### ISSUE TITLE
When DBInstance has non-nil `dbClusterIdentifier`, must not set `allocatedStorage` 

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#1028]
For the `DBInstance` RDS resource, if you set the `spec.dbClusterIdentifer` field to a non-nil value, you cannot set the `allocatedStorage` field to a non-nil value otherwise you will get an error from the `ModifyDBInstance` API call:

```
InvalidParameterCombination: The specified DB instance is a member of a DB Cluster. Storage grows based on usage. You don't need to set it explicitly.
```

Unfortunately, `DescribeDBInstances` returns a value of `1` for `allocatedStorage` for a `DBInstance` with a non-nil `dbClusterIdentifier` field.

This means that if the RDS controller for ACK sees that the observed state of any other field for the DBInstance is different from the desired state of that field  -- for example if the AvailabilityZone changes -- the controller calls the RDS `ModifyDBInstance` API call and will set the DBInstance's `spec.allocatedStorage` field to `1` and then we run into the `InvalidParameterCombination` error. We need to always set `allocatedStorage` to `nil` in the Input shape for `ModifyDBInstance` **when `dbClusterIdentifier` is non-nil**.

This is similar to the issue #917 where certain fields in the Input shape for ModifyDBCluster needed to be set to `nil` when engineMode was `serverless`.

**Comment by jaypipes** [comment]
Well, the good news is that I've reproduced this with an e2e test. The bad news is that the solution is going to add a bunch of custom code :(

**Comment by brucegucode** [comment]
I believe this issue should be fixed , i tried changing instance type and it's working as expected.

**Comment by brucegucode** [comment]
code is merged, this issue can be resolved
