### ISSUE TITLE
Missing `ConditionTypeResourceSynced` after updating a CR

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1030]
(Issue only tested with only s3 for now)

**Describe the bug**
After updating a CR, it looks like the update code path doesn't append a `ConditionTypeResourceSynced` to the conditions list.

**Steps to reproduce**

- Create an s3 bucket resource
- Add a `tagging` Spec field
- Run `k describe bucket <name>` /  `k get bucket <name> -o yaml`

**Expected outcome**
Expecting to see `ConditionTypeResourceSynced` in `Status.Conditions` array

**Environment**

* Using EKS (yes/no), if so version?  1.20.4
* AWS service targeted: s3

**Comment by RedbackThomson** [comment]
Condition of at least "Synced" should now be present on all resources as per https://github.com/aws-controllers-k8s/runtime/pull/61
