### ISSUE TITLE
Add affinity and toleration option to api gateway controller

### ISSUE THREAD

**Issue by ops-hummus** [aws-controllers-k8s/community#1038]
I'm using the apigatewayv2 controller and I'm trying to control where my application is being created. I have a specific nodes for controllers but since I don't have an affinity attribute I need to save the chart locally and add the affinity attribute by myself. It's a bit frustrating since I don't want to manage this chart. 

**Describe the solution you'd like**
Saved the chart locally and added affinity attribute manually.

**Describe alternatives you've considered**
If it's not possible, it would be nice to understand why.

**Comment by philnichol** [comment]
Hi @jaypipes , hope you don't mind but I raised this that should address this https://github.com/aws-controllers-k8s/code-generator/pull/249
Thanks in advance for your review, and it's my first contribution to this project, so apologies for any missing stemps!
