### ISSUE TITLE
ECR Lifecycle policies

### ISSUE THREAD

**Issue by svmundada** [aws-controllers-k8s/community#1043]
**Is your feature request related to a problem?**
As per the [spec](https://pkg.go.dev/github.com/aws-controllers-k8s/ecr-controller/apis/v1alpha1#RepositorySpec) for `ecr.services.k8s.aws/v1alpha1.Repository` we cannot create [lifecycle policies]( https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html). This feature would really help us ( mono-repo users).

**Describe the solution you'd like**
Users should be able to configure Lifecycle policies as part of repository/ecr creation.

**Suggestion**
Lifecycle policies seem like central configuration for ECR (account + region ), should we have different CR to represent central config and `Repository` should reference it ?

**Comment by svmundada** [comment]
@RedbackThomson Sorry for the delayed response.
Understood, we were just looking for a way to manage ECR policies with ACK. It's not critical but any timelines?

**Comment by A-Hilaly** [comment]
@svmundada i'm taking this next week
/assign

**Comment by A-Hilaly** [comment]
@svmundada we just released ecr-controller `v0.0.10` which adds support of lifecycle policies. A new field is added to the resource spec now: `spec.LifecyclePolicy`
