### ISSUE TITLE
Add ACK operators to Community Operators (OperatorHub.io and Openshift OperatorHub)

### ISSUE THREAD

**Issue by trgeiger** [aws-controllers-k8s/community#1045]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

It would be great to add to the ACK automation pipelines the ability to publish the ACK operators to the Community Operator repositories.

**Describe the solution you'd like**
A description of what you want to happen.

The initial publication will require opening PRs in 2 different repositories, one for OperatorHub.io, the other for the embedded OperatorHub that's present in Openshift 4 (details on these here: https://k8s-operatorhub.github.io/community-operators/contributing-where-to/)

I believe there will need to be 1 PR per operator as well (2 PRs per operator if contributing to both repositories), given how the documentation lays out the current process.

The full details on contributing with all requirements are at this link under the "Contributing" headline: https://k8s-operatorhub.github.io/community-operators/contributing-prerequisites/

Before publication:
* we will need to merge the AdoptedResource reconciler changes in aws-controllers-k8s/runtime#59
* we should also probably wait until we get Openshift installation documentation merged aws-controllers-k8s/community#1039

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by vijtrip2** [comment]
The above automation PR will create separate issues for each service controller whenever there is missing olmconfig.yaml or ci.yaml or when automatic olm bundle generation fails.

Closing this parent issue.
