### ISSUE TITLE
AWS App Mesh service controller

### ISSUE THREAD

**Issue by eminalemdar** [aws-controllers-k8s/community#1051]
## New ACK Service Controller

Support for [**AWS App Mesh**]

### List of API resources

List the API resources in order of importance to you:

1) [Proxy]
2) [Traffic Routing]
3) [Service to Service Authentication]
4) [Traffic Policies]

**Comment by jaypipes** [comment]
Hi @eminalemdar! Thanks for submitting this service controller request!

Were you aware of the existing AppMesh controller for Kubernetes project?

https://github.com/aws/aws-app-mesh-controller-for-k8s/

I'm wondering if perhaps you want to see support for proxy, traffic routing, service-to-service authentication and traffic policy custom resources in that controller? Currently, it only supports Mesh, VirtualNode, VirtualGateway, VirtualRouter and VirtualService resources along with integrations for AWS CloudMap.

**Comment by eminalemdar** [comment]
> Hi @eminalemdar! Thanks for submitting this service controller request!
> 
> Were you aware of the existing AppMesh controller for Kubernetes project?
> 
> https://github.com/aws/aws-app-mesh-controller-for-k8s/
> 
> I'm wondering if perhaps you want to see support for proxy, traffic routing, service-to-service authentication and traffic policy custom resources in that controller? Currently, it only supports Mesh, VirtualNode, VirtualGateway, VirtualRouter and VirtualService resources along with integrations for AWS CloudMap.

Hello @jaypipes! I wasn't aware of the AppMesh Controller but does this controller works like the controllers in here?

**Comment by jaypipes** [comment]
> Hello @jaypipes! I wasn't aware of the AppMesh Controller but does this controller works like the controllers in here?

No, the AppMesh controller for Kubernetes is a hand-built Kubernetes controller, not a code-generated one like ACK controllers are. However, functionally, the AppMesh controller for Kubernetes I linked above is more feature-rich than a control-plane-only controller like ACK.
