### ISSUE TITLE
update sdk for FIPS endpoint support -> AWS SDK 1.42.0 [crossplane/provider-aws]

### ISSUE THREAD

**Issue by smcavallo** [aws-controllers-k8s/community#1059]
aws sdk released new method of configuring FIPS endpoints
See - https://github.com/aws/aws-sdk-go/pull/3938

crossplane/provider-aws bound to the SDK version that the code-generator uses because its output is used in this repo and SDK versions have to match.  See (crossplane/provider-aws#918)

Describe the solution you'd like
update aws-go-sdk 1.37.10 to 1.42.0

https://github.com/aws/aws-sdk-go/releases/tag/v1.42.0

**Comment by A-Hilaly** [comment]
Closing in favor of https://github.com/aws-controllers-k8s/community/issues/1128
