### ISSUE TITLE
Secrets Integration to Protect CRD Fields

### ISSUE THREAD

**Issue by alina-kim** [aws-controllers-k8s/community#106]
The AWS RDS API, among others, requires sensitive fields to be displayed in plain text. To protect such fields, we want to:

- Allow users to create Kubernetes Secrets and store their sensitive data in them
- Receive Secret references in place of target fields and pass the Secret data to the desired AWS API

Link to the [Secrets Integration design proposal](https://github.com/alina-kim/aws-controllers-k8s/blob/ack-secrets/docs/design/proposals/secrets/secrets.md)

**Comment by RedbackThomson** [comment]
Added as part of https://github.com/aws-controllers-k8s/code-generator/pull/21
