### ISSUE TITLE
[Resource-Relationship] Implement referencing resource(s) from same api-group

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#1063]
Parent task: https://github.com/aws-controllers-k8s/community/issues/545

This issue will track implementation for adding reference of another resource or list of resources within same API Group of a resource.

Example: ApiGatewayv2 `Integration` resource should be able to provide reference of `API` resource to find `APIID`.

**Comment by jaypipes** [comment]
Remaining (as of 2022-01-14) part to do is ResourceSynced condition generation, which is waiting on #1064
