### ISSUE TITLE
Handle nested fields in SetFieldConfig

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#1065]
While implementing the solution for #178, Bryan [pointed out](https://github.com/aws-controllers-k8s/code-generator/pull/232#pullrequestreview-801911964) that the solution would not work for nested field paths.

We should address this gap in functionality.

**Comment by RedbackThomson** [comment]
@brycahta Is there work left to do for this?

**Comment by brycahta** [comment]
@RedbackThomson No work left. 

I was going to resolve once we cut a release with these changes/fixes. If y'all have a different process feel free to resolve.
