### ISSUE TITLE
Release artifacts on github 

### ISSUE THREAD

**Issue by svmundada** [aws-controllers-k8s/community#1074]
**Is your feature request related to a problem?**
At present, ACK controllers don't host any artifacts (yamls), so we have to clone the controller repo and translate changes to our repo. 

**Describe the solution you'd like**
Having release artifacts like https://github.com/tektoncd/pipeline/releases/tag/v0.30.0 would easy out the process to update controllers. 
Use case: Additional patches required over base release can be handled by kustomize patches and these change very rarely, so updates are generally a breeze.

**Comment by A-Hilaly** [comment]
@svmundada Did you try our public helm charts? we publish them in our public ECR repository.

**Comment by RedbackThomson** [comment]
If you would like to reference the `Kustomization` files that are generated for each controller, and for every release, you can do that directly using `kubectl apply -k` like so:

```bash
kubectl apply -k "github.com/aws-controllers-k8s/s3-controller/config/default?ref=v0.0.7"
```

**Comment by svmundada** [comment]
@A-Hilaly 
I am yet to try it out, but yes it looks promising.

@RedbackThomson 
Thanks, the above kustomization feature works perfectly fine. One small request apart from the regular update, if we can get `image: ack-s3-controller:latest` updated according to specific `ref` that'd be great to have.

**Comment by RedbackThomson** [comment]
That's interesting. I didn't realise these Kustomizations point to this seemingly arbitrary image. 

Realistically we would want it to be `image: public.ecr.aws/aws-controllers-k8s/s3-controller:v0.0.7`. I think these manifests are just from an outdated version.

I'll make this into a separate bug report and assign myself

**Comment by RedbackThomson** [comment]
https://github.com/aws-controllers-k8s/community/issues/1076

**Comment by svmundada** [comment]
@RedbackThomson Thanks, also can we check for other fields in kustomize generated artifacts if they are similar to helm?
