### ISSUE TITLE
Kustomization points to outdated image and tag

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1076]
**Describe the bug**
The [image](https://github.com/aws-controllers-k8s/s3-controller/blob/main/config/controller/kustomization.yaml#L6-L9) used in the Kustomization deployment manifest point to `ack-$SERVICE-controller:latest`. If you attempt to deploy this Kustomization directly (`kubectl apply -k config/default`), the pod will fail to even start since the image does not exist.

**Expected outcome**
The deployment should contain the correct path to the ECR repository with a valid tag (pinned to the latest version, as we do for Helm) eg. `image: public.ecr.aws/aws-controllers-k8s/s3-controller:v0.0.7`.

**Comment by jaypipes** [comment]
There's history behind the way the kustomization files currently work. When I wrote the original Bash-based e2e tests, I used KinD to create the local test k8s cluster, built a Docker image containing the local source code of the controller under test, tagged said Docker image with `ack-$SERVICE-controller:latest` (note: there is no registry/repository component to the tag like there is for the Helm-based stuff) and then used a simple Kustomize overlay to start up the controller in the KinD cluster. The Kustomization overlay was never meant to be used for anything other than local testing, thus the reason for the `:local` tag stuff.
