### ISSUE TITLE
Ability to provide API version as resource-specific configuration

### ISSUE THREAD

**Issue by muvaf** [aws-controllers-k8s/community#1089]
**Is your feature request related to a problem?**

Currently, you can give version input, i.e. `v1alpha1`, as a flag to the CLI but that means all members of that API group get to use the same version. However, there are cases where only a few resources in the given group are meant to be bumped to `v1beta1` for example.

**Describe the solution you'd like**

A new configuration field in [`ResourceConfig`](https://github.com/aws-controllers-k8s/code-generator/blob/285d87b66b62fbfb859986ddf74c9f9b6ae743fb/pkg/generate/config/resource.go#L22) would give enough level of granularity for this configuration.

**Comment by muvaf** [comment]
If this sounds good to you all, I can dive into the code to see how we can implement it for both ACK and Crossplane. cc @jaypipes and friends

**Comment by A-Hilaly** [comment]
Sounds great @muvaf, i believe this will also have an impact on https://github.com/aws-controllers-k8s/code-generator/pull/122. We will have to generate webhooks for specific resource rather than full api versions

**Comment by muvaf** [comment]
Fixed in https://github.com/aws-controllers-k8s/code-generator/pull/266
