### ISSUE TITLE
Does rds-controller cover read replica?

### ISSUE THREAD

**Issue by jamesseo-alation** [aws-controllers-k8s/community#1109]
**What is the URL of the document?**

**Which section(s) is the issue in?**

**What needs fixing?**

**Additional context**

I need to append read replica instance on a db instance and need to check if rds-constroller can support this feature.
When I read dbInstnace CRD, it doesn't include read replica related property. Can you share any doc about read replica setup by rds-controller?

**Comment by RedbackThomson** [comment]
The RDS controller spec contains the [`replicationSourceIdentifier`](https://github.com/aws-controllers-k8s/rds-controller/blob/main/config/crd/bases/rds.services.k8s.aws_dbclusters.yaml#L309) field. As per the [RDS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Replication.CrossRegion.html#AuroraMySQL.Replication.CrossRegion.Creating), you are expected to create the master replica first, and then specify the ARN of that cluster in the `replicationSourceIdentifier` when creating the read replica. 

The ACK controller does not have any additional logic on top of the [AWS SDK Go `CreateDBCluster` operation](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBCluster) when creating DB clusters.

**Comment by jaypipes** [comment]
@jamesseo-alation please see #893. Closing this as duplicate.
