### ISSUE TITLE
crossplane: unable to generate prometheusservice

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#1114]
**Describe the bug**
https://github.com/crossplane/provider-aws/issues/977
we are unable to generate new service prometheusservice via code-generator - which is part of 1.37.10 go-sdk

`Error: service prometheusservice not found`

https://github.com/aws/aws-sdk-go/tree/v1.37.10/service/prometheusservice
https://docs.aws.amazon.com/sdk-for-go/api/service/prometheusservice/

**Steps to reproduce**
make generate

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by jaypipes** [comment]
Hi @haarchri! Try `amp` :)

https://github.com/aws/aws-sdk-go/blob/v1.37.10/models/apis/amp/2020-08-01/api-2.json

**Comment by haarchri** [comment]
thanks looks like this is working ;)

**Comment by jaypipes** [comment]
> thanks looks like this is working ;)

no prob! it's a common issue... where the serviceID doesn't match the service long-form package name...

**Comment by haarchri** [comment]
but i think we need to set .ServicePackageName via generator-config.yaml otherwise the generated code will use `amp` as .ServicePackageName  but here we need `prometheusservice`
https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/crossplane/pkg/controller.go.tpl#L14

**Comment by haarchri** [comment]
```
cat generator_config.yaml
model_name: amp 
```
and in makefile we can use `prometheusservice`
