### ISSUE TITLE
support updating tags for Role and Policy resources in IAM

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#1119]
In order to update the tags applied to an IAM Role and Policy resource, one must call the [`TagRole`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_TagRole.html), [`TagPolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_TagPolicy.html), [`UntagRole`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_UntagRole.html) and [`UntagPolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_UntagPolicy.html) IAM API calls.

This is inconsistent with virtually all other AWS API resources, which use the "Tagris" [`TagResources`](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_TagResources.html) and [`UntagResources`](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_UntagResources.html) AWS Resource Group Tagging API. Why this is the case is unknown to me, but this means that we need to add some custom code to update tag collections on IAM resources instead of copying what has been done for other controllers. :(

Background on tagging IAM resources (including the statement that IAM resources cannot be tagged using the AWS Resource Group Tagging APIs or TagEditor): https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html

**Comment by RedbackThomson** [comment]
Both are now supported! Woo hoo.
