### ISSUE TITLE
The `recommended-inline-policy` file does not exist in opensearchservice-controller repository

### ISSUE THREAD

**Issue by faganihajizada** [aws-controllers-k8s/community#1120]
**Describe the bug**
According to [documentation](https://aws-controllers-k8s.github.io/community/docs/user-docs/irsa/#:~:text=the%20IAM%20role-,%23,-Note) `INLINE_POLICY` can be set by executing:
```
INLINE_POLICY_URL=${BASE_URL}/config/iam/recommended-inline-policy
INLINE_POLICY="$(wget -qO- ${INLINE_POLICY_URL})"
```
But the `recommended-inline-policy` file does not exist in repository https://github.com/aws-controllers-k8s/opensearchservice-controller

**Steps to reproduce**

Set `BASE_URL=https://raw.githubusercontent.com/aws-controllers-k8s/${SERVICE}-controller/main ` as described in the documentation and try to get `INLINE_POLICY` from it as described above.

**Expected outcome**
INLINE_POLICY should be set as expected and apply them to the newly created IRSA role

**Comment by jaypipes** [comment]
Hi @faganihajizada! The documentation you linked above states that an inline policy is optional but should be present if `config/iam/recommended-policy-arn` file is missing from the controller repo. In the case of the opensearchservice-controller repository, the recommend-policy-arn file is indeed present, though:

https://github.com/aws-controllers-k8s/opensearchservice-controller/blob/main/config/iam/recommended-policy-arn

**Comment by faganihajizada** [comment]
Thanks, @jaypipes!
