### ISSUE TITLE
Provision AWS Rest API using ACK for Amazon API Gateway v2

### ISSUE THREAD

**Issue by palisado** [aws-controllers-k8s/community#1125]
Hi All,

I have question regarding ACK for Amazon API Gateway v2. I was following this guide to integrate AWS HTTP API Gateway from our K8s cluster using ACK for Amazon API Gateway v2: https://aws.amazon.com/blogs/containers/integrate-amazon-api-gateway-with-amazon-eks/
The guide worked fine and I was able to create AWS HTTP API Gateway.

Now, I have a requirement to have AWS WAF attached to API Gateway and currently AWS HTTP API Gateway does not support WAF (verified by AWS Support).
I need to modify the above solution to provision AWS REST API Gateway instead of HTTP API Gateway.

My questions are:
1. Is ACK for Amazon API Gateway v2 support the creation of AWS REST API Gateway?
2. How can we modify this apigw-api.yaml file to provision/ create AWS REST API Gateway (see below)?

#Code for apigw-api.yaml:
####################

`apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: apitest-private-nlb
spec:
  body: '{
              "openapi": "3.0.1",
              "info": {
                "title": "ack-apigwv2-import-test-private-nlb",
                "version": "v1"
              },
              "paths": {
              "/$default": {
                "x-amazon-apigateway-any-method" : {
                "isDefaultRoute" : true,
                "x-amazon-apigateway-integration" : {
                "payloadFormatVersion" : "1.0",
                "connectionId" : "4tmoc6",
                "type" : "http_proxy",
                "httpMethod" : "GET",
                "uri" : "arn:aws:elasticloadbalancing:us-east-2:123456789:listener/net/k8s-default-authorse-0a5d6089c2/09873328923/89042fe223",
               "connectionType" : "VPC_LINK"
                  }
                }
              },
              "/meta": {
                  "get": {
                    "x-amazon-apigateway-integration": {
                       "uri" : "arn:aws:elasticloadbalancing:us-east-2:123456789:listener/net/k8s-default-echoserv-29e1df501d/09873328923/f5de1a00b80f5ebe",
                      "httpMethod": "GET",
                      "connectionId": "4tmoc6",
                      "type": "HTTP_PROXY",
                      "connectionType": "VPC_LINK",
                      "payloadFormatVersion": "1.0"
                    }
                  }
                }
              },
              "components": {}
        }'`

Thanks in advanced.
Budi

**Comment by vijtrip2** [comment]
Thanks for reaching out!

> Is ACK for Amazon API Gateway v2 support the creation of AWS REST API Gateway?
> How can we modify this apigw-api.yaml file to provision/ create AWS REST API Gateway (see below)?

No, apigatewayv2 controller is built from `aws-sdk-go/apigatewayv2` and those API do not support creation of REST APIs.
ACK team will need to build another "apigateway" controller (NOTE: no v2), which will support REST API creation.

I will create a GH issue which you can follow but it's not on our priority list right now.

**Comment by vijtrip2** [comment]
https://github.com/aws-controllers-k8s/community/issues/1126

**Comment by palisado** [comment]
Thanks for the info and quick reply Vijay.
I will check the GH #1126 issue that you created.

Cheers,
Budi
