### ISSUE TITLE
IAM controller typo in policy example

### ISSUE THREAD

**Issue by ops-hummus** [aws-controllers-k8s/community#1131]
Hi,
You need to replace the end of the line of the policy, from . to ,

https://github.com/aws-controllers-k8s/iam-controller/blob/8330444befbbced91561cdf090553f1322c9e2ae/config/iam/recommended-inline-policy#L11

**Comment by vijtrip2** [comment]
Thanks for pointing out the error.
Fixed now!

**Comment by ops-hummus** [comment]
@vijtrip2 
Glad to help :)
Do you have an ETA on when you are going to release a stable build?

**Comment by vijtrip2** [comment]
> Do you have an ETA on when you are going to release a stable build?
No ETA yet.
