### ISSUE TITLE
`ACK.ResourceSynced` condition gets removed in ACK runtime `v0.16.0`

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#1133]
**Describe the bug**
`ACK.ResourceSynced` gets removed after successful creation of the resource in ACK runtime `v0.16.0`

### Context

In the new release `v0.16.0`, ACK runtime had a [change](https://github.com/aws-controllers-k8s/runtime/commit/5afdd00a4bf2587efa53dbf7693f4a550f43fea4) to reset(remove) old `Status.Conditions` at the start of reconciler loop, and set latest `Status.Conditions` again during reconciliation. The latest `Status.Conditions` are then patched into the K8s object status at end of reconciler loop.

If at the end of reconciler loop, there is no `ACK.ResourceSynced` condition present inside `Status.Conditions`, then `ACK.ResourceSynced=Unknown` condition gets added.

`ACK.ResourceSynced` condition is an important condition for customers to determine whether the resource is synced or still under reconciliation process. The above mentioned change was made as a precursor change for a [new feature](https://github.com/aws-controllers-k8s/code-generator/pull/247) to determine `ACK.ResourceSynced` condition by introspecting `Spec/Status` field values, or invoking AWS APIs, and NOT just relying on whether any error occurred during reconciliation loop or not.

### Problem

While the proposed [feature](https://github.com/aws-controllers-k8s/code-generator/pull/247) for setting `ACK.ResourceSynced` condition by introspecting `Spec/Status` fields is still under development, there is a side-effect from the precursor change causing test failures in various controllers(with new runtime) that assert on resource condition.

The side-effect is that, Even if `ACK.ResourceSynced` condition was set correctly during `Create` operation, the following reconciler loops remove this condition at beginning of loop. If the `Update` operation uses hooks to set this condition again, there are no problems but following edge case is still not handled.

Edge Case:
When a resource is first created, a finalizer is added and metadata of K8s resource is patched, which triggers a second reconciliation loop. During the second reconciliation loop, conditions are removed at beginning and since resource neither gets created, nor gets updated in this second loop, the `ACK.ResourceSynced` condition is never set and default to `ACK.ResourceSynced=Unknown` which is problematic, when resource has been successfully created.

### Proposed Solutions (Sorted in order of speed of implementation)

1) Revert the precursor change, and fall back to old behavior. Add this change back when `AWSResourceManager.IsResourceSynced()` method is [implemented](https://github.com/aws-controllers-k8s/code-generator/pull/247)

2) Keep the precursor [change](https://github.com/aws-controllers-k8s/runtime/commit/5afdd00a4bf2587efa53dbf7693f4a550f43fea4) but instead of adding `ACK.ResourceSynced=Unknown` when condition is missing at the end, Set `True or False` depending on whether there was any `reconciler error` or not.

3) Complete the implementation of determining the `ACK.ResourceSynced` condition from `AWSResourceManager.IsResourceSynced()` method and not rely on hook code from various Create/Update methods.

**Comment by jaypipes** [comment]
@vijtrip2 for solution (2), could we potentially change that to: "Set True or False depending on whether there was any reconciler error AND whether there was no Diff found in the Delta"? In other words, set ACK.ResourceSynced=True when there was no error in the ReadOne and the returned resource from ReadOne matches the Spec fields of the originally-supplied resource?

**Comment by acornett21** [comment]
I feel that clearing out the statuses completely on each reconcile leads to a bad UI/UX experience. IE a user sees `Success` in the Status for a `Bucket` for example, then the Status would become not present and the user would no longer see what they preciously say 'Ready/Failed/etc', which is confusing.

**Comment by vijtrip2** [comment]
> I feel that clearing out the statuses completely on each reconcile leads to a bad UI/UX experience.

That is not correct :) Only `Status.Conditions` is cleared and calculated again during reconciler loop.

> Status would become not present and

This is not correct either, Status is patched. The flow is not like 
"remove -> add again" but it's more like
 "in-memory remove -> in-memory add latest conditions ->  patch on disk"

**Comment by acornett21** [comment]
I was referring to `Status.Conditions`, sorry to not state that clearly. 

Doing the below I never see any value being written to `Status.Conditions`
`kubectl get bucket example-8675309 -oyaml -w`

yields the below
```
status:
  ackResourceMetadata:
    ownerAccountID: <omitted>
  location: http://example-8675309.s3.amazonaws.com/
```

Am I missing something?

**Comment by vijtrip2** [comment]
Thanks @acornett21 , for detailed explanation.

This may be a specific bug for S3 controller, but the new [patch](https://github.com/aws-controllers-k8s/runtime/commit/c0254e470c2a905f5f984d735c1c49d9fef7d982) we just made, will make sure at least 'ACK.ResourceSynced' condition will always be present. If "True" or "False" synced status cannot be determined, atleast "Unknown" status will be populated.

There is also a separate [effort](https://github.com/aws-controllers-k8s/code-generator/pull/247) to correctly determine 'ACK.ResourceSynced' condition as "True"/"False" and making sure it is always present. After the mentioned PR is merged, we will audit all the controllers and make sure setting of 'ACK.ResourceSynced' condition is consistent.

**Comment by RedbackThomson** [comment]
After reading articles like the following: https://maelvls.dev/kubernetes-conditions/ , it seems that the way we handle conditions does not match the upstream Kubernetes standard. I have also looked at the fluxcd/pkg repository (https://github.com/fluxcd/pkg/tree/main/runtime/conditions) and see that they handle conditions in the same way as `Pod`. 

Would it be possible to align our designs more so to [those](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Condition). If we cannot change our version of condition to `metav1.Condition` directly, then our changes may include (at least):
- Adding a `LastTransitionTime` property to each condition
- Adding an `ObservedGeneration` property to each condition 
- Not removing any conditions - only updating or adding new conditions (keyed by `Type`)

As for `ResourceSynced`, this would solve our problem by having our initial condition (after the first reconciliation loop) be `Unknown`, then updating the condition as and when needed afterwards.

**Comment by acornett21** [comment]
@vijtrip2 After testing other controllers (elasticache/mq) it does look like this error is specific in S3, which doesn't really make sense, as all controllers share the same runtime code. I'll test that patch against S3 to see if that solves the issue in that controller as well.

Below is an output from elasticache
```
status:
  ackResourceMetadata:
    arn: arn:aws:elasticache:us-west-2:625535193395:usergroup:demoid
    ownerAccountID: <omitted>
  conditions:
  - status: "True"
    type: ACK.ResourceSynced
  - lastTransitionTime: "2022-01-20T15:01:35Z"
    message: Resource already exists
    reason: This resource already exists but is not managed by ACK. To bring the resource
      under ACK management, you should explicitly adopt the resource by creating a
      services.k8s.aws/AdoptedResource
    status: "True"
    type: ACK.Terminal
  status: active
  ```
  
  The article that @RedbackThomson shared is how I've seen conditions handled in other operators that have been built with `operator-sdk`

**Comment by vijtrip2** [comment]
Thanks for diving deeper, @acornett21 !!

In the current state of world, individual service controller code is responsible for adding `ResourceSynced` conditions, that's why some services show it and some not.

First step to bring consistency across controllers is setting these condition from ACK runtime when the service controller code is not setting them. ACK runtime will set `Unknown` status. All the new release of controllers should have this feature.

Next step is to determine ResourceSynced status from resource fields and not rely on service controllers to implement conditions logic. This will allow ACK runtime to determine True/False Synced status instead of Unknown. [Work](https://github.com/aws-controllers-k8s/code-generator/pull/247) is tracked here.

**Comment by vijtrip2** [comment]
The newly released v0.16.2 worked as expected for most controllers but it changed the `ACK.ResourceSynced` condition behavior for some asynchronous APIs.

### What Changed in `v0.16.2`?

In the release `v0.16.2`, ACK runtime added the `ACK.ResourceSynced = True` condition, when the `desired` and `latest` spec were identical. IOW, if there is no delta between desired and latest resource, mark the resource as `Synced` and do not requeue.

This corrected the behavior for many controllers, where `ACK.ResourceSynced` condition was getting cleared as mentioned in the `Edge Case` inside issue description. 

### How it impacted asynchronous resource creation?

Some ACK controllers, ex: `rds-controller`, handle the asynchronous creation of resource by continuously requeueing the resource for reconciliation until the terminal state change occurs. For Ex: rds-controller's `DBCluster` ResourceManager sets the `ACK.ResourceSynced = False` condition  if DBCluster state in not `available`. rds-controller sets this condition in the `ReadOne` method using custom hooks. When ACK runtime , sees `ACK.ResourceSynced = False` on a resource, it requeues the resource for further reconciliation.

With the new change in `v0.16.2` since there were no delta between desired and latest spec after the ReadOne operation, `ACK.ResourceSynced = True` was set in resource Status and ACK runtime stopped requeueing the resource, which caused the `ACK.ResourceSynced = True` condition to incorrectly get set and hence resulted in e2e test failure.


### Bug Fix

#### [Proposed Solution](https://github.com/aws-controllers-k8s/code-generator/pull/247)
* A new `AWSResourceManager.IsSynced()` will be introduced to determine the Synced status of resource. This will help get rid of custom hooks present in Read/Create/Update operations for setting `ACK.ResourceSynced` condition
* After the ACK reconciler has performed `ReadOne + Create/Update + LateInitialize` operation, it will call 'IsSynced' method to set the `ACK.ResourceSynced` condition
* `handleRequeues()` method will be called After `IsSynced` method to correctly requeue the resource based on `ACK.ResourceSynced` condition
* By default when no configuration is provided, `IsSynced` method will return True. This will work for majority of synchronous AWS APIs and will not require every service team to add Synced condition in generator.yaml for every resource
* This solution will get rid of various custom hooks present sporadically across service controllers and bring consistency.

Please see different scenarios below on how this conditions will be updated by proposed solution.

#### Scenarios

a) **ReadOne Failure:** `ensureCondition` method sets the `ACK.ResourceSynced = False`, `IsSynced` method is never called, requeue occurs
b)  **Create Failure:** `ensureCondition` method sets the `ACK.ResourceSynced = False`, `IsSynced` method is never called, requeue occurs
c) **Update Failure:** `ensureCondition` method sets the `ACK.ResourceSynced = False`, `IsSynced` method is never called, requeue occurs
d) **LateInitialize Failure:** `ensureCondition` method sets the `ACK.ResourceSynced = False`, `IsSynced` method is never called, requeue occurs
e) **Successul Create:**  `IsSynced` method correctly determines the `ACK.ResourceSynced` and `handleRequeues` method determines the requeue
f) **Successul Update:**  `IsSynced` method correctly determines the `ACK.ResourceSynced` and `handleRequeues` method determines the requeue 
g) **No delta in desired, latest spec:** `IsSynced` method correctly determines the `ACK.ResourceSynced` and `handleRequeues` method determines the requeue

NOTE: for asynchronous resource creation/update/no-delta, the `IsSynced` method will correctly determine the Synced status based on resource state.

**Comment by RedbackThomson** [comment]
> A new `AWSResourceManager.IsSynced()` will be introduced to determine the Synced status of resource

Would you mind clarifying what the `IsSynced` method actually does? Is this more than just the getter for the `ResourceSynced` condition?

**Comment by vijtrip2** [comment]
> Would you mind clarifying what the IsSynced method actually does? Is this more than just the getter for the ResourceSynced condition?

Updated comment above with following,

> This `IsSynced()` method will be auto-generated based on Synced Config provided in `generator.yaml` file. In a nutshell, this method will return true/false depending on whether a resource state meets the criteria of being Synced. Ex: For rds DBCluster, `IsSynced` will return `true` only if `DBCluster.Status.Status` is `available` . More details [here](https://github.com/aws-controllers-k8s/code-generator/pull/247)

**Comment by jaypipes** [comment]
> After reading articles like the following: https://maelvls.dev/kubernetes-conditions/ , it seems that the way we handle conditions does not match the upstream Kubernetes standard.

@RedbackThomson specifically what are you referring to in the above article that we do not align with?

> I have also looked at the fluxcd/pkg repository (https://github.com/fluxcd/pkg/tree/main/runtime/conditions) and see that they handle conditions in the same way as `Pod`.

In what way exactly? The Flux `conditions` package is generic to any Condition-like structs and is mostly there to give Flux an idea of the "polarity" of different ConditionTypes.

> Would it be possible to align our designs more so to [those](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Condition). If we cannot change our version of condition to `metav1.Condition` directly, then our changes may include (at least):
> 
> * Adding a `LastTransitionTime` property to each condition

We already have this: https://github.com/aws-controllers-k8s/runtime/blob/f142275219901dfc48c3787db3f49145c559f489/apis/core/v1alpha1/conditions.go#L77

> * Adding an `ObservedGeneration` property to each condition

The problem with adding an `ObservedGeneration` attribute to the `Condition` is that by definition, that would pin ACK controller implementation to being single-writer and require us to always use the leader election system from upstream controller-runtime. The reason is because the latest "observed generation" stored in that field is the observation of a **single** controller daemon. That information more appropriately belongs **inside that controller daemon state itself** and not in the etcd state storage shared by multiple controllers that may want to read and write information for the same resource.

Put another way, if you have two writers mutating a resource, ObservedGeneration is useless because it only represents the latest observed generation that *one* of those writers saw.

> * Not removing any conditions - only updating or adding new conditions (keyed by `Type`)

Conditions represent the state of a resource during a particular reconciliation run. Leaving old conditions in the Conditions collection run just means stale information is kept around unnecessarily, IMHO. Events, on the other hand, are more what you're looking for (and I'd be OK emitting events for the historical record of transition of important conditions) if that's what we want to do.

> As for `ResourceSynced`, this would solve our problem by having our initial condition (after the first reconciliation loop) be `Unknown`, then updating the condition as and when needed afterwards.

That is what currently happens, no?

**Comment by jaypipes** [comment]
> With the new change in `v0.16.2` since there were no delta between desired and latest spec after the ReadOne operation, `ACK.ResourceSynced = True` was set in resource Status and ACK runtime stopped requeueing the resource, which caused the `ACK.ResourceSynced = True` condition to incorrectly get set and hence resulted in e2e test failure.

The ACK.ResourceSynced condition should have been set to True if and only if there was no ACK.ResourceSynced condition already set on the `latest` resource. The rds-controller should have set ACK.ResourceSynced to False in the ReadOne resource manager method, so it's a bug if the code added in 0.16.2 *reset* the ACK.ResourceSynced to True instead of ignoring the existing (set by the ReadOne method) value of ACK.ResourceSynced.

**Comment by vijtrip2** [comment]
> The rds-controller should have set ACK.ResourceSynced to False in the ReadOne resource manager method, so it's a bug if the code added in 0.16.2 reset the ACK.ResourceSynced to True instead of ignoring the existing (set by the ReadOne method) value of ACK.ResourceSynced.

This is correct, v0.16.2 was overriding irrespective of checking if the condition already exists. That's why the e2e tests started failing.

However if we solely start to determine the `ACK.ResourceSynced` condition from `IsSynced` call inside `reconciler.Sync()` method, It will give us opportunity to remove all the hook code from ReadOne/Create/Update methods. It will also make debugging easier, because currently we go looking at all the hooks for where the condition was set. It will centralize the condition handling. wdyt?

**Comment by RedbackThomson** [comment]
> Put another way, if you have two writers mutating a resource, ObservedGeneration is useless because it only represents the latest observed generation that one of those writers saw.

Is that not what `Pod` follows as well? I believe you that `ObservedGeneration` is limiting, I think I just don't understand the technical points for how it is.

> Leaving old conditions in the Conditions collection run just means stale information is kept around unnecessarily

Yeah ... you make a good point with this one. I think what events are probably the better place for something like this.
