### ISSUE TITLE
Add security flags to go build step

### ISSUE THREAD

**Issue by philnichol** [aws-controllers-k8s/community#1134]
**Is your feature request related to a problem?**
The way the controller binary is compiled could include security flags.

**Describe the solution you'd like**
For example, we could include the `-buildmode=pie` flag to `go build` to get ASLR, improving security of the binary with minimal effort, the only cost being a small increase in final image size.
Some more info on this flag can be found in [this blogpost](https://devdrivensecurity.substack.com/p/hardening-go-programs-1n)
Others might have other suggestions or similar "quick wins"?

Happy to contribute if there's any interest

Output from gdb on current controller:
```shell
# gdb -batch -ex "checksec ./controller"
GEF for linux ready, type `gef' to start, `gef config' to configure
96 commands loaded for GDB 10.1.90.20210103-git using Python engine 3.9
[+] checksec for '/test/controller'
Canary                        : ✘
NX                            : ✓
PIE                           : ✘
Fortify                       : ✘
RelRO                         : ✘
```

Edit:  Looks like it adversely affected memory usage in [kubernetes](https://github.com/kubernetes/kubernetes/pull/105352) when they implemented this, so worth keeping that in mind.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by RedbackThomson** [comment]
This does seem like an easy win. Our controllers have a fairly small memory overhead, so hopefully the Kubernetes issue doesn't surface for us. Interested to see the binary size increase, too.

**Comment by philnichol** [comment]
Thanks @RedbackThomson ! I'll have a go and get some side-by-side comparisons.

**Comment by philnichol** [comment]
@RedbackThomson not a trivial difference TBF:

As is:
```
 aws-controllers-k8s     s3-v0.0.7-5-g3e6743f-dirty   3278a5d3a608   About a minute ago   63.8MB
```
with Pie flag:
```
aws-controllers-k8s     s3-v0.0.7-5-g3e6743f-dirty   bc58dcce3bff   6 seconds ago   74.5MB
```

What do you reckon? Probably worth evaluating performance also?

**Comment by RedbackThomson** [comment]
That does seem fairly substantial. But to be fair it was only a 64MB binary to begin with. Thoughts @jaypipes @vijtrip2 @A-Hilaly ?

**Comment by vijtrip2** [comment]
I believe if we can improve security posture of controller, which will allow more customers to adopt the controllers and run in their production cluster, we should go for it.

For the above specific case, I believe ~10MB increase in size will not be a bad trade-off. We should do it : )

and Thanks @philnichol for always raising our security standards. We will try to take this knowledge and implement in other projects as well. Appreciate it!

**Comment by jaypipes** [comment]
Reading the associated blog post now... from first glance, seems like 10MB image size is a perfectly acceptable trade-off. Will finalize decision after reading the article fully and we'll chat about this at today's ACK community meeting.

**Comment by jaypipes** [comment]
> Reading the associated blog post now... from first glance, seems like 10MB image size is a perfectly acceptable trade-off. Will finalize decision after reading the article fully and we'll chat about this at today's ACK community meeting.

OK, after fully reading the article, seems like yes, PIE is an easy win and with an acceptable increase in binary size. We could also look into using CGO but then we'd open up the door to attacks with modified dynamically-loaded libs.

**Comment by philnichol** [comment]
yeah, the CGO stuff seemed way less trivial, and potentially could bring in other security issues?

**Comment by philnichol** [comment]
Not needed: 
https://github.com/aws-controllers-k8s/code-generator/pull/273#issuecomment-1021149860
