### ISSUE TITLE
ECR - Repository CR tags not reflecting 

### ISSUE THREAD

**Issue by svmundada** [aws-controllers-k8s/community#1137]
**Describe the bug**
Updating tags on `Repository` CR is not reflecting, at least in the console.
In the debug logs i do see reconcile happen but resource metadata is not getting updated.

**Steps to reproduce**
- Create a Repository without tags.
- Update a Repository by adding tags.

**Expected outcome**
If CR is updated, tags should also be reflected.

**Environment**

* Kubernetes version 1.20
* Using EKS (yes/no), if so version? Yes 1.20
* AWS service targeted (S3, RDS, etc.) ECR

**Comment by A-Hilaly** [comment]
Thanks for reporting this issue @svmundada , indeed ecr is missing the update code path for repositories. Sending a fix soon.

**Comment by A-Hilaly** [comment]
@svmundada we just release a new ecr-controller version fixing this issue: https://github.com/aws-controllers-k8s/ecr-controller/releases/tag/v0.0.16

**Comment by svmundada** [comment]
@A-Hilaly Can we please reopen this? We are using `v0.0.17` and after updating the tags on `Repository` we are seeing random 503 errors. Also tags are not getting updated in ECR on console.

```
  Tags:
    Key:    <>
    Value:  <>
    Key:    <>
    Key:    <>
    Value:  <>
    Key:    <>
    Key:    <>
    Value:  <>
    Key:    <>
    Value:  <>
    Key:    <>
    Value:  <>
    Key:    <>
    Value:  <>
Status:
  Ack Resource Metadata:
    Arn:               <>
    Owner Account ID:  <>
  Conditions:
    Message:               ServerException: An internal server error has occured
    Status:                True
    Type:                  ACK.Recoverable
    Last Transition Time:  2022-02-04T09:53:54Z
    Status:                False
    Type:                  ACK.ResourceSynced
  Created At:              2021-12-03T15:02:47Z
  Repository URI:          <>
Events:                    <none>
```
If you see the tags section it's just key/value pairs are mixed up.
Any help would be much appreciated ?

**Comment by A-Hilaly** [comment]
@svmundada i'm investigating this issue RN

**Comment by A-Hilaly** [comment]
Hey @svmundada i am not able to reproduce the issue with ecr-controller v0.0.17 - can you please provide the manifests of the ECR repositories you're creating and/or the controller logs your observing?

**Comment by vijtrip2** [comment]
>  ServerException: An internal server error has occured

This looks like an error from ECR side and nothing wrong with how controller is trying to reconcile. This should resolve as ECR service recovers from this issue on their side.

@svmundada , please verify again and reopen if the issue does not resolve.

**Comment by svmundada** [comment]
@vijtrip2 Makes sense on the ECR part side. Btw did you try to update tags on the already existing ECR repo? because that's what failed for us ( 2 times ).

**Comment by A-Hilaly** [comment]
>Btw did you try to update tags on the already existing ECR repo?

Yes the ecr e2e tests creates a repository with no tags and then starts adding/updating tags: https://github.com/aws-controllers-k8s/ecr-controller/blob/main/test/e2e/tests/test_repository.py#L218-L244
