### ISSUE TITLE
Access policy for  Fine-grained access control

### ISSUE THREAD

**Issue by faganihajizada** [aws-controllers-k8s/community#1142]
**Is your feature request related to a problem?**
When creating an OpenSearch domain with OpenSearch service-controller Fine-grained access control is enabled but there is no access policy assigned by default.

**Describe the solution you'd like**
Can we make it possible to add an IAM policy to the domain?

**Describe alternatives you've considered**
When you try to enable fine-grained access control from AWS Web Console a policy will be assigned by default:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:{region}:{account-id}:domain/{domain-name}/*"
    }
  ]
}
```
Can we make this policy automatically generated by the OpenSearch service controller?

**Comment by RedbackThomson** [comment]
I see a [`Spec.AccessPolicies`](https://aws-controllers-k8s.github.io/community/reference/opensearchservice/v1alpha1/domain/#spec) field for the `Domain` resource. Is this what you are referring to?

**Comment by faganihajizada** [comment]
Yes, that's the one 👍🏻  Thanks!
