### ISSUE TITLE
crossplane - skip region for iam group resources

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#1150]
**Describe the bug**
for crossplane the region parameter is hard-coded - but for iam group resources we don't need region 
https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/crossplane/apis/crd.go.tpl#L21-L23

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by muvaf** [comment]
@jaypipes Does ACK now allow generation of IAM resources?

@haarchri if we are sure IAM is the only one, we can hard-code the if condition in the template. Addition of a config parameter (add region or not) to main config object is high cost given that it's used by both ACK and Crossplane. In that case, I don't think ACK uses CRD spec for region so it'd be a Crossplane-specific option, which is a first.

**Comment by haarchri** [comment]
@muvaf i have an working ACK generated resource - `ServiceLinkedRole` without Problems but with `region` i can publish the PR in provider-aws if it helps

**Comment by muvaf** [comment]
@haarchri do you think having `if CRD.Group == iam` [here](https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/crossplane/apis/crd.go.tpl#L21-L23) would be future-proof enough?

**Comment by haarchri** [comment]
think we have here something more? https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/crossplane/pkg/controller.go.tpl#L47

**Comment by jaypipes** [comment]
> @jaypipes Does ACK now allow generation of IAM resources?
> 
> @haarchri if we are sure IAM is the only one, we can hard-code the if condition in the template. Addition of a config parameter (add region or not) to main config object is high cost given that it's used by both ACK and Crossplane. In that case, I don't think ACK uses CRD spec for region so it'd be a Crossplane-specific option, which is a first.

Hi @muvaf! Yes, we have an IAM controller for ACK now:

https://github.com/aws-controllers-k8s/iam-controller

Currently only Role and Policy resources are supported, with support for attaching and detaching Polcies (non-inline) to a Role resource via the `Role.Spec.Policies` field.

We're working on supporting other resources like User, Group, etc.

**Comment by muvaf** [comment]
@jaypipes great! do you do anything special for region there?

@haarchri What do you think about adding if statements to cover `iam` for now and later if we ever need it for another group, we can make it behave by looking at something in config. As far as I can tell, there has not been a resource that doesn't require region other than IAM, so we might be fine there.

**Comment by haarchri** [comment]
added PR for iam https://github.com/aws-controllers-k8s/code-generator/pull/285
