### ISSUE TITLE
S3 controller delete message

### ISSUE THREAD

**Issue by svmundada** [aws-controllers-k8s/community#1158]
**Describe the bug**
We tried to update the tags on our bucket and in return, we are seeing the controller continuously reconciling on delete event.

bucket status
```
  - message: "BucketNotEmpty: The bucket you tried to delete is not empty\n\tstatus
```

controller logs
```
2022-02-02T17:17:14.611Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "bucket", "request": "ack-system/<>", "error": "BucketNotEmpty: The bucket you tried to delete is not empty\n\tstatus code: 409, 
```
Any suggestions on how to figure out what caused this? 
Looks like the deletion timestamp got set somehow and which is causing this.

**Steps to reproduce**
Not sure what caused it, but we definitely didn't issue any delete command for the bucket.
Also, we see deletion timestamp set on the bucket resource and finalizer is also present.

**Expected outcome**
This should not happen. 

**Environment**

* Kubernetes version 1.20
* Using EKS (yes/no), if so version? 1.20 yes
* AWS service targeted (S3, RDS, etc.) S3

**Comment by RedbackThomson** [comment]
>  Also, we see deletion timestamp set on the bucket resource and finalizer is also present.

I don't believe any part of the ACK runtime should ever **set** a deletion timestamp. I wonder if some other system inside your cluster issued this delete?

**Comment by svmundada** [comment]
@RedbackThomson Our cluster updating process just does the "apply", so a bit confused about what caused this. 
Any suggestions on where to look? The last applied configuration is just empty ( and every reconciliation generated version is getting updated )

Also, now that deletion timestamp is added to the resource, the controller is going in an endless loop, is there any way to fix this? Or should we delete bucket resource and take the adopted resource path?

**Comment by svmundada** [comment]
@vijtrip2 Thanks for the suggestion. 
Although it didn't work. I removed `deletionTimestamp` and `deletionGracePeriodSeconds` fields and did kubectl replace. After that again when I do kubectl get on the bucket, I see deletion `deletionTimestamp` to be set.
Another weird thing I observed, kubectl replace with `--force` takes kubectl into some kind of loop ( based on `-v 8`) and it never returns.
Any suggestions?

**Comment by vijtrip2** [comment]
> Any suggestions?

Not really :/ . I wonder what is marking the resource as deleted.

**Comment by svmundada** [comment]
I am not sure too, but this is becoming a pain point for us. I'd check again how `kubectl apply --force` works in background and if causes any delete operation.

**Comment by vijtrip2** [comment]
Please reopen if you still need assistance from ACK team. We were unable to reproduce this any of the ACK controllers.

**Comment by IliaGe** [comment]
I have the same issue, a bucket resource hold a property of 'deletionTimestamp'. Something is returning this property even after a deletion (with kubectl edit ...).
I have stopped the controller, and re-edited, still, the deletionTimestamp is getting back to the resource :0
Is there a mutatingWebHook or something like that implemented?

**Comment by RedbackThomson** [comment]
>  Is there a mutatingWebHook or something like that implemented?

No ... but this is strange and is going to be a big problem if it keeps happening. I don't see any reference to any code paths that delete CRs in any of our common code.
