### ISSUE TITLE
Unable to pull ack-s3 charts manifest from ecr

### ISSUE THREAD

**Issue by senior88oqz** [aws-controllers-k8s/community#1169]
**Describe the bug**

I was following the installation [instruction](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/#install-an-ack-service-controller-with-helm-recommended) and unable to pull the chart manifest for s3-controller with version `v0.0.5` and above.

Also, it seems the link to the `installation docs` under the [usage](https://gallery.ecr.aws/aws-controllers-k8s/s3-controller) tab on the ecr is broken :)

**Steps to reproduce**

```
➜ HELM_EXPERIMENTAL_OCI=1 helm pull oci://public.ecr.aws/aws-controllers-k8s/s3-chart --version v0.0.5 -d /tmp/chart
v0.0.5: Pulling from public.ecr.aws/aws-controllers-k8s/s3-chart
Error: manifest does not contain a layer with mediatype application/tar+gzip
```

**Comment by vijtrip2** [comment]
Hi @senior88oqz , I was wondering what is version of helm that are using.

The recommended way to install an ACK service controller for Kubernetes is to use [Helm 3.7+](https://helm.sh/docs/intro/install/).

**Comment by senior88oqz** [comment]
Thanks @vijtrip2 , i was on `v3.6.0`, working fine now after upgrading to `v3.8.0`
