### ISSUE TITLE
ACK Controllers installScope

### ISSUE THREAD

**Issue by oleg-yudovich** [aws-controllers-k8s/community#1170]
**Is your feature request related to a problem?**

Hey guys.
When installing ACK controllers in our cluster, there is `ClusterRole` created for each one of them.
We can see it as the default behavior for example in the s3 controller.

https://github.com/aws-controllers-k8s/s3-controller/blob/2153e6d2cf34cd9d68cf0f27dbc3c3610644a7e3/helm/values.yaml#L62
https://github.com/aws-controllers-k8s/s3-controller/blob/main/helm/templates/cluster-role-binding.yaml#L2

How can we override this value to `namespace`?
I didn't find anything in the [docs](https://aws-controllers-k8s.github.io/community/docs/community/overview/)

We are must have this option as a Corporate security requirement.

**Comment by vijtrip2** [comment]
Hi, you can update the value using --set option of helm install OR you can manually edit your local values.yaml

The configuration is present in values.yaml file https://github.com/aws-controllers-k8s/s3-controller/blob/main/helm/values.yaml#L62

**Comment by oleg-yudovich** [comment]
Thanks you @vijtrip2
