### ISSUE TITLE
User Agent String is not being populated correctly

### ISSUE THREAD

**Issue by brycahta** [aws-controllers-k8s/community#1171]
**Describe the bug**
When querying EC2-controller usage data, the user-agent string returns: 
`aws-controller-k8s/- (GitCommit/; BuildDate/; CRDKind/; CRDVersion/) aws-sdk-go/1.37.10 (go1.17.5; linux; amd64)`

**Steps to reproduce**
* Query `aws-controller-k8s` user-agent string in metrics/dashboard (I am using internal service).

**Expected outcome**
I expect `$SERVICE-controller` to be denoted somewhere and `GitCommit`, `BuildDate`, `CRDKind`, and `CRDVersion` to be populated. Also, (from Jay), the string should read `aws-controllers-k8s` (with an 'S')

**Environment**

* Kubernetes version N/A
* Using EKS (yes/no), if so version?  N/A
* AWS service targeted (S3, RDS, etc.)  EC2, but applies to all

**Comment by RedbackThomson** [comment]
Probably this little guy: https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/cmd/controller/main.go.tpl#L90
