### ISSUE TITLE
ack go-sdk-v1.42.0 ClientToken Field in VPCEndpointObservation 

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#1172]
**Describe the bug**
in crossplane we bumped the go-sdk-v1 to 1.42.0 (https://github.com/crossplane/provider-aws/pull/1122) and code-generator to commit `76bb8df5f54ad3791f93f4aa4d805f61fccb3591` we see now that for VPCEndpointObservation an Field ClientToken is added: https://github.com/crossplane/provider-aws/pull/1122/files#diff-ed0977533addb34c49a5d80220f52ca5975f5e24fb39df5f0bb7e47f685e3e08R72-R74
we think this is a bug - any option that we can skip it ?

for Input we skip it like: https://github.com/crossplane/provider-aws/pull/1122/files#diff-0b940562e012ed7b06ec705413df631709994fe5bf0d9d021fa25b9f33c21fc3R120

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by A-Hilaly** [comment]
@haarchri Apparently this is not a bug. According to [`CreateVPCEndpoint` ](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html)API call documentation, both of the Input and the Output contains `ClientToken`.
One of the solutions would be to add `- CreateVpcEndpointOutput.ClientToken` to the list of ignored `field_path` in your `generator-config.yaml`. However ideally you can directly instruct the code generator to get the Observation fields from `CreateVpcEndpointOuput.VpcEndpoint` by doing something similar to what we have in the ec2-controller
```yaml
operations:
  CreateVpcEndpoint:
    output_wrapper_field_path: VpcEndpoint
```

**Comment by haarchri** [comment]
Thanks for clarification that the CreateOutput will add the ClientToken to Observation - i will test

**Comment by haarchri** [comment]
thanks its working
