### ISSUE TITLE
UpdateRequest payload should ONLY include Spec fields with Delta

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#1174]
In the current implementation of `newUpdateRequestPayload` method inside `sdk_update.go.tpl` file, all the Spec fields from desired resource are included in the UpdateRequest.

For the most part this works well because AWS APIs ignore update of a field to similar value in the backend. But there are some minority of cases where the Update API can return `ValidationError`(or have some other unknown side-effect). Example: RDS's `ModifyDBInstance` API does not allow passing identical value for `DBSubnetGroupName` field.

To be on the safer side, ACK code-generator should only include Spec fields, with Delta between desired and latest state, inside the UpdateRequest payload. This will have two advantages:

a) Reduces the chances of `ValidationError`
b) The UpdateRequest payload for customers will be more useful when customers try to debug using CloudTrail.

**Comment by vijtrip2** [comment]
As per @jaypipes, The flip side for only adding a field in UpdateRequestPayload when there is delta(between desired & latest state), is that whether AWS Update API will remove the fields absent in UpdateRequest from the AWS Resource in some cases.
 
So there should be a configuration option per resource in `generator.yaml` that will control whether to consider delta before adding a field inside UpdateRequest payload.

**Comment by a-hilaly** [comment]
This is already implemented as `OmitUnchangedFields` config https://github.com/aws-controllers-k8s/code-generator/commit/9fbf8c4cbf99b2a944ac0e38872b0cd776cc2962
/close
