### ISSUE TITLE
It is not possible to update opensearch domain configuration by adjusting YAML file

### ISSUE THREAD

**Issue by faganihajizada** [aws-controllers-k8s/community#1181]
**Describe the bug**

How to add new OpenSearch warm instances or update the version of the domain? After deploying an OpenSearch domain with UltraWarm instances enabled I wanted to add one more warm node to the domain (increase it from 3 to 4). I adjusted the YAML file and applied change.
When I describe the resource in Kubernetes I can see that changes applied but in AWS Console I still see only 3 warm nodes instead of 4.

I also tested changing the `engineVersion` from `"Elasticsearch_7.9"` to `"Elasticsearch_7.10"` and it didn't work.

**Steps to reproduce**

Adjust  `engineVersion` and/or `warmCount` section in the YAML file and apply changes.

**Expected outcome**
ACK controller trigger changes for AWS Opensearch resource.

**Environment**

* Kubernetes version: 1.21
* Using EKS (yes/no), if so version?  yes, EKS platform version: eks.4
* AWS service targeted (S3, RDS, etc.): OpenSearch domain

**Comment by A-Hilaly** [comment]
Hello @faganihajizada, currently the opensearch controller doesn't support update operations for `Domain` CRs.

**Comment by faganihajizada** [comment]
Thanks for the info, @A-Hilaly

**Comment by bambaryla** [comment]
hey AWS, please fix this upgrade possibility or we will stay on Elasticsearch forever ;)

**Comment by carpenterbees** [comment]
Dear ACK development team, I am using this controller and found very useful, would be nice to have it fully featured.

**Comment by jaypipes** [comment]
@faganihajizada @carpenterbees @bambaryla I'm assigning this to myself. Need to get this controller in shape and I will work on implementing the update code paths this week.

First step is [bringing the controller into a modern ACK runtime and dependencies](https://github.com/aws-controllers-k8s/opensearchservice-controller/pull/49)

**Comment by Moulick** [comment]
@jaypipes would be lovely to know how this is progressing?

**Comment by razor-1** [comment]
Hi @jaypipes

I don't want to step on any toes since this issue is assigned to you, but also know that it's easy to get busy with other things. I started exploring how to add update domain functionality based on how it's been done for RDS in https://github.com/aws-controllers-k8s/rds-controller/blob/main/pkg/resource/db_cluster/custom_update.go.

Before going further I was wondering if this is the right direction to be going in? If so and it's OK with you, I could probably get a PR opened fairly soon. If not, any pointers on the best way to handle it would be appreciated.

Thanks!

**Comment by razor-1** [comment]
I've opened https://github.com/aws-controllers-k8s/opensearchservice-controller/pull/67 for this, and have tested both update and upgrade using it successfully.

**Comment by a-hilaly** [comment]
Thank you so much for your contribution @razor-1 !
This is now support in `opensearchservice-controller` v0.0.25
/close
