### ISSUE TITLE
Document the IAM setup requirements for individual ACK service controllers

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#120]
We need to create documentation that outlines the prerequisite IAM role/permission setup that needs to occur for ACK service controllers, including a quick scripted demo of setting up IRSA for a Kubernetes cluster and creating (via the AWS console or the `aws` CLI tool) the required IAM role and permission set for the IAM role associated with the Service Account that is tied to the Pod running the service controller.

**Comment by RedbackThomson** [comment]
I believe this was included as part of the CARM documentation? Does this suffice? https://aws-controllers-k8s.github.io/community/user-docs/authorization/#configuring-aws-iam

**Comment by so0k** [comment]
those docs are outdated, most stuff gets 404 since https://github.com/aws/aws-controllers-k8s was redirected to this repo?
![image](https://user-images.githubusercontent.com/1762599/129648882-8e944b43-3124-4c78-a3fb-3cd058b49f40.png)

**Comment by jaypipes** [comment]
> those docs are outdated, most stuff gets 404 since https://github.com/aws/aws-controllers-k8s was redirected to this repo?

Thanks for the heads up @so0k! I'll correct those broken links ASAP.

**Comment by jaypipes** [comment]
This is done now.
