### ISSUE TITLE
Implement `update` functionality for `Subnet` resource

### ISSUE THREAD

**Issue by brycahta** [aws-controllers-k8s/community#1203]
**Is your feature request related to a problem?**
[ec2-controller](https://github.com/aws-controllers-k8s/ec2-controller) supports Create/Delete functionality for `Subnet` resource, but **not** [Update](https://github.com/aws-controllers-k8s/ec2-controller/blob/af432344f155be0761ed68724ff04c04b6e89bcf/pkg/resource/subnet/sdk.go#L447).

**Describe the solution you'd like**
I should be able to modify/update an ACK-managed `Subnet` resource using its controller

**Describe alternatives you've considered**
Updating resource myself using `aws-sdk`, cli, or console

**Comment by brycahta** [comment]
![image](https://user-images.githubusercontent.com/61433408/188701696-fefe96bd-a2a4-42d8-b05b-d6c930a72f97.png)

Will prioritize update functionality related to _Edit subnet settings_ in the _Console_. Note, for fields backed by [modify-subnet-attribute](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-subnet-attribute.html) **You can only modify one attribute at a time.**

**Comment by brycahta** [comment]
Update: **We are blocked on aligning Update functionality with Console due to older version of aws-sdk-go**

The AWS Console 'Edit subnet settings' contains functionality (resource-based naming, DNS settings) that is not yet supported by the version of `aws-sdk-go` being used in _code-generator_, `v1.42.0`. 

`ModifySubnetAttribute` input shape in `aws-sdk-go v1.42.0`:

```
    "ModifySubnetAttributeRequest":{
      "type":"structure",
      "required":["SubnetId"],
      "members":{
        "AssignIpv6AddressOnCreation":{"shape":"AttributeBooleanValue"},
        "MapPublicIpOnLaunch":{"shape":"AttributeBooleanValue"},
        "SubnetId":{
          "shape":"SubnetId",
          "locationName":"subnetId"
        },
        "MapCustomerOwnedIpOnLaunch":{"shape":"AttributeBooleanValue"},
        "CustomerOwnedIpv4Pool":{"shape":"CoipPoolId"}
      }
    }
```

*latest* `ModifySubnetAttribute` input shape:

```
    "ModifySubnetAttributeRequest":{
      "type":"structure",
      "required":["SubnetId"],
      "members":{
        "AssignIpv6AddressOnCreation":{"shape":"AttributeBooleanValue"},
        "MapPublicIpOnLaunch":{"shape":"AttributeBooleanValue"},
        "SubnetId":{
          "shape":"SubnetId",
          "locationName":"subnetId"
        },
        "MapCustomerOwnedIpOnLaunch":{"shape":"AttributeBooleanValue"},
        "CustomerOwnedIpv4Pool":{"shape":"CoipPoolId"},
        "EnableDns64":{"shape":"AttributeBooleanValue"},
        "PrivateDnsHostnameTypeOnLaunch":{"shape":"HostnameType"},
        "EnableResourceNameDnsARecordOnLaunch":{"shape":"AttributeBooleanValue"},
        "EnableResourceNameDnsAAAARecordOnLaunch":{"shape":"AttributeBooleanValue"},
        "EnableLniAtDeviceIndex":{"shape":"Integer"},
        "DisableLniAtDeviceIndex":{"shape":"AttributeBooleanValue"}
      }
    },
```

I can see some of these fields were added in [`v1.42.11`](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v14211-2021-11-23):

> service/ec2: Updates service API and documentation
  This release adds a new parameter ipv6Native to the allow creation of IPv6-only subnets using the 
  CreateSubnet operation, and the operation ModifySubnetAttribute includes new parameters to modify 
  subnet attributes to use resource-based naming and enable DNS resolutions for Private DNS name.

as well as in [`v1.42.16`](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v14216-2021-11-30):

> service/ec2: Updates service API and documentation
 This release adds support for Is4gen and Im4gn instances. This release also adds a new subnet 
 attribute, enableLniAtDeviceIndex, to support local network interfaces, which are logical networking 
 components that connect an EC2 instance to your on-premises network.


For now, I'll proceed with implementing `Update` for the current fields in `ModifySubnetAttributeRequest v1.42.0`. Feel free to chime in with feedback and/or plans to update `aws-sdk-go` in the future

**Comment by jaypipes** [comment]
Closing as completed.
