### ISSUE TITLE
`ClientToken` included in ec2-controller types

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1222]
**Describe the bug**
The `ClientToken` field in an AWS request should not be exposed to users as it is only related to the SDK methods. I can see this in `VPCEndpoint.Spec`, as well as a number of structs in `types.go`. These should be included in the `ignore.field_paths` of the generator config.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.) EC2

**Comment by A-Hilaly** [comment]
I still see that `VPCEndpoint` has a `ClientToken` field https://github.com/aws-controllers-k8s/ec2-controller/blob/main/apis/v1alpha1/vpc_endpoint.go#L29

**Comment by brycahta** [comment]
`ClientToken` field removed in [v0.0.19](https://github.com/aws-controllers-k8s/ec2-controller/releases/tag/v0.0.19)
