### ISSUE TITLE
Support custom documentation for fields

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1223]
**Is your feature request related to a problem?**
A lot of the auto-generated field documentation is insufficient. Especially when using custom fields, the field documentation is related to the underlying type of the field rather than its purpose to the user. This is also evident on all of the `ACKResourceMetadata` fields, which even include example code blocks in their docs. 

**Describe the solution you'd like**
We should be able to describe fields using a custom block of text, or maybe also by referencing a path to a field that has the correct description (useful for when using wrappers in custom fields). This custom block of text might live inside the `generator.yaml`, but that could potentially clutter everything, so it might also be better for the generator config to reference another YAML file.

**Comment by jljaco** [comment]
Next steps on this:  change the implementation such that custom documentation goes into a separate file.  Leaving this open until that change is made.
