### ISSUE TITLE
Environment variables missing in deployment Kustomization

### ISSUE THREAD

**Issue by joshuamoreno1** [aws-controllers-k8s/community#1224]
**Describe the bug**
When I deployed manually the controller using the kubernetes manifiest, when I created lambdas the controller did not react to those new resources.

**Steps to reproduce**
Deploy the controller using the config folder

**Expected outcome**
I expect the lambdas were created.

**Environment**
Development

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.) Lambda
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

You could resolve this if you add these lines to controller/deployment.yaml in spec.env as anothers controllers have:

```
 - name: ACK_RESOURCE_TAGS
          value: services.k8s.aws/managed=true,services.k8s.aws/created=%UTCNOW%,services.k8s.aws/namespace=%KUBERNETES_NAMESPACE%
```

**Comment by RedbackThomson** [comment]
The `ACK_RESOURCE_TAGS` do not have anything to do with a controller detecting the resource. I would be more interested in seeing the manifests you applied to the cluster and the methods you used to deploy the controller using the Kustomization manifests.

**Comment by RedbackThomson** [comment]
Ah yes, I see now. Our [Helm charts](https://github.com/aws-controllers-k8s/lambda-controller/blob/main/helm/templates/deployment.yaml#L66-L82) include these environment variables with default values, but we have not extended these same options into the Kustomization files. 

Great catch!

**Comment by joshuamoreno1** [comment]
Thanks a lot!!
