### ISSUE TITLE
apigatewayv2 v0.0.17 fails to run

### ISSUE THREAD

**Issue by shopizer-ecommerce** [aws-controllers-k8s/community#1236]
**Describe the bug**
apigatewayv2 v0.0.17 pods fail to run after installation was complete. 

**Steps to reproduce**

Install from Helm as recommended here https://aws-controllers-k8s.github.io/community/docs/user-docs/install/
Installed serviceaccount and IAM policies as recommended here https://aws-controllers-k8s.github.io/community/docs/user-docs/irsa/

**Expected outcome**
A concise description of what you expected to happen.

I expect the dployment, replicaset and pods to be running without errors

**Environment**

non production, we want to test the ability to create api gateway from our existing charts

* Kubernetes version
* Using EKS (yes/no), if so version

Yes version 1.19

* AWS service targeted (S3, RDS, etc.)

apigatewayv2

kubectl logs 

1.6480432435648882e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "0.0.0.0:8080"}
1.6480432435652447e+09  INFO    setup   initializing service controller {"aws.service": "apigatewayv2"}
1.6480432444232705e+09  INFO    setup   starting manager        {"aws.service": "apigatewayv2"}
1.6480432444246342e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.6480432444248543e+09  INFO    controller.stage        Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Stage", "source": "kind source: *v1alpha1.Stage"}
1.648043244424888e+09   INFO    controller.stage        Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Stage"}1.6480432444251213e+09  INFO    controller.api  Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "API", "source": "kind source: *v1alpha1.API"}
1.648043244425171e+09   INFO    controller.api  Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "API"}
1.6480432444253018e+09  INFO    controller.vpclink      Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "VPCLink", "source": "kind source: *v1alpha1.VPCLink"}
1.6480432444253483e+09  INFO    controller.vpclink      Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "VPCLink"}
1.6480432444254467e+09  INFO    controller.deployment   Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Deployment", "source": "kind source: *v1alpha1.Deployment"}
1.6480432444254918e+09  INFO    controller.deployment   Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Deployment"}
1.648043244425941e+09   INFO    controller.authorizer   Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Authorizer", "source": "kind source: *v1alpha1.Authorizer"}
1.6480432444259875e+09  INFO    controller.authorizer   Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Authorizer"}
1.6480432444260883e+09  INFO    controller.route        Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Route", "source": "kind source: *v1alpha1.Route"}
1.648043244426135e+09   INFO    controller.route        Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Route"}1.648043244426284e+09   INFO    controller.integration  Starting EventSource    {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Integration", "source": "kind source: *v1alpha1.Integration"}
1.648043244426323e+09   INFO    controller.integration  Starting Controller     {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Integration"}
1.64804324442659e+09    INFO    controller.adoptedresource      Starting EventSource    {"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "source": "kind source: *v1alpha1.AdoptedResource"}
1.6480432444266257e+09  INFO    controller.adoptedresource      Starting Controller     {"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource"}
1.6480432445266647e+09  INFO    controller.stage        Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Stage", "worker count": 1}
1.6480432445274115e+09  INFO    controller.adoptedresource      Starting workers        {"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "worker count": 1}
1.6480432445906773e+09  INFO    controller.api  Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "API", "worker count": 1}
1.648043244590723e+09   INFO    controller.deployment   Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Deployment", "worker count": 1}
1.6480432445906913e+09  INFO    controller.vpclink      Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "VPCLink", "worker count": 1}
1.6480432445908558e+09  INFO    controller.authorizer   Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Authorizer", "worker count": 1}
1.648043244591213e+09   INFO    controller.integration  Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Integration", "worker count": 1}
1.6480432445912426e+09  INFO    controller.route        Starting workers        {"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "Route", "worker count": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x168cb7f]

goroutine 560 [running]:
github.com/aws-controllers-k8s/apigatewayv2-controller/pkg/resource/vpc_link.(*resourceManager).IsSynced(0xc0004f6720, {0x1a77601, 0xb}, {0x1e09cf8, 0xc00000e440})
        /github.com/aws-controllers-k8s/apigatewayv2-controller/pkg/resource/vpc_link/manager.go:260 +0x5f
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).ensureConditions(0xc00000e440, {0x1dd96d8, 0xc0004f6750}, {0x1e06570, 0xc00040f300}, {0x1e09cf8, 0xc00000e440}, {0x1daaec0, 0xc000adb500})
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.17.2/pkg/runtime/reconciler.go:299 +0x270
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Sync.func1()
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.17.2/pkg/runtime/reconciler.go:216 +0x46
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Sync(0xc000304a20, {0x1dd96d8, 0xc0004f6750}, {0x1e06570, 0xc00040f300}, {0x1e09cf8, 0xc00000e2e8})

I have installed v0.0.14 and this version is working fine so far

 kubectl get all -n ack-system
NAME                                                                 READY   STATUS    RESTARTS   AGE
pod/ack-apigatewayv2-controller-apigatewayv2-chart-d6f88d4df-tjfq9   1/1     Running   0          74m

NAME                                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ack-apigatewayv2-controller-apigatewayv2-chart   1/1     1            1           74m

NAME                                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/ack-apigatewayv2-controller-apigatewayv2-chart-d6f88d4df   1         1         1       74m

**Comment by vijtrip2** [comment]
Hi @shopizer-ecommerce , Thanks for reporting the bug. This got fixed in release v0.0.18
Please upgrade to the apigateway-controller release v0.0.18 . Cheers!
