### ISSUE TITLE
Delta code generation for field of type `SecretKeyReference`

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1239]
**Describe the bug**
`ack-generate` doesn't generate delta code that correctly compares two arrays of `SecretKeyReference`.

**Steps to reproduce**

Generate memorydb-controller with `ack-generate` v0.18.0 and lookup `pkg/resources/usesr/delta.go#L54`
The generated code looks like:
```go
if !ackcompare.SliceStringPEqual(a.ko.Spec.AuthenticationMode.Passwords, b.ko.Spec.AuthenticationMode.Passwords) {
	delta.Add("Spec.AuthenticationMode.Passwords", a.ko.Spec.AuthenticationMode.Passwords, b.ko.Spec.AuthenticationMode.Passwords)
}
```

**Expected outcome**
Should generate code that correctly compares two arrays of `SecretKeyReference`

**Environment**

* ack-generate v0.18.0

**Comment by vijtrip2** [comment]
The key comparison for the SecretKeyReference will be implemented. However comparison of actual password will not be implemented in the solution because the observed state of resource does not return the password value.
