### ISSUE TITLE
RDS `EnablePerformanceInsights` delta failing

### ISSUE THREAD

**Issue by dspaxton** [aws-controllers-k8s/community#1251]
**Describe the bug**
Creation of an RDS instance using the controller results in the instance not stabilising to the point of being able to use it. 
**Steps to reproduce**

Following steps outlined in https://aws.amazon.com/blogs/database/deploy-amazon-rds-databases-for-applications-in-kubernetes/ when I come to create the instance, it constantly seems to be either  resetting master credentials, configuring enhanced monitoring or rebooting. 

**Expected outcome**

RDS Instance is launched and can be used. 

**Environment**

* Kubernetes 1.21
* Using EKS (yes/no), eks.5
* AWS service targeted RDS

**Comment by dspaxton** [comment]
Apologies, after re-running a 3rd time it appears to be working now.

**Comment by RedbackThomson** [comment]
> Apologies, after re-running a 3rd time it appears to be working now.

Oh. Was there anything we should update in the docs that would make it more clear?

**Comment by dspaxton** [comment]
Hmm I just had a thought. I did make a change to the type of deployment. I'll keep open and test again in the morning.

**Comment by brucegucode** [comment]
I think we may need to reopen this issue. made a comment here 
https://github.com/aws-controllers-k8s/rds-controller/pull/77#issuecomment-1147754387
