### ISSUE TITLE
Ability to use reference KMS key with RDS via Name rather than ARN

### ISSUE THREAD

**Issue by robertgates55** [aws-controllers-k8s/community#1258]
In RDS `crd`s, `kmsKeyId` expects an ARN (or alias).

I can create a KMS Key using the kmscontroller, but the ARN is obviously not available until the AWS resource is created.

Is there any way to use the `kmsKey*Name*` or similar to the RDS resource, just as we can with `dbClusterParameterGroupName` or `dbSubnetGroupName`?

**Comment by vijtrip2** [comment]
ACK controllers now support [referencing resources across ACK controllers](https://github.com/aws-controllers-k8s/community/blob/main/docs/design/proposals/resource-reference/cross-api-group.md). So you would be able to reference a KMSKey by the kubernetes resource name inside RDS crd.

I will add this support inside rds controller and publish a new version of controller, that will have field for referencing KMSKey resource.

**Comment by robertgates55** [comment]
That'd be awesome. Happy to test & post an example here for posterity once you've released etc!

**Comment by vijtrip2** [comment]
@robertgates55 , please test the new kmsKeyRef field in the new v0.0.24 release for rds-controller.

**Comment by robertgates55** [comment]
When I upgrade the helm chart, do the latest CRDs get installed? I can see the pod has rolled to the new version, but the crds look the same....

**Comment by vijtrip2** [comment]
> When I upgrade the helm chart, do the latest CRDs get installed?

I am not sure if the helm install handles upgrading the crds. I will try to find the answer. 
But to unblock yourself, you can install the crds again. CRDs are present in [github.com/rds-controller/helm/crds/](https://github.com/aws-controllers-k8s/rds-controller/tree/main/helm/crds)

**Comment by robertgates55** [comment]
Cool. Have manually patched the CRDs to latest and tested - All working as expected!

```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: some-dbcluster
spec:
  ...
  kmsKeyRef:
    from:
      name: some-kms-key-in-same-namespace
  ...
```
👍
