### ISSUE TITLE
Build controller fails with error: canot clone repository: context deadline exceeded

### ISSUE THREAD

**Issue by dalbhanj** [aws-controllers-k8s/community#1274]
**Describe the bug**
Build controller fails with error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1

**Steps to reproduce**
Follow current [documentation](https://aws-controllers-k8s.github.io/community/docs/contributor-docs/building-controller/) to build existing controllers. I tried S3 and RDS and both report same issue

**Expected outcome**
Expect controller to build successfully

**Environment**
Local Mac environment

* Kubernetes version: 
* Using EKS (yes/no), if so version? Yes but I'm not using EKS yet since this is local environment
* AWS service targeted (S3, RDS, etc.): tried with both S3 & RDS and both report errors

```
$ export SERVICE=s3
$ make build-controller SERVICE=$SERVICE
building ack-generate ... ok.
==== building s3-controller ====
Copying common custom resource definitions into s3
Building Kubernetes API objects for s3
Error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1

$ export SERVICE=RDS
$ make build-controller SERVICE=$SERVICE
building ack-generate ... ok.
==== building rds-controller ====
Copying common custom resource definitions into rds
Building Kubernetes API objects for rds
Error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1
```

**Comment by A-Hilaly** [comment]
Hey @dalbhanj, `ack-generate` is currently set to timeout after [180 seconds](https://github.com/aws-controllers-k8s/code-generator/blob/main/cmd/ack-generate/command/common.go#L40) when trying to clone `aws/aws-sdk-go` repository.

To solve this issue you will have to either increase this value or manually run a `git clone https://github.com/aws/aws-sdk-go` in the ack cache directory which should be by default `$HOME/.cache/aws-controllers-k8s/src/aws-sdk-go` :)

**Comment by dalbhanj** [comment]
Closing this issue as I was able to surpass after fixing my laptop's resource issue. Laptop was running out of resources and had unreliable internet connection. Rebooting fixed the problem : )
