### ISSUE TITLE
Outdated end-to-end test guidance

### ISSUE THREAD

**Issue by dalbhanj** [aws-controllers-k8s/community#1278]
**What is the URL of the document?** https://aws-controllers-k8s.github.io/community/docs/contributor-docs/testing/

 https://aws-controllers-k8s.github.io/community/docs/contributor-docs/testing/

**Which section(s) is the issue in?** https://aws-controllers-k8s.github.io/community/docs/contributor-docs/testing/#run-end-to-end-test

 

**What needs fixing?** Is there another way to run end-to-end tests? 

 Looks like makefile doesn't have 'kind-test' included.
```
$ make kind-test SERVICE=$SERVICE
make: *** No rule to make target `kind-test'.  Stop.
```

**Additional context**

**Comment by RedbackThomson** [comment]
`make kind-test` is still a valid target in our testing: https://github.com/aws-controllers-k8s/test-infra/blob/main/Makefile#L18

When you are trying to run this, does the documentation make it clear that you should be within the `test-infra` repository?
