### ISSUE TITLE
CloudTrail service controller

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1284]
## New ACK Service Controller

Support for AWS CloudTrail

### List of API resources

List the API resources in order of importance to you:

1) [Trail](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_CreateTrail.html)
2) [EventDataStore](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_CreateEventDataStore.html)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
