### ISSUE TITLE
Examples for every Service Controllers

### ISSUE THREAD

**Issue by eminalemdar** [aws-controllers-k8s/community#1293]
**What is the URL of the document?**
https://aws-controllers-k8s.github.io/community/docs/community/services/

**Which section(s) is the issue in?**

Service details

**What needs fixing?**
Documentation missing examples for every Service Controller in the list. Examples with default options (with required and optional parts defined) would be perfect. Being able to use those examples for every controller as reference points would make it extremely easy for everyone to use ACK.

**Additional context**
I would love to help with this issue myself too with contribution and reviews for those documentations, if that's possible.

**Comment by vijtrip2** [comment]
Agree. More examples will be very helpful.
Ideally, ACK team wants to place these example manifests inside https://github.com/aws-controllers-k8s/examples

**Comment by RedbackThomson** [comment]
> Examples with default options (with required and optional parts defined) would be perfect

Our [API Reference](https://aws-controllers-k8s.github.io/community/reference/) outlines which fields are optional and required in the spec. But I agree that we should provide some basic examples, so that people can take them and adapt them to their needs - rather than starting from scratch.

As @vijtrip2 said, we want to use the example manifests repository. We haven't nailed down what format that repository will be - whether it's a series of raw YAML files, Kustomization directories, or Helm charts. The first step is to just start putting things in there, though, in whatever form they exist. We can worry about how exactly they're represented once we have things to organise.

**Comment by eminalemdar** [comment]
> Our [API Reference](https://aws-controllers-k8s.github.io/community/reference/) outlines which fields are optional and required in the spec.

Thanks for sharing the API Reference. 

> As @vijtrip2 said, we want to use the example manifests repository. We haven't nailed down what format that repository will be - whether it's a series of raw YAML files, Kustomization directories, or Helm charts. The first step is to just start putting things in there, though, in whatever form they exist. We can worry about how exactly they're represented once we have things to organise.

I think raw YAML files and Helm would be more ideal. Also, I believe having a guideline in the folders for each controller makes things easier for people.

**Comment by jaypipes** [comment]
@eminalemdar Agreed, more user-friendly examples in a single repository also exposed in our public documentation site would be ideal. You can find examples for the different controllers in the `/test/e2e/resources` directory of the individual ACK controller source repositories, just FYI...

**Comment by eminalemdar** [comment]
> You can find examples for the different controllers in the `/test/e2e/resources` directory of the individual ACK controller source repositories, just FYI...

Thank you @jaypipes I saw these examples.

**Comment by A-Hilaly** [comment]
It would be nice if we could also publish ACK examples that provide a demonstration of common service implementation and infrastructure patterns, similar to what [cdk-examples](https://github.com/aws-samples/aws-cdk-examples/tree/master/python) have

**Comment by RedbackThomson** [comment]
Wow @eminalemdar . What a great start with the examples! I think this is a great start for people who want to try out ACK and wouldn't know where to start. I also really like your (well written) bash install scripts. 

I understand where you are coming from with the Terraform example, too. The AWS integrations team has just released the [AWS EKS Blueprints for Terraform](https://github.com/aws-ia/terraform-aws-eks-blueprints) examples, which we might want to point to - to save ourself the headache of maintaining them ourselves.

**Comment by eminalemdar** [comment]
> I understand where you are coming from with the Terraform example, too. The AWS integrations team has just released the [AWS EKS Blueprints for Terraform](https://github.com/aws-ia/terraform-aws-eks-blueprints) examples, which we might want to point to - to save ourself the headache of maintaining them ourselves.

That's a great idea @RedbackThomson! Maybe I will update the Terraform codes in the repo with the EKS Blueprints.

**Comment by RedbackThomson** [comment]
Just saw your cool medium article, @eminalemdar . I still want to move forward with pushing some of this stuff into the `examples` repository. I have a lot more examples that I can add but I like your rough structure

**Comment by eminalemdar** [comment]
> Just saw your cool medium article, @eminalemdar . I still want to move forward with pushing some of this stuff into the `examples` repository. I have a lot more examples that I can add but I like your rough structure

Thanks a lot @RedbackThomson ! Sharing is the best thing we can do for the greater community. I believe we can work on this together if you need any help from me.

**Comment by RedbackThomson** [comment]
@eminalemdar Please check out https://github.com/aws-controllers-k8s/examples/pull/1 . I didn't include the TF scripts, because they haven't been migrated to use AWS EKS blueprints. We should probably split `scripts` up into `terraform`, `cdk`, etc. too?

**Comment by eminalemdar** [comment]
Brilliant! Thanks @RedbackThomson ! I will migrate the `terraform` scripts to AWS EKS blueprints as soon as I can. I will let you know when I complete that.

> We should probably split `scripts` up into `terraform`, `cdk`, etc. too?

Having multiple options for EKS cluster deployment would be perfect for everybody if it is maintainable of course. But I think starting with Terraform is more convenient.

**Comment by eminalemdar** [comment]
Hey @RedbackThomson ! I've migrated the Terraform scripts to Amazon EKS Blueprints for Terraform. you can check it out from [here](https://github.com/eminalemdar/aws-controllers-for-kubernetes/tree/master/terraform-files)

**Comment by eminalemdar** [comment]
Hello @RedbackThomson ! I've added some more examples to the original repository. You can check out the PR and the examples from [here](https://github.com/eminalemdar/aws-controllers-for-kubernetes/pull/24)

**Comment by RedbackThomson** [comment]
@eminalemdar Would you be open to rebasing your repository from our `examples` repository? That way, we can easily cut PRs if you want to add more examples. Otherwise someone will have to copy between the different repository layouts each time, which is going to get annoying fairly quickly.

**Comment by eminalemdar** [comment]
@RedbackThomson I can add this repository as a remote to my repository and push changes/new examples or I can create PRs to this repository directly too with forking this repository.

**Comment by jaypipes** [comment]
@eminalemdar I think we're good to close this issue out, yes? The examples repo contains examples for all the ACK controllers I believe?

**Comment by eminalemdar** [comment]
> @eminalemdar I think we're good to close this issue out, yes? The examples repo contains examples for all the ACK controllers I believe?

Hello @jaypipes! I think we can close this issue. I can create new ones if needed in the examples repo. They are not quite complete but I will try to add more by creating PRs and relevant issues from there. Thank you!

**Comment by jaypipes** [comment]
Sounds good @eminalemdar thank you! :)
