### ISSUE TITLE
Code redeclarations happen if resource and shape names overlap

### ISSUE THREAD

**Issue by Benedikt1992** [aws-controllers-k8s/community#1294]
**Is your feature request related to a problem?**
When generating crossplane controller code for a service it uses the scheme `Generate` + `shape name` to generate methods for preparing inputs and processing outputs. If some shapes have the same name as the resource itself it generates methods with overlapping names. (e.g. for  `cognitoidentity` we have the resource `IdentityPool` and the shape `IdentityPool` used as input for update calls.

**Describe the solution you'd like**
It would be useful to have the option to change the way how the method names are generated (e.g. configure a prefix or suffix)

**Describe alternatives you've considered**
I have tried several configs that didn't habe any effect (`resources.IdentityPool.update_operation.custom_method_name` and `operations.UpdateIdentityPool.custom_implementation`). Current workaround is to disable the code generator and change the code manually

**Comment by Benedikt1992** [comment]
@muvaf @haarchri Do you have any ideas how to solve this issue?

**Comment by jaypipes** [comment]
Hi @Benedikt1992! The way we handle this in ACK's code-generator is to append the suffix `_SDK` to shapes that overlap with publicly-defined names in CRDs.

When I get back home from Spain (currently sitting in airport in Valencia...) I will generate the Cognito controller and advise you what you need to do in the generator.yaml file to get around your issue. Thanks for your patience!

**Comment by Benedikt1992** [comment]
No, we generated the code, disabled the generator and made manual changes to the code
