### ISSUE TITLE
Attempting to install the SQS controller, complains about missing docker image

### ISSUE THREAD

**Issue by igorkaplan55** [aws-controllers-k8s/community#1306]
I am using the helm chart to install the SQS controller. I get the deployment with the following image repo url:
public.ecr.aws/aws-controllers-k8s/sqs-controller:v0.0.0-non-release-version 

...
image: public.ecr.aws/aws-controllers-k8s/sqs-controller:v0.0.0-non-release-version
        imagePullPolicy: IfNotPresent
        name: controller 
        ...
        
I Get an error about missing image. Looks like the problem is not with an incorrect image tag, looks like sqs-controller is missing from the docker repo.

When I test this repo by doing:
$ docker pull public.ecr.aws/aws-controllers-k8s/sqs-controller:v0.0.0-non-release-version

Error response from daemon: repository public.ecr.aws/aws-controllers-k8s/sqs-controller not found: name unknown: The 
repository with name 'sqs-controller' does not exist in the registry with id 'aws-controllers-k8s' 

  At the same time, if I test the RDS controller docker image:
  docker pull public.ecr.aws/aws-controllers-k8s/rds-controller:v0.0.24

I get an image with no problems

I wonder if I am doing anything incorrectly, or there is a known issue about missing SQS image?

**Comment by igorkaplan55** [comment]
Thanks Vijay.

 

I believe, I followed all instructions and configured everything correctly. However getting the following error when attempting to build:

 

$ pwd

/home/igorkaplan/git/sqs-controller/code-generator 

 

$ echo $SERVICE

sqs

echo $SERVICE_CONTROLLER_SOURCE_PATH

/home/igorkaplan/git/sqs-controller 

 

$ make build-controller-image sqs

 

building 'sqs' controller docker image with tag: aws-controllers-k8s:sqs-8b2d5b1

git commit: 8b2d5b1c257da21dcebeeb659fabbec88e0fc429

#1 [internal] load .dockerignore

#1 transferring context: 2B done

#1 DONE 0.0s

 

#2 [internal] load build definition from Dockerfile

#2 transferring dockerfile: 38B 0.0s done

#2 DONE 0.0s

 

#4 [internal] load metadata for public.ecr.aws/bitnami/golang:1.17

#4 DONE 0.3s

 

#3 [internal] load metadata for public.ecr.aws/eks-distro-build-tooling/eks...

#3 DONE 0.3s

 

#6 [builder 1/11] FROM ***@***.***:f5e976cce2...

#6 DONE 0.0s

 

#8 [internal] load build context

#8 DONE 0.0s

 

#5 [stage-1 1/3] FROM public.ecr.aws/eks-distro-build-tooling/eks-distro-mi...

#5 resolve ***@***.***:defed268f03173500174d285a8bbb5dd98d31b5f8f894736e936740c2953baff done

#5 ...

 

#8 [internal] load build context

#8 transferring context: 2B done

#8 DONE 0.0s

 

#7 [builder 2/11] WORKDIR /github.com/aws-controllers-k8s/sqs-controller

#7 CACHED

 

#9 [builder 3/11] COPY sqs-controller/LICENSE /github.com/aws-controllers-k...

#9 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount284083836/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount284083836/sqs-controller: no such file or directory

 

#10 [builder 4/11] COPY sqs-controller/ATTRIBUTION.md /github.com/aws-contro...

#10 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount020668331/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount020668331/sqs-controller: no such file or directory

 

#11 [builder 5/11] COPY sqs-controller/go.mod /github.com/aws-controllers-k8...

#11 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount653554958/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount653554958/sqs-controller: no such file or directory

 

#13 [builder 7/11] RUN go mod download

#13 CACHED

 

#16 [builder 10/11] COPY sqs-controller/pkg /github.com/aws-controllers-k8s/...

#16 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount198867221/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount198867221/sqs-controller: no such file or directory

 

#15 [builder 9/11] COPY sqs-controller/cmd /github.com/aws-controllers-k8s/s...

#15 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount050469232/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount050469232/sqs-controller: no such file or directory

 

#14 [builder 8/11] COPY sqs-controller/apis /github.com/aws-controllers-k8s/...

#14 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount255491087/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount255491087/sqs-controller: no such file or directory

 

#12 [builder 6/11] COPY sqs-controller/go.sum /github.com/aws-controllers-k8...

#12 ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount095504153/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount095504153/sqs-controller: no such file or directory

 

#6 [builder 1/11] FROM ***@***.***:f5e976cce2...

#6 resolve ***@***.***:f5e976cce25b88a9308d64589f3d18680f9190d043e6109903c1dd272165d26c done

#6 CANCELED

 

#5 [stage-1 1/3] FROM public.ecr.aws/eks-distro-build-tooling/eks-distro-mi...

#5 sha256:defed268f03173500174d285a8bbb5dd98d31b5f8f894736e936740c2953baff 703B / 703B done

#5 sha256:524e12ba594336d3f759726a1235400d966f5f781e78f0a378b9d8abf68b6744 505B / 505B done

#5 sha256:6f9a39e74d14442d5964d51864af0fa06485db9e39a08f408db7d04c8120e820 892B / 892B done

#5 CANCELED

------

> [builder 3/11] COPY sqs-controller/LICENSE /github.com/aws-controllers-k8s/sqs-controller/LICENSE:

------

------

> [builder 4/11] COPY sqs-controller/ATTRIBUTION.md /github.com/aws-controllers-k8s/sqs-controller/ATTRIBUTION.md:

------

------

> [builder 5/11] COPY sqs-controller/go.mod /github.com/aws-controllers-k8s/sqs-controller/go.mod:

------

------

> [builder 6/11] COPY sqs-controller/go.sum /github.com/aws-controllers-k8s/sqs-controller/go.sum:

------

------

> [builder 8/11] COPY sqs-controller/apis /github.com/aws-controllers-k8s/sqs-controller/apis:

------

------

> [builder 9/11] COPY sqs-controller/cmd /github.com/aws-controllers-k8s/sqs-controller/cmd:

------

------

> [builder 10/11] COPY sqs-controller/pkg /github.com/aws-controllers-k8s/sqs-controller/pkg:

------

failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount198867221/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount198867221/sqs-controller: no such file or directory

make: *** [Makefile:49: build-controller-image] Error 1

**Comment by vijtrip2** [comment]
> ERROR: failed to walk /var/lib/docker/tmp/buildkit-mount284083836/sqs-controller: lstat /var/lib/docker/tmp/buildkit-mount284083836/sqs-controller: no such file or directory

HI @igorkaplan55 , are you still facing this error? This looks like it's spawning from your local docker configuration.

**Comment by vijtrip2** [comment]
Closing this issue. Please reopen if you are still facing these errors.
