### ISSUE TITLE
Route53 controller GA release

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#1314]
Determine exit criteria for Route53 controller GA release and implement them.

**Comment by RedbackThomson** [comment]
For GA I propose we release the following CRDs:
- `HostedZone`
- `TrafficPolicy`
- `RecordSet`

This should allow Route53 users to create and manage their domain, DNS records and traffic flow through that domain.

**Comment by a-hilaly** [comment]
Duplicated of https://github.com/aws-controllers-k8s/community/issues/480
