### ISSUE TITLE
Issue with import path of the Amazon Managed Service for Prometheus (AMP) package

### ISSUE THREAD

**Issue by JamesJHPark** [aws-controllers-k8s/community#1322]
**Describe the bug**
In the process of generating the `amp` controller, we generate the import path as `github.com/aws/aws-sdk-go/service/amp`. However, the AMP package name in `aws-sdk-go/service` is `prometheusservice`, and there is no matching `ServiceID` of the service package name to import. 

**Steps to reproduce**

- Run the latest version of the code-generator against the `amp` controller

**Expected outcome**

- Import path should be set using the `aws-sdk-go` package name.

**Environment**

- AWS service targeted (S3, RDS, etc.) `amp`

**Comment by RedbackThomson** [comment]
Hey @JamesJHPark 

Check out this pull request - where I tried to figure out how the AWS APIs and SDKs use different names, and what the overlap is - https://github.com/aws-controllers-k8s/code-generator/pull/213

If AMP introduces a 4th type of name, then that's good to know

**Comment by JamesJHPark** [comment]
As per discussion with @A-Hilaly , @RedbackThomson, the service package name of the Amazon Managed Service for Prometheus (AMP) is `prometheusservice`. Also, with the [service naming nomenclature](https://github.com/aws-controllers-k8s/code-generator/pull/213), we can distinguish the service id and names to code-generate the ACK controller. Accordingly, we generate the import path as `github.com/aws/aws-sdk-go/service/prometheusservice`, and include the optional model-name field in the `generator.yaml` file to override the service name and search the API file in aws-sdk/go/models/apis. Resolved the issue with code-generating the `prometheusservice` controller.
