### ISSUE TITLE
Prometheusservice service controller

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1323]
## New ACK Service Controller

Support for [Amazon Managed Prometheus service](https://aws.amazon.com/prometheus/)

### List of API resources

List the API resources in order of importance to you:

1) [Workspace](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-CreateWorkspace)
2) [RuleGroupsNamespace](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-CreateRuleGroupsNamespace)
3) [AlertManagerDefinition](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-CreateAlertManagerDefinition)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
