### ISSUE TITLE
Add `SecurityGroupRules` to EC2 `SecurityGroup`

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1326]
**Is your feature request related to a problem?**
The EC2 `SecurityGroup` currently allows you to create and associate an EC2 Security Group with a VPC, but there is no way to add rules. The AWS SDK for Go supports adding rules through a separate method called [`ModifySecurityGroupRules`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.ModifySecurityGroupRules). 

**Describe the solution you'd like**
A new `SecurityGroupRules` property in the spec of EC2 `SecurityGroup` and custom hooks supporting the handling of those rules with the API.

**Comment by vijtrip2** [comment]
@brycahta , Please take a look at this. It is an important part missing from SecurityGroup CRD.
If there is already an open issue that you are tracking, please close this one.

**Comment by brycahta** [comment]
Working on this now
