### ISSUE TITLE
Wrong ConfigMap and Secret names on Red Hat OpenShift pre-installation instructions

### ISSUE THREAD

**Issue by juanrh** [aws-controllers-k8s/community#1343]
**What is the URL of the document?**
https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/

**Which section(s) is the issue in?**

[Step 3: Create ack-$SERVICE-user-config and ack-$SERVICE-user-secrets for authentication](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/#step-3-create-ack-service-user-config-and-ack-service-user-secrets-for-authentication)

**What needs fixing?**
The documentation indicates that I should create a ConfigMap with name "ack-$SERVICE-user-config" and a Secret with name "ack-$SERVICE-user-secrets". Instead, those names should be "ack-user-config" and "ack-user-secrets". See "additional context" below for details

**Additional context**

When testing this for the operator ["AWS Controllers for Kubernetes - Amazon RDS"](https://operatorhub.io/operator/ack-rds-controller), after installing the operator using the OpenShift console following "Step 4: Install the controller", then the controller pod fails to start, and the following Pod event is visible

> Error: configmap "ack-user-config" not found

This issue is solved by using the following names:

- "ack-user-config" for the ConfigMap
- "ack-user-secrets" for the Secret

instead of the names that appear in the documentation.

**Comment by RedbackThomson** [comment]
Which controller and version are you attempting to use? We actually switched from `ack-user-config` to `ack-$SERVICE-user-config` a little while ago, so that you could have separate configmaps per service - giving more fine-grain control over permissions. It's possible that the controller you're trying to use has not been released since we made that change, and still looks for the older name.

**Comment by acornett21** [comment]
@RedbackThomson Has a release happened since the `code-gen` PR went in?

**Comment by acornett21** [comment]
I see a release that happened today (well merges into the appropriate controllers for v0.19.0), so we just need for those all to trickle through and should be in OperatorHub after that.

**Comment by juanrh** [comment]
> Which controller and version are you attempting to use?

This was the RDS controller `ack-rds-controller.v0.0.24`

```
$ oc -n ack-system get  operatorgroup ack-system-cvk92
NAME               AGE
ack-system-cvk92   166m
jrodrig-mac:ACK jrodrig$ oc -n ack-system get operatorgroup ack-system-cvk92 -o yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: DBCluster.v1alpha1.rds.services.k8s.aws,DBClusterParameterGroup.v1alpha1.rds.services.k8s.aws,DBInstance.v1alpha1.rds.services.k8s.aws,DBParameterGroup.v1alpha1.rds.services.k8s.aws,DBSecurityGroup.v1alpha1.rds.services.k8s.aws,DBSubnetGroup.v1alpha1.rds.services.k8s.aws,GlobalCluster.v1alpha1.rds.services.k8s.aws
  creationTimestamp: "2022-06-15T08:29:45Z"
  generateName: ack-system-
  generation: 2
  name: ack-system-cvk92
  namespace: ack-system
  resourceVersion: "9191199"
  uid: 225f38bf-da06-4103-bd0b-f05d5a6b5cc3
spec: {}
status:
  lastUpdated: "2022-06-15T08:29:45Z"
  namespaces:
  - ""

$ oc -n ack-system get subscription ack-rds-controller -o yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2022-06-15T08:29:45Z"
  generation: 1
  labels:
    operators.coreos.com/ack-rds-controller.ack-system: ""
  name: ack-rds-controller
  namespace: ack-system
  resourceVersion: "9191357"
  uid: df7b09ef-238f-4c77-afbf-b623608dbace
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: ack-rds-controller
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ack-rds-controller.v0.0.24
status:
...
```

So that explains that. Certainly it's nicer to be able to have separate configurations and permissions per controller. 

I'll wait for the update, thanks a lot for the prompt response!

**Comment by RedbackThomson** [comment]
@juanrh No problem, Juan. We're just cleaning up some bugs with the new `v0.19.0` runtime, but hope to get those out *soon*. I can update you when they are ready

**Comment by RedbackThomson** [comment]
@juanrh Try out https://github.com/aws-controllers-k8s/rds-controller/releases/tag/v0.0.27 and let me know

**Comment by vijtrip2** [comment]
Closing the issue based on @acornett21's  comment.

**Comment by juanrh** [comment]
@RedbackThomson thanks for the heads up. I just tested it on a cluster. The version 0.0.27 of "AWS Controllers for Kubernetes - Amazon RDS" was available in Operator Hub without any additional configuration. With that an a ConfigMap ack-rds-user-config and a secret ack-rds-user-secrets now the pod for the Deployment ack-rds-controller is launching fine and accessing the AWS credentials.

So I confirm that for me this is working perfectly, and is consistent with the docs.

Thanks for the quick response!
