### ISSUE TITLE
Update to some .spec fields for DBInstance causes infinite restart loop

### ISSUE THREAD

**Issue by teddyking** [aws-controllers-k8s/community#1346]
**Describe the bug**

We have observed a condition in which an update to some `.spec` fields on a `DBInstance` resource can lead to the RDS instance entering an infinite restart loop.
Specifically it seems to be `.spec` fields for which the ack service controller attempts to set non-null defaults if values for the fields are not provided when the `DBInstance` is first created.
Although we have only verified this behaviour using `.spec.storageType`, we believe the following fields will behave in the same way:

```
spec:
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 1
  copyTagsToSnapshot: false
  deletionProtection: false
  licenseModel: postgresql-license
  monitoringInterval: 0
  multiAZ: false
  preferredBackupWindow: 23:00-23:30
  preferredMaintenanceWindow: wed:23:34-thu:00:04
  publiclyAccessible: false
  storageEncrypted: false
  storageType: gp2
```

**Steps to reproduce**

### Step 1: Create a DBInstance and do not set .spec.storageType

```console
$ cat <<EOF | kubectl apply -f-
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: rds-psql-1
  namespace: default
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: rds-psql-1
  dbName: postgres
  engine: postgres
  engineVersion: "14.1"
  masterUsername: adminUser
  masterUserPassword:
    namespace: default
    name: rds-psql-password
    key: password
  vpcSecurityGroupIDs:
  - sg-xxx
  dbSubnetGroupName: dbsubnetgroup
EOF
```

### Step 2: Wait for ACK to sync the instance

Wait for the instance to become Available, then get the `DBInstance` resource and confirm that the ack controller has now set a default value for `.spec.storageType`

```console
$ kubectl get dbinstance -n default rds-psql-1 -o jsonpath={'.spec.storageType'}; echo
gp2
```

### Step 3: Edit the DBInstance to remove `.spec.storageType`

```console
$ kubectl edit dbinstance -n default rds-psql-1
# remove `.spec.storageType`
```

### Step 4: Observe infinite cycle

See ACK ending up in a infinite cycle that causes the actual RDS instance running AWS to be updated and restarted continiously.
This can be verified by waiting 5-10 minutes after making the edit and then viewing the "Recent events" for the RDS instance in the AWS web console.

### Step 5: Exit cycle manually

To exit that cycle, manually set `.spec.storageType` on the `DBInstance` (e.g. to the default value of `gp2`)

**Expected outcome**

I expect that the instance doesn't continuously restart if I update one of the listed spec values.

**Additional Info**

After some debugging and looking over the code we believe that the core of the issue lies inside the Update method of
the RDS resource manager. That method uses the AWS SDK for Go to update the external RDS instance running in AWS. In
case of a successful update the method still returns a non-nil error because of [this line](https://github.com/aws-controllers-k8s/rds-controller/blob/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599/pkg/resource/db_instance/sdk.go#L2368).

The [reasoning](https://github.com/aws-controllers-k8s/rds-controller/blob/48abf6cd03988a5645d3be39b2f3f81985ef7a20/pkg/resource/db_instance/hooks.go#L98) for doing that is "Requeueing resource after successful update; status fields retrieved asynchronously". This then causes the runtime reconciler to [exit early](https://github.com/aws-controllers-k8s/runtime/blob/35dd8c179dec95abeec3e84c0694cf6b9e8a275c/pkg/runtime/reconciler.go#L529) without updating the `DBInstance` resource in the cluster, which would have happened later and should have set default values for any optional property that hasn't been set explicitly.

In the example above `.spec.storageType` is not being set to its default value after the successful update (e.g. `gp2`).
That means the `DBInstance` resource in our cluster is still out-of-sync with the actual RDS instance running in AWS
even though the update was in fact successful. During the next reconcile (every 30 seconds) that diff will cause another
update which causes yet another restart of the RDS instance running in AWS and gets us in the same situation. We are now
in the infinite update-restart cycle.

To stop this from happening, it seems the ACK RDS controller could change [the Update method](https://github.com/aws-controllers-k8s/rds-controller/blob/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599/pkg/resource/db_instance/sdk.go#L236) for `DBInstance` to no longer override the error in order to trigger a requeue but instead make use of conditions the same way that is done [in the Create method here](https://github.com/aws-controllers-k8s/rds-controller/blob/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599/pkg/resource/db_instance/sdk.go#L1446).

**Environment**

* Kubernetes version: v1.21.12
* Using EKS (yes/no), if so version? Yes, v1.21.12
* AWS service targeted (S3, RDS, etc.) RDS
* RDS ACK controller version: v0.0.24

\- @teddyking / @st3v

**Comment by RedbackThomson** [comment]
> To stop this from happening, it seems the ACK RDS controller could change [the Update method](https://github.com/aws-controllers-k8s/rds-controller/blob/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599/pkg/resource/db_instance/sdk.go#L236) for DBInstance to no longer override the error in order to trigger a requeue but instead make use of conditions the same way that is done [in the Create method here](https://github.com/aws-controllers-k8s/rds-controller/blob/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599/pkg/resource/db_instance/sdk.go#L1446).

I actually think this is a very good idea. Relying on returning an error to requeue has become a bit of a pain point in the `runtime` logic. Let me give that a shot and see if that can be a solution for unblocking the latest runtime updates.

**Comment by RedbackThomson** [comment]
I have re-opened this. Even though the fix was pushed into the RDS controller repository, we haven't made a new release for it yet. I'll come in and close this when we have.
