### ISSUE TITLE
Install docs can be simplified for helm 3.8+

### ISSUE THREAD

**Issue by acmcelwee** [aws-controllers-k8s/community#1347]
**What is the URL of the document?**

[](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/#install-an-ack-service-controller-with-helm-recommended)

**Which section(s) is the issue in?**

Install an ACK service controller with Helm (Recommended)

**What needs fixing?**

[As of Helm 3.8+, the OCI support for charts is generally available](https://github.com/helm/helm/releases/tag/v3.8.0). 

This should simplify the setup steps required, since you'd no longer need to first pull down the OCI artifact down and extract the charts before running the `helm install`.

Ignoring the additional helm install args, the base install action for the latest version of, say the iam controller chart, boils down to: `helm install iam-chart oci://public.ecr.aws/aws-controllers-k8s/iam-chart --version v0.0.16`

**Additional context**

**Comment by RedbackThomson** [comment]
Oh awesome. I actually just changed this on our `examples` repository, yesterday. I will copy over the changes :)
