### ISSUE TITLE
Question/Clarification/Bug - ACK-Controllers reconciliation after getting to desired state

### ISSUE THREAD

**Issue by ShacharMalachi** [aws-controllers-k8s/community#1355]
**Describe the bug**
ACK-Controllers don't override manual changes (e.g aws-console) after resource is getting to the desired state, even after few days of waiting.

There was a similar issue here: https://github.com/aws-controllers-k8s/community/issues/1288
The answer says that ACK-Controllers are using K8s API server default requeue time (described as 8 hours in this answer), but when I tested it, I waited few days and the controllers still didn't requeued.

I've seen this code here: https://github.com/aws-controllers-k8s/s3-controller/blob/b23f9784d06baf6cbafaaf751734ea3b7aae9613/pkg/resource/bucket/manager_factory.go#L85
Does it mean that the controller would never requeued unless I'll restart the pod or rollout the deployment? If it is, do you plan in the future to enable users to control this value?

Thanks,
Shachar.

**Steps to reproduce**
Tested for S3 controller (but same for other controllers such as ElastiCache)
1. Create S3 Bucket with controller
2. Wait for Bucket resource get to desired state
3. Change Bucket property manually via AWS console
4. Wait few days
5. S3-Controller didn't override manual changes
7. Only when I manually restarted the s3-controller, manual changes were override by s3-controller as expected.

**Expected outcome**
S3-Controller should override manual changes after Bucket getting to desired state.

**Environment**

* Kubernetes version: v1.22.7
* Using EKS: No
* AWS service targeted: S3-Controller v0.1.0

**Comment by vijtrip2** [comment]
@ShacharMalachi , thanks for bringing this to our attention. I will reproduce this and report back on this issue. I will try to validate that requeue happens at 8 hour interval.

> I've seen this code here: https://github.com/aws-controllers-k8s/s3- controller/blob/b23f9784d06baf6cbafaaf751734ea3b7aae9613/pkg/resource/bucket/manager_factory.go#L85

This code should not be overriding the k8s controller runtime requeue behavior.

**Comment by ShacharMalachi** [comment]
> @ShacharMalachi , thanks for bringing this to our attention. I will reproduce this and report back on this issue. I will try to validate that requeue happens at 8 hour interval.
> 
> > I've seen this code here: https://github.com/aws-controllers-k8s/s3- controller/blob/b23f9784d06baf6cbafaaf751734ea3b7aae9613/pkg/resource/bucket/manager_factory.go#L85
> 
> This code should not be overriding the k8s controller runtime requeue behavior.

Hi @vijtrip2 

Any news regarding trying to reproduce this issue?

Thanks,
Shachar.

**Comment by vijtrip2** [comment]
Hi @ShacharMalachi , I was able to reproduce the issue. We will be working on fixing this bug ASAP.

**Comment by vijtrip2** [comment]
Hi @ShacharMalachi , I found the issue and submitted a fix. I will let you know when new release of the s3 controller is out, and you can validate the fix too. Thanks!

**Comment by ShacharMalachi** [comment]
> Hi @ShacharMalachi , I found the issue and submitted a fix. I will let you know when new release of the s3 controller is out, and then you can validate the fix too.

Hi @vijtrip2, Thank you very much for the quick fix, I truly appreciate it!

**Comment by vijtrip2** [comment]
Hi @ShacharMalachi , you are welcome!

The new controller image and helm chart are published, and they should perform periodic drift detection every 10 hours to reconcile the desired state. https://gallery.ecr.aws/aws-controllers-k8s/s3-chart

We chose 10 hours because that is the default for upstream controller-runtime as well.

**Comment by MohammadAlavi1986** [comment]
The default value for s3 resource manager factory is `0` which means the resource will not be re-synced.

https://github.com/aws-controllers-k8s/s3-controller/blob/main/pkg/resource/bucket/manager_factory.go#L82
```
// RequeueOnSuccessSeconds returns true if the resource should be requeued after specified seconds
// Default is false which means resource will not be requeued after success.
func (f *resourceManagerFactory) RequeueOnSuccessSeconds() int {
	return 0
}
```

I had to add the following arguments to the s3 controller [deployment](https://github.com/aws-controllers-k8s/s3-controller/blob/main/config/controller/deployment.yaml#L27) to make it re-sync resources every 180 seconds.

```
        - --reconcile-resource-resync-seconds
        - "Bucket=180"
```

**Comment by a-hilaly** [comment]
@MohammadAlavi1986 `RequeueOnSuccessSeconds` is only leveraged if it returns a value > 0 (the function is generated). By default the controller requeues every 10hours if one of tweaking options is not specificed (`--reconcile-resource-resync-seconds`). Here is the part of code that decides which parameter to use https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L1084-L1132
