### ISSUE TITLE
Drift Remediation For ACK Resources

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#1367]
**Is your feature request related to a problem?**
When an AWS resource managed by an ACK controller gets modified outside of the controller scope, through AWS console or AWS CLI, the controller should perform drift remediation and update the resource back to it's desired state.

**Describe the solution you'd like**

- [ ] ACK controller should be able to perform periodic drift remediation for AWS resources managed by that controller.
- [ ] Drift remediation period should be configurable during controller installation
- [ ] Helm artifacts should provide a configurable value for controller drift remediation period
- [ ] Drift remediation period should be configurable per resource using annotation

Note: Current drift remediation period is 10 hours and it is not configurable per installation or per resource by ACK customers.

**Comment by jaypipes** [comment]
I think we are likely to want different drift remediation seconds values per resource. I think a CLI option structured like so would probably work:

```
--drift-remediation-seconds-default=<NUMBER_SECONDS>
```

would apply to all resources without an override that the controller manages.

```
--drift-remediation-configuration=<JSON>
```

would allow overriding specific resources with the following serialized JSON representation:

```json
{
  "<RESOURCE_NAME>": {
    "seconds": <SECONDS>, // <=0 indicates no drift remediation will occur
  }, ...
}
```

so, image the RDS controller started with the following CLI option:

```
--drift-remediation-configuration='{"dbinstance": {"seconds": 0}, "dbinstancereadreplica": {"seconds": 300}}'
```

would indicate no drift remediation for DB Instances and a 5-minute drift remediation for DB Instance Read Replicas.

I think this setup would give us the flexibility I image we will get requests for...

**Comment by vijtrip2** [comment]
> Will we need to handle "undesirable" fields as well? For example, if I create a _Subnet_ with `VPCID` and `CIDRBlock`, then after some time my application associates an `IPv6CIDRBlock` with this _Subnet_, then would drift remediation be triggered and try to disassociate the `IPv6CIDRBlock`? In this context, I didn't specify the block myself but also do not care about this value at all.
> 
> Or should this be on the user to know their resources' interactions/potential states when the resource is being managed by controller?

In this case, IPv6CIDRBlock should get late initialized into the Subnet, correct? And then the resync will not override it.

**Comment by acornett21** [comment]
Taking my thoughts from the community meeting and putting them on paper.

1. This probably shouldn't be an additional (separate) CR/Configuration entity, as it would not be able to be packaged with the OpenShift operators.
2. It would be best if this was an `optional` field added to _all_ ACK CR's after they have been generated from the AWS API. This would allow a default to be configured in the controller code itself, then give the ability for the user to apply a CR and have that specific resource reconciled at a given interval.

These are just some general thoughts, ideas. I'm sure other ideas could work as well, but we want to make sure whatever is implemented works both in k8's and OpenShift controllers.
