### ISSUE TITLE
Resources references for Lambda controller

### ISSUE THREAD

**Issue by jkatz** [aws-controllers-k8s/community#1394]
**Is your feature request related to a problem?**

Pieces of the Lambda controller can have resources that it may need to reference. For example, Lambda functions can be stored in S3 buckets and therefore depend on that buckets creation.

**Describe the solution you'd like**

Here are a list of refs that can be added in each of the CRD specs. Note that names may be changed if I'm not matching convention.

Function
* `code.s3BucketRef`
* `kmsKeyRef`
* `vpcConfig.securityGroupRefs`
* `vpcConfig.subnetRefs`

FunctionUrlConfig
* `functionName`

Alias
* `functionName`

EventSourceMapping
* `functionName`
* `AMKArn`

**Comment by A-Hilaly** [comment]
We're having issues assigning people that are not part of @aws-controllers-k8s/community-maintainers  @Vandita2020 will own this ticket.

**Comment by A-Hilaly** [comment]
@Vandita2020 I think only `AMKRef` is missing here, or can we close this?

**Comment by A-Hilaly** [comment]
ping @Vandita2020
