### ISSUE TITLE
VPC FlowLogs can't be generated

### ISSUE THREAD

**Issue by akesser** [aws-controllers-k8s/community#1408]
**Describe the bug**
VPC FlowLogs exist in the aws sdk for go
[https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CreateFlowLogs](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CreateFlowLogs), but do not exist in the ec2 generator-config.yaml, therefore we cannot activate them for creation 

**Steps to reproduce**

**Expected outcome**
We should be able to generate the code for FlowLogs

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by A-Hilaly** [comment]
Hey @akesser, did you try to bump `aws-sdk-go` version in ec2-controller `go.mod` file? this might solve your issue

**Comment by haarchri** [comment]
we trying to implement this in crossplane  but it looks like it is not possible - because this resource is not in ignore_list
https://github.com/crossplane-contrib/provider-aws/blob/master/apis/ec2/generator-config.yaml#L2
and the resource is not implemented

**Comment by A-Hilaly** [comment]
I just tried with our ec2-controller repository and i am not able to generate the `FlowLog` crd - this might be a bug in our code-generator. Investigating the root cause very soon

**Comment by haarchri** [comment]
Thanks

**Comment by xoanmi** [comment]
Related slack 🧵: https://crossplane.slack.com/archives/C01718T2476/p1659004740260759

**Comment by A-Hilaly** [comment]
The code-generator consider `CreateFlowLogs` a CreateBatch operation. Adding the following block to the generator configuration file should solve the issue:
```yaml
operations:
  CreateFlowLogs:
    operation_type:
    - Create
    resource_name: FlowLogs
```
