### ISSUE TITLE
Renaming a Controller 

### ISSUE THREAD

**Issue by ilangofman** [aws-controllers-k8s/community#1411]
**Is your feature request related to a problem?**
Currently, I am working on the Amazon Managed Service for Prometheus (AMP) controller. Right now, the name of the controller is `prometheusservice-controller`. I was wondering if it would be possible to rename a controller repository to something more fitting such as `amp-controller`.  

**Describe the solution you'd like**

I understand right now that the name comes from the aws-sdk-go library. Which the controller imports are based on. Would there be any way to separate the controller name from the sdk import path?

**Comment by RedbackThomson** [comment]
Sorry but all of our tooling and documentation lines up with the current naming scheme. I opened [a PR](https://github.com/aws-controllers-k8s/code-generator/pull/213) a while ago clarifying what each service uses as their identifiers and where they are used in ACK. It would be a pretty monumental effort for us to refactor this, even just for a single repository.

**Comment by a-hilaly** [comment]
Already released controller cannot be renamed, however, current code-generator supports renaming the controller name/module which is permissible if the controller didn't receive a an official release.
/close
