### ISSUE TITLE
Question: Lambda controller not updating configuration

### ISSUE THREAD

**Issue by karmingc** [aws-controllers-k8s/community#1413]
**Describe the bug**
I'm not sure if this is exactly a bug, but I noticed that whenever I try to update a field, for example, `timeout`, it does not update on the lambda function.

I looked in CloudTrail and saw the `UpdateFunctionConfiguration` event and noticed that it was not in the `RequestParameters`. However, the ECR image URI that I provide on the new deploy is included.

**Steps to reproduce**
1. Deploy lambda function with `timeout` with a value of `5` with an image URI of "uriA" -> lambda pulling from uriA and has a timeout of 5.
2. Once deployed, update the resource template with a value of `10` with an image URI of "uriB" -> lambda pulling from uriB and has a timeout of 5.

**Expected outcome**
The lambda function should have a newly updated timeout of 10 seconds.

**Environment**

Kubernetes version
Using EKS (yes/no), if so version? 1.22.5
AWS service targeted (S3, RDS, etc.): Lambda
We also use Helm to deploy if that matters.

**Comment by A-Hilaly** [comment]
HI @karmingc thank you for reporting this issue. I'm currently refactoring lambda-controller e2e tests and will take a look a this very soon.

**Comment by A-Hilaly** [comment]
Could you please provide the version of the controller, and some logs related this event?

**Comment by karmingc** [comment]
hi @A-Hilaly, we are currently using `v0.0.16`

I wasn't able to get much informative logs through Helm, but can provide the ones from cloudtrail. Let me know if you have specific ones in mind.

resource template
```
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: <>
spec:
  name: <>
  packageType: "Image"
  role: arn:aws:iam::***:role/<>
  code:
    imageURI: ***.dkr.ecr.us-east-1.amazonaws.com/<>
  environment:
    variables:      
      ENVIRONMENT: <>
  timeout: 5 # update here to test whether it updated to new value of 10s
  vpcConfig:
    securityGroupIDs:
      - "<>"
    subnetIDs:
      - "<>"
      - "<>"
      - "<>"
```

CreateFunction event through cloudtrail:
```json
...
    "eventTime": "2022-08-08T15:47:41Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "CreateFunction20150331",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "...",
    "userAgent": "aws-controllers-k8s/-v0.0.16 (GitCommit/<>; BuildDate/2022-05-23T16:37; CRDKind/; CRDVersion/) aws-sdk-go/1.42.0 (go1.17.10; linux; amd64)",
    "requestParameters": {
        "functionName": "<>",
        "role": "arn:aws:iam::<>:role/<>",
        "code": {
            "imageUri": "<>.dkr.ecr.us-east-1.amazonaws.com/<>"
        },
        "timeout": 5,
        "publish": false,
        "vpcConfig": {
            "subnetIds": [
                "<>",
                "<>",
                "<>"
            ],
            "securityGroupIds": [
                "<>"
            ]
        },
        "packageType": "Image",
        "environment": {}
    },
    "responseElements": {
        "functionName": "<>",
        "functionArn": "arn:aws:lambda:us-east-1:<>:function:<>",
        "role": "arn:aws:iam::<>:role/<>",
        "codeSize": 0,
        "description": "",
        "timeout": 5,
        "memorySize": 128,
        "lastModified": "2022-08-08T15:47:40.461+0000",
        "codeSha256": "<>",
        "version": "$LATEST",
        "vpcConfig": {
            "subnetIds": [
                "<>",
                "<>",
                "<>"
            ],
            "securityGroupIds": [
                "<>"
            ],
            "vpcId": "<>"
        },
        "environment": {},
        "tracingConfig": {
            "mode": "PassThrough"
        },
        "revisionId": "<>",
        "state": "Pending",
        "stateReason": "The function is being created.",
        "stateReasonCode": "Creating",
        "packageType": "Image",
        "architectures": [
            "x86_64"
        ],
        "ephemeralStorage": {
            "size": 512
 ...     
```

UpdateFunction
```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "<>",
        "arn": "arn:aws:sts::<>:assumed-role/<>",
        "accountId": "<>",
        "accessKeyId": "<>",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "<>",
                "arn": "arn:aws:iam::<>:role/<>",
                "accountId": "<>",
                "userName": "<>"
            },
            "webIdFederationData": {
                "federatedProvider": "arn:aws:iam::<>",
                "attributes": {}
            },
            "attributes": {
                "creationDate": "2022-08-08T16:02:50Z",
                "mfaAuthenticated": "false"
            }
        }
    },
    "eventTime": "2022-08-08T16:02:56Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "UpdateFunctionCode20150331v2",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "<>",
    "userAgent": "aws-controllers-k8s/-v0.0.16 (GitCommit/<>; BuildDate/2022-05-23T16:37; CRDKind/; CRDVersion/) aws-sdk-go/1.42.0 (go1.17.10; linux; amd64)",
    "requestParameters": {
        "fullyQualifiedArn": {
            "arnPrefix": {
                "partition": "aws",
                "region": "us-east-1",
                "account": "<>"
            },
            "relativeId": {
                "functionName": "<>"
            },
            "functionQualifier": {}
        },
        "functionName": "arn:aws:lambda:us-east-1<>:function:<>",
        "publish": false,
        "imageUri": "<>.dkr.ecr.us-east-1.amazonaws.com/<new image uri>",
        "dryRun": false
    },
    "responseElements": {
        "functionName": "<>",
        "functionArn": "arn:aws:lambda:us-east-1:<>:function:<>",
        "role": "arn:aws:iam:<>:role/<>",
        "codeSize": 0,
        "description": "",
        "timeout": 5,
        "memorySize": 128,
        "lastModified": "2022-08-08T16:02:56.000+0000",
        "codeSha256": "<>",
        "version": "$LATEST",
        "vpcConfig": {
            "subnetIds": [
                "<>",
                "<>",
                "<>"
            ],
            "securityGroupIds": [
                "<>"
            ],
            "vpcId": "<>"
        },
        "environment": {},
        "tracingConfig": {
            "mode": "PassThrough"
        },
        "revisionId": "<>",
        "state": "Active",
        "lastUpdateStatus": "InProgress",
        "lastUpdateStatusReason": "The function is being created.",
        "lastUpdateStatusReasonCode": "Creating",
        "packageType": "Image",
        "architectures": [
            "x86_64"
        ],
        "ephemeralStorage": {
            "size": 512
        }
    },
    "requestID": "<>",
    "eventID": "<>",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "<>",
    "eventCategory": "Management",
    "tlsDetails": {
        "clientProvidedHostHeader": "lambda.us-east-1.amazonaws.com"
    }
}
```

**Comment by A-Hilaly** [comment]
Hi @karmingc, i have been able to reproduce the issue, it looks like it's a bug in the update code path. I'm actively working on a fix, I will ping you here once we make a new release.

**Comment by A-Hilaly** [comment]
We just release `v0.0.17` with a fix. Can you give it shot @karmingc ?

**Comment by karmingc** [comment]
apologies for the very late reply @A-Hilaly, I recently deployed `v0.1.2` to our cluster and the issue is still persisting...
I tried updating the description and the timeout but no changes reflected on the lambda...

Here's the event with 
```json
    "eventTime": "2022-10-27T17:33:28Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "UpdateFunctionCode20150331v2",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "...",
    "userAgent": "aws-controllers-k8s/-v0.1.2 (GitCommit/88784c04d9130d3769728c074fe0998c9529d219; BuildDate/2022-10-07T15:29; CRDKind/; CRDVersion/) aws-sdk-go/1.44.93 (go1.17.13; linux; amd64)",
    "requestParameters": {
        "fullyQualifiedArn": {
            "arnPrefix": {
                "partition": "aws",
                "region": "us-east-1",
                "account": "..."
            },
            "relativeId": {
                "functionName": "..."
            },
            "functionQualifier": {}
        },
        "functionName": "arn:aws:lambda:us-east-1:...",
        "publish": false,
        "imageUri": "...",
        "dryRun": false
    },
    "responseElements": {
        "functionName": "...",
        "functionArn": "...",
        "role": "...",
        "codeSize": 0,
        "description": "<old description>",
        "timeout": <old timeout>,
        "memorySize": 128,
        "lastModified": "2022-10-27T17:33:28.000+0000",
        "codeSha256": "...",
        "version": "$LATEST",
        "environment": {},
        "tracingConfig": {
            "mode": "PassThrough"
        },
        "revisionId": "cbdc7bb6-9ed9-4287-ad00-5707cb1efba7",
        "state": "Active",
        "lastUpdateStatus": "InProgress",
        "lastUpdateStatusReason": "The function is being created.",
        "lastUpdateStatusReasonCode": "Creating",
        "packageType": "Image",
        "architectures": [
            "x86_64"
        ],
        "ephemeralStorage": {
            "size": 512
        }
    },
    "requestID": "3ceb2782-1433-46cd-9815-cb1d879002fa",
```

**Comment by A-Hilaly** [comment]
Ohh thank you for reporting this. Reopening and investigating soon :)
/reopen

**Comment by A-Hilaly** [comment]
Hi @karmingc , i am not able to reproduce the same bug with the latest version of lambda-controller.
Here is the function manifest i'm deploying
```yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: ack-img-function
  annotations:
    services.k8s.aws/region: eu-west-2
spec:
  name: ack-img-function
  packageType: Image
  code:
    imageURI: <ID>.dkr.ecr.eu-west-2.amazonaws.com/test2:latest
  role: arn:aws:iam::<ID>:role/ack-lambda-test-role
  description: a lambda function create with an image URI
```
I run `kubectl edit functions` and change memory to 256, timeout to 5 and the description.

Executing `aws lambda get-function --function-name ack-img-function --region eu-west-2` shows that the fields have been updated correctly.

Am I missing something in my experiement?

**Comment by karmingc** [comment]
Hi @A-Hilaly,

I can confirm that using `kubectl edit functions`, it does update function. However, I'm actually deploying this k8s manifest through helm and i'm not quite sure why it's not propagating when doing so with `helm upgrade`... I'll look into it, but if you have any suggestions, happy to listen!

**Comment by A-Hilaly** [comment]
May I ask what version of helm are you using? one thing i would start with is checking the output using `helm cmd --dry-run`

**Comment by karmingc** [comment]
We use version `v3.5.3` and I'm able to see that the manifest deployed on the server are indeed updated.. 

```sh
# Source: .../templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: ack-img-function
spec:
  name: ack-img-function
  description: "[Test3] "
  packageType: "Image"
  role: ...
  code:
    imageURI: img-uri
  environment:
    variables:
      ENVIRONMENT: sandbox
  timeout: 15
```

However, on the actual lambda itself, it's still the original value of 10 seconds for timeout and the original description.

**Comment by karmingc** [comment]
Ah I should specify that we are using `helm upgrade` command... After a bit of searching, found this old answer that Helm uses the [Patch API](https://github.com/helm/helm/issues/5915#issuecomment-505389394). Though, I was converted my yaml file to json and applied the `patch` using `kubectl patch function <function_name> --patch-file lambda.json --type merge` and the lambda config changes updated...

**Comment by karmingc** [comment]
@A-Hilaly it seems that it's consistent with the IAM controller too when using the `upgrade` function with helm

**Comment by A-Hilaly** [comment]
This is a normal behaviour. Helm upgrade will upgrade your controller (deployment, service etc..) but your lambda function is a separate resource. You'll have to manually trigger a reconciliation by updating one of the fields (description for example)

**Comment by karmingc** [comment]
Apologies, that's a typo, i'm referring to the custom resources, not the controller itself, such the IAM [role](https://aws-controllers-k8s.github.io/community/reference/iam/v1alpha1/role/) and IAM [policy](https://aws-controllers-k8s.github.io/community/reference/iam/v1alpha1/policy/).

**Comment by A-Hilaly** [comment]
Yes. If you are calling helm upgrade with a helm chart containing a lambda function, without modifying it. The upgrade will not trigger any reconciliation.
To trigger resource update you will to do one of the following:
- Upgrade the controller version (will restart a new controller hence trigger a reconciliation)
- Update your custom resource, either in the helm chart or directly using `kubectl edit/apply`

**Comment by karmingc** [comment]
> Yes. If you are calling helm upgrade with a helm chart containing a lambda function, without modifying it. The upgrade will not trigger any reconciliation. To trigger resource update you will to do one of the following:
> 
> * Upgrade the controller version (will restart a new controller hence trigger a reconciliation)
> * Update your custom resource, either in the helm chart or directly using `kubectl edit/apply`

Yes, i'm suggesting that we are indeed updating the custom resource in the helm chart by modifying some fields of it, such as `description`, `timeout`, etc... But the upgrade is not triggering any reconciliation.

**Comment by karmingc** [comment]
For example, in the first upgrade
```sh
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: <>
spec:
  name: <>
  packageType: "Image"
  role: arn:aws:iam::***:role/<>
  code:
    imageURI: ***.dkr.ecr.us-east-1.amazonaws.com/<>
  environment:
    variables:      
      ENVIRONMENT: <>
  timeout: 5 
  vpcConfig:
    securityGroupIDs:
      - "<>"
    subnetIDs:
      - "<>"
      - "<>"
      - "<>"
```

then in the second upgrade

```sh
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: <>
spec:
  name: <>
  packageType: "Image"
  role: arn:aws:iam::***:role/<>
  code:
    imageURI: ***.dkr.ecr.us-east-1.amazonaws.com/<>
  environment:
    variables:      
      ENVIRONMENT: <>
  timeout: 10
  vpcConfig:
    securityGroupIDs:
      - "<>"
    subnetIDs:
      - "<>"
      - "<>"
      - "<>"
```

But the lambda configuration still indicates a 5 seconds `timeout`.
