### ISSUE TITLE
Bypassing the CallerIdentity validation for running tests 

### ISSUE THREAD

**Issue by grameshtwilio** [aws-controllers-k8s/community#1421]
**Is your feature request related to a problem?**
I would like to test some of the ACK controllers with my `localstack` environment where I pass test credentials to the controller as environment variables. However, the controller errors at this [line](https://github.com/aws-controllers-k8s/runtime/blob/v0.19.3/pkg/config/config.go#L155)

**Describe the solution you'd like**
If a config variable such as `AWS_ACCOUNT_ID` is set, then the `GetCallerIdentity` validation is skipped.

**Describe alternatives you've considered**
Any alternate suggestion to achieve the same goal is perfect

**Comment by A-Hilaly** [comment]
We used to have a `--aws-acount-id` flag before. I'm not against bringing it back and using it if `GetCallerIdentity` fails somehow. @aws-controllers-k8s/runtime-maintainer thoughts?

**Comment by grameshtwilio** [comment]
I found the [PR](https://github.com/aws-controllers-k8s/runtime/pull/54) that removed the `--aws-account-id` flag. It would be great to get it back or enabling something along the lines  of a`--local-run` flag that skips the validation check

**Comment by A-Hilaly** [comment]
I don't think it's safe to add flag that skips all validation checks on a binary that will be running on production.. however i don't see a problem with using `--aws-account-id` to override/default a value. In the mean time you can use a custom runtime library for your tests. Most of the controllers have a local go.mod file that replaces the upstream runtime module with your local one https://github.com/aws-controllers-k8s/s3-controller/blob/main/go.local.mod#L5

**Comment by jaypipes** [comment]
Hi @grameshtwilio! Sorry for delay in commenting on this.

I'm not in favor of adding back the `--aws-account-id` CLI arg for the reasons noted in the PR you linked: it was causing confusion for users during the install/startup process.

I'm similarly not keen to add a flag that skips verification steps for the same reasons that @A-Hilaly mentioned.

From looking at the localstack docs, it looks like you can have localstack run STS (by default on localhost port 4592). You can then simply pass `--endpoint-url` as `https://localhost:4592` and should be good to go. :)
