### ISSUE TITLE
How to pull the charts via Terraform Helm Provider?

### ISSUE THREAD

**Issue by ramnamy** [aws-controllers-k8s/community#1423]
**Describe the bug**
How to pull the charts via Terraform Helm Provider

**Steps to reproduce**

**Expected outcome**
I would like to deploy the ACK controllers via Terraform Helm Chart

**Environment**

* Kubernetes version: 1.23
* Using EKS (yes/no), if so version?  Yes
* AWS service targeted (S3, RDS, etc.) S3

**Comment by A-Hilaly** [comment]
That's a good idea, we could definitely add an example for that in https://github.com/aws-controllers-k8s/examples

**Comment by A-Hilaly** [comment]
@ramnamy would you be interested in contributing and adding a Terraform example to https://github.com/aws-controllers-k8s/examples?

**Comment by Kras4ooo** [comment]
@ramnamy This is just an example with `s3`

```
resource "helm_release" "this" {
  name             = "s3-controller"  # You can put whatever name you like
  namespace        = "ack-controllers"  # You can put whatever name you like
  create_namespace = true
  chart            = "oci://public.ecr.aws/aws-controllers-k8s/s3-chart"
  version          = "v0.1.5"
  recreate_pods    = true
  cleanup_on_fail  = true

  values = [templatefile("${path.module}/templates/values.yaml",{
    REGION       = data.aws_region.this.name
    IAM_ROLE_ARN = aws_iam_role.this.arn
  })]
}
```
