### ISSUE TITLE
Standardize ACK Github labels

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1431]
Currently, we manually create and manage labels in the community repository. Ideally, we could have a script/prow job that periodically syncs the Github labels. 

Here is a list of requirements/nice-to-have things I'm thinking of:
- We need to prefix all label names with their type: `kind`, `area`, `priority`, `service`, etc...
- We need a label for each service controller named `service/$SERVICE`
- We need labels for various areas/domains like `area/architecture`, `area/infra`, `area/testing`, `area/documentation` etc...
- We need to automatically create a new label whenever a new service controller repository - probably this something we can combine with @JamesJHPark work.
- Bring unique labels like `release` for release PRs, and `needs-triage` for unlabeled issues ...
- Create a script that syncs the Github labels across all service controller repositories

**Comment by A-Hilaly** [comment]
Spent sometime brainstorming (mostly getting inspired from open source k/k style of labeling) what labels can be helpful fo r us to support.

**Service labels (issues and PRs)**
- `service/$AWS_SERVICE` (when an issue or PR is related to one service and/or one service controller)
- `service/none` (when an issue or PR a not related to any service specifically)
- `service/all` (when an issue is related to all the services)

**Area labels (issues and PRs):**
(issues or PRs can have one or more of those)

- `area/testing` (Categorizes issue or PR as related to unit tests or e2e tests)
- `area/runtime` (Categorizes issue or PR as related to controller runtime, common reconciliation logic, etc...)
- `area/code-generation` (Categorizes issue or PR as related to controllers or docs code generation)
- `area/infra` (Categorizes issue or PR as related to our testing infrastructure, prow/flux configuration etc...)
- `area/automation` (Categorizes issue or PR as related to automation on top of the infra, prow jobs, release jobs, github actions etc...)
- `area/api/k8s` (Categorizes issue or PR as related to kubernetes API)
- `area/api/aws` (Categorizes issue or PR as related to aws API)
- `area/multi-vesion` (Categorizes issue or PR as related to multi version support)
- `area/documentation`
- `area/security` (Categorizes issue or PR as related to security aws or k8s side)
- `area/example` (Categorizes issue or PR as related to published examples)
- `area/community-meeting` (thinking meeting minutes etc...)

Kind labels (PRs and Issues):
(issues or PRs can have one or more of those)
- `kind/bug`  Categorizes issue or PR as related to a bug. 
- `kind/feature`  Categorizes issue or PR as related to a bug. 
- `kind/cleanup`  Categorizes issue or PR as related to cleaning up code, process, or technical debt. 
- `kind/deprecation`  Categorizes issue or PR as related to a feature/enhancement marked for deprecation. 
- `kind/design`  Categorizes issue or PR as related to design. 
- `kind/documentation`  Categorizes issue or PR as related to documentation. 
- `kind/regression`  Categorizes issue or PR as related to a regression from a prior release. 
- `kind/support`  Categorizes issue or PR as a support question. 
- `kind/flake`  Categorizes issue or PR as related to a flaky test. 
- `kind/failing-tests`  Categorizes issue or PR as related to a consistently or frequently failing test. 
- `kind/cve`  Categorizes issue or PR as related to a CVE

Milestone labels (for runtime and code-generator related issues/PRs)

- `milestone/incomplete-labels` 
- `milestone/needs-approval`
- `milestone/needs-attention`
- `milestone/removed`

Triage labels (Issues only)
- `triage/accepted`
- `triage/duplicate` Indicates an issue is a duplicate of other open issue.
- `triage/needs-information`  Indicates an issue needs more information in order to work on it. 
- `triage/not-reproducible`  Indicates an issue can not be reproduced as described. 
- `triage/unresolved`  Indicates an issue that can not or will not be resolved. 

Rare but can be usefull labels:
- `¯\_(ツ)_/¯` when things are just out of control

Newly created issues should be automatically tagged with `needs-triage`, ` needs-kind `, ` needs-area`.

**Comment by A-Hilaly** [comment]
kubernetes org have a periodic prow job that calls [`label_sync` ](https://github.com/kubernetes/test-infra/tree/master/label_sync) to sync labels from a labels.yaml file. We can either adopt the same script or build something simpler (`label_sync` was built to sync labels a cross multiple organizations and repositories and support deprecation)

**Comment by jaypipes** [comment]
@A-Hilaly I love this.
