### ISSUE TITLE
Script install-helm.sh does not exist

### ISSUE THREAD

**Issue by kskzk** [aws-controllers-k8s/community#1436]
**Describe the bug**
Hi,

When I try to build a controller by using code-generator in an environment where Helm is not installed, an error message to install Helm using scripts/install-helm.sh, but scripts/install-helm.sh does not exist.
```
FATAL: Missing requirement 'helm'
Please install helm before running this script.

You can install Helm with the helper scripts/install-helm.sh
```

Thanks.

**Steps to reproduce**
Run ```make build-controller SERVICE=$SERVICE``` in an environment where Helm is not installed.

**Expected outcome**
Show links such as https://helm.sh/ja/docs/intro/install/.

**Environment**
N/A

**Comment by A-Hilaly** [comment]
Good catch, thank you @kskzk.
