### ISSUE TITLE
Complete rds-controller e2e tests

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1440]
Currently, `rds-controller` is missing few pieces in the e2e tests:

- [x] e2e tests for `dbproxy`
- [x] e2e tests for `global_cluster`
- [x] Patch operations e2e tests for `db_parameter_group`

/cc @brucegucode @jkatz

**Comment by A-Hilaly** [comment]
I will resume the work on https://github.com/aws-controllers-k8s/rds-controller/pull/107 and add e2e tests for `db_paramater_group`

**Comment by brucegucode** [comment]
trying to understand the requirement, is it necessary before GA? like each CRD needs a e2e test ? or it can be delayed after GA?

**Comment by A-Hilaly** [comment]
> is it necessary before GA?

Yes, it is required for each CRD to go GA.

> like each CRD needs a e2e test ?

Correct.

> or it can be delayed after GA?

We can't delay it after GA (we can't release untested CRDs). In case we don't have e2e tests for some CRDs. We believe will have to remove them before releasing the controller.

Note that these tests will be executed during the soak tests for the `rds-controller`

**Comment by brucegucode** [comment]
dbproxy e2e here https://github.com/aws-controllers-k8s/rds-controller/pull/115

**Comment by brucegucode** [comment]
rds proxy e2e tests are already in, I'm adding e2e test for global cluster https://github.com/aws-controllers-k8s/rds-controller/pull/116

The 3rd one will be finished by Amine

**Comment by A-Hilaly** [comment]
DBParameterGroups update operation just have been merged. Rds v0.1.0 is out.
/close
