### ISSUE TITLE
Support state less APIs 

### ISSUE THREAD

**Issue by brucegucode** [aws-controllers-k8s/community#1450]
**Is your feature request related to a problem?**
It's not related to a problem 

**Describe the solution you'd like**
Not sure if it's possible for k8s, but there are some state less APIs from say RDS service. like rebootdbinstance/cluster api. These are only status of db, not related to any Spec of an actual db instance. Not sure if we can achieve this through ACK framework. 

probably customer can set status of db instance instead of spec ? then ACK can call this reboot api ? 
Similar thing i can think of like failover api of a maz instance or multi-az cluster. 

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by A-Hilaly** [comment]
I don't think ACK should deal with the data plane for any service even thought it sounds simple and straightforward to implement (and i don't believe it's the case here).
I just can't imagine having to deal with EC2 boot/reboot operations, manage s3 objects, dynamodb table raws etc... unless if we want to create a new set of controller that will exclusively deal with the data plane (and complete the existing controllers)

> probably customer can set status of db instance instead of spec ? then ACK can call this reboot api ?

I always think about `Status` as the field users should never modify manually with - and most of the kubernetes controllers respect this pattern so it can a little bit not intuitive to expect users to modify the status manually.

Spec/Status conventions: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
