### ISSUE TITLE
[emr-containers] add tutorial for getting started with ACK service controller for EMR on EKS

### ISSUE THREAD

**Issue by dalbhanj** [aws-controllers-k8s/community#1452]
This will be new tutorial for getting started with ACK service controller for EMR on EKS
Related Issue: https://github.com/aws-controllers-k8s/community/issues/1267

We are announcing **developer preview** for ACK service controller for EMR on EKS. This tutorial would walk the customers through how to create EMR on EKS controller and run Spark Jobs

**Comment by Swalloow** [comment]
Hi @dalbhanj, Thanks for the awesome work!
We planning to use a streaming application at EMR on EKS.
Are there any options like `failureRetries`, `retryInterval` available? (in spark-on-k8s-operator)

**Comment by dalbhanj** [comment]
Hi @Swalloow, we have plans to make emr on eks controller more robust by adding features like job retries and add additional customization. Can you please create new Github issue for this? Please tag it `'[emr-containers]'`in title so that we can drive this discussion and track it. Thank you!

**Comment by dalbhanj** [comment]
Closing this issue since the tutorial is merged

**Comment by Swalloow** [comment]
Hi @dalbhanj, I create GitHub issue here. https://github.com/aws-controllers-k8s/community/issues/1489
Thanks
