### ISSUE TITLE
[emr-containers] add recommended controller IAM policy to recommended-inline-policy

### ISSUE THREAD

**Issue by dalbhanj** [aws-controllers-k8s/community#1468]
**Is your feature request related to a problem?**
Not really a problem but the feature will simplify getting started experience. 

**Describe the solution you'd like**
Add recommended IAM policy to https://github.com/aws-controllers-k8s/emrcontainers-controller/blob/main/config/iam/recommended-inline-policy and reference in getting started tutorial
This is referenced in this PR: https://github.com/aws-controllers-k8s/community/pull/1453

**Describe alternatives you've considered**
Currently alternative is to have recommended IAM policy in getting started tutorial

**Comment by RedbackThomson** [comment]
We consider this a blocker for GA, since the recommended policy files are used in the installation instructions
