### ISSUE TITLE
Add REST API Gateway support

### ISSUE THREAD

**Issue by CorreyS** [aws-controllers-k8s/community#1469]
**Is your feature request related to a problem?**
Add REST API Gateway to API Gateway V2

**Describe the solution you'd like**
Ability to configure a REST API gateway instead of only HTTP.

**Comment by A-Hilaly** [comment]
Hi @CorreyS , not an `apigatewayv2` expert here, but trying to understand what's not support in the current `apigatewayv2-controller`. Is https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/apis/v1alpha1/api.go#L23-L58 not enough to create "REST" API Gateway? Do you have examples on how to create one using API Calls, CDK or CF?
