### ISSUE TITLE
S3 Endpoint Configuration

### ISSUE THREAD

**Issue by vardhanv** [aws-controllers-k8s/community#1495]
**Is your feature request related to a problem?**
I want to use the AWS S3 operator with an onperm S3 storage, and need to be able to configure the S3 endpoint, but the S3 configuration spec does not allow an S3 endpoint to be created.

**Describe the solution you'd like**
Add a configuration to allow an S3 endpoint that is not AWS

**Describe alternatives you've considered**
No alternatives

**Comment by A-Hilaly** [comment]
Hi @vardhanv you can set a service endpoint by passing the `--aws-endpoint-url` flag. If you're deploying your controller using helm, you can set this value https://github.com/aws-controllers-k8s/s3-controller/blob/main/helm/values.yaml#L52
