### ISSUE TITLE
Custom Endpoint not used during initial Account fetch

### ISSUE THREAD

**Issue by redradrat** [aws-controllers-k8s/community#1498]
**Describe the bug**
The initial account id check does not take into account a customized session config.

https://github.com/aws-controllers-k8s/runtime/blob/ae946aa1e0dd309db0064c2c347b724074725c60/pkg/config/config.go#L165-L167

Specifically the session creation here, without taking into account a custom awscfg is the issue:
https://github.com/aws-controllers-k8s/runtime/blob/ae946aa1e0dd309db0064c2c347b724074725c60/pkg/config/config.go#L149-L154

**Steps to reproduce**
Point the controller to a custom endpoint `AWS_ENDPOINT_URL`.

**Expected outcome**
The initial check should also take into account custom configured endpoint or other config.

**Environment**
Testing, Localstack(?)

* Kubernetes version
* Using EKS (yes/no), if so version? No
* AWS service targeted (S3, RDS, etc.) *

**Comment by RedbackThomson** [comment]
Closing since we have merged https://github.com/aws-controllers-k8s/runtime/pull/104
