### ISSUE TITLE
Document `generator.yaml` schema

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1502]
Bootstrapping a new controller which requires customization via `generator.yaml`, e.g. to override methods, is not clearly documented. Slack discussion: https://kubernetes.slack.com/archives/C0402D8JJS1/p1665057847630139

**What is the URL of the document?**

Perhaps should go here (https://aws-controllers-k8s.github.io/community/docs/contributor-docs/building-controller/) or a new page where we describe the full schema.

**Which section(s) is the issue in?**

n/a

**What needs fixing?**

Document the schema of `generator.yaml` and provide some examples.

**Additional context**

**Comment by A-Hilaly** [comment]
++ to document `generator.yaml`.

Adding two points here:
- We're having in mind the project of reworking all the configuration model so perhaps let's target this once sure about the design of next version. (#1184 and #1185)
- We could also start by generating some basic documentation by parsing the Go code comments :)

**Comment by embano1** [comment]
Yeah, there's certainly multiple levels of how to doc the `generator.yaml` structure. MVP IMHO would be to list all available fields/structs and give a short explanation of required/optional and use case.

**Comment by a-hilaly** [comment]
Thanks to Jay and John, we have it documented here https://aws-controllers-k8s.github.io/community/docs/contributor-docs/code-generator-config/
/close
