### ISSUE TITLE
Missing recommended-inline-policy

### ISSUE THREAD

**Issue by knguyenst** [aws-controllers-k8s/community#1510]
Per documentation at https://aws-controllers-k8s.github.io/community/docs/user-docs/irsa/  - the following file is missing from the repo:

https://raw.githubusercontent.com/aws-controllers-k8s/kms-controller/main/config/iam/recommended-inline-policy

```
SERVICE=kms
BASE_URL=https://raw.githubusercontent.com/aws-controllers-k8s/${SERVICE}-controller/main
POLICY_ARN_URL=${BASE_URL}/config/iam/recommended-policy-arn
POLICY_ARN_STRINGS="$(wget -qO- ${POLICY_ARN_URL})"

INLINE_POLICY_URL=${BASE_URL}/config/iam/recommended-inline-policy
INLINE_POLICY="$(wget -qO- ${INLINE_POLICY_URL})"

```

Thus INLINE_POLICY is empty - what is the recommended inline policy - anyone?

**Comment by A-Hilaly** [comment]
Hi @knguyenst for kms-controller we have [recommended-policy-arn](https://github.com/aws-controllers-k8s/kms-controller/blob/main/config/iam/recommended-policy-arn) :)

**Comment by mcanevet** [comment]
Maybe https://github.com/aws-controllers-k8s/kms-controller/blob/main/config/iam/recommended-policy-arn?

**Comment by knguyenst** [comment]
I'm good with it.  Was just wondering if the recommended policy is different than the one that is managed.

Special thanks
