### ISSUE TITLE
Goroutine leak in `aws-sdk-go` library

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1512]
@embano1 brought to our attention this issue that reported a goroutine leak in the `aws-sdk-go` library see https://github.com/aws/aws-sdk-go/issues/3606. It looks like the bug was fixed in `aws-sdk-go-v2` but no the v1 library. We need to bring this in our next community meeting 10-20-22.
/cc @aws-controllers-k8s/runtime-maintainer

**Comment by jljaco** [comment]
We don't think that we have a codepath where we have yet seen this happen.  Setting this to a long-term priority

**Comment by a-hilaly** [comment]
we're moving to aws-sdk-go v2 - closing as this is no longer relevant
/close
