### ISSUE TITLE
[doc] API Reference rds DBInstance spec vpcSecurityGroupRefs is array

### ISSUE THREAD

**Issue by csantanapr** [aws-controllers-k8s/community#1524]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/reference/rds/v1alpha1/dbinstance/

**Which section(s) is the issue in?**

DBInstance spec

**What needs fixing?**

The field `vpcSecurityGroupRefs` and is missing the `-` to indicate is an array
![image](https://user-images.githubusercontent.com/1094878/199247418-9068807e-8377-4944-b861-89475fd5b35e.png)

**Comment by csantanapr** [comment]
I was trying to find where is this content in the doc repo but I was not able to find it, if you let me know I can submit a PR

**Comment by A-Hilaly** [comment]
The documentation is released in: https://github.com/aws-controllers-k8s/community/tree/gh-pages by `community-docs-release` prow job, that executes at somepoint [gen_references.py](https://github.com/aws-controllers-k8s/community/blob/main/docs/scripts/gen_reference.py) (which uses a jinja template here https://github.com/aws-controllers-k8s/community/blob/main/docs/scripts/templates/resource.jinja2)
