### ISSUE TITLE
[doc] Table of spec field description is malformed

### ISSUE THREAD

**Issue by csantanapr** [aws-controllers-k8s/community#1525]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/reference/rds/v1alpha1/dbinstance/

**Which section(s) is the issue in?**

Table of field descriptions for DBInstance, starting at `processorFeatures.[]`

**What needs fixing?**

table is corrupted starting from this point

**Additional context**

![image](https://user-images.githubusercontent.com/1094878/199248355-0ec5d6e3-e5be-4eee-a3e8-516e0de36f77.png)

Let me know where is this content is located in the git repo and I can submit a PR

**Comment by A-Hilaly** [comment]
Good catch! thank you @csantanapr.
Looks like the rendered HTML is broken at the `processorFeatures.[]` and `dbParameterGroups.[]` fields. A good starting point i would be to try to understand if what is the component responsible for this issue.
- [`community-docs-release`](https://prow.ack.aws.dev/?job=community-docs-release) is the prow job publishing the docs 
- We use [`docs-2.json`](https://github.com/aws/aws-sdk-go/blob/main/models/apis/rds/2014-10-31/docs-2.json#L3211) from aws-sdk-go to parse field and resource documentation
- Rendered html: https://github.com/aws-controllers-k8s/community/blob/gh-pages/reference/rds/v1alpha1/dbinstance/index.html#L343

**Comment by RedbackThomson** [comment]
> - We use [docs-2.json](https://github.com/aws/aws-sdk-go/blob/main/models/apis/rds/2014-10-31/docs-2.json#L3211) from aws-sdk-go to parse field and resource documentation
