### ISSUE TITLE
Multi-AZ DB cluster parameter?

### ISSUE THREAD

**Issue by tirelibirefe** [aws-controllers-k8s/community#1531]
Hello,
I don't know ACK RDS Controller supports Multi-AZ DB cluster or not. It looks like ACK pretends support multi-AZ DB cluster but I couldn't have found any installation parameters. I would like to install a multi-AZ DB cluster but have been looking for the necessary parameter in documentation. It would be nice if you can put cpl of sentence explain this.

Thanks & Regars

**Comment by A-Hilaly** [comment]
Hi @tirelibirefe currently Multi-Az DB Cluster is not supported due to https://github.com/aws-controllers-k8s/community/issues/1376 - please subscribe to this issue to know get notified when the bug is fixed.

**Comment by adm-mkarakas** [comment]
Hello again,
If I install single-zone DBCluster by using ACK, will I be able to convert to multi-AZ DBCluster later after the [problem ](https://github.com/aws-controllers-k8s/community/issues/1376)is fixed ?

Thanks & Regards

**Comment by tirelibirefe** [comment]
Hello again,
If I install single-zone DBCluster by using ACK, will I be able to convert to multi-AZ DBCluster later after the problem is fixed ?

Thanks & Regards
