### ISSUE TITLE
Bundled Controller Manager

### ISSUE THREAD

**Issue by nstogner** [aws-controllers-k8s/community#1534]
**Is your feature request related to a problem?**

Installing a controller per AWS service is tedious and resource inefficient.

**Describe the solution you'd like**

Support an additional controller that bundles all service controllers into a single binary. This would allow for efficiency gains similar to the core kubernetes controller manager which shares caches, etc.

**Describe alternatives you've considered**

A bundled set of yamls/helm charts would fix the tedious part but not the efficiency part.

**Comment by RedbackThomson** [comment]
I don't think we'll ever ship all of the controllers as a single binary, because it would change our permissions model. We like that each controller is managed under a separate service account and typically those are given permissions by separate IAM roles. Managing all controllers in a single pod would require a pod with essentially sudo AWS access.

However installing multiple controllers is an understandably tedious task and hence I have previously proposed a unified Helm chart - https://github.com/aws-controllers-k8s/community/issues/1360

**Comment by jaypipes** [comment]
> I am not sure I see how keeping the controllers separate improves the security posture of the system as a whole. What types of attack vectors would compromise controller A but not controller B within the ACK system?

The IAM Role associated with the Service Account running a bundled controller would essentially need super-user privileges across all services... a God role. By having separate controllers, operators can limit the IAM Role associated with the service account to just a single AWS service.

**Comment by nstogner** [comment]
‘ By having separate controllers, operators can limit the IAM Role associated with the service account to just a single AWS service.’

A bundled controller would still allow for this. A user could configure the controller to run for N number of services. They could then provision a role with access to those services only. This approach would not prohibit operators from running 1:1 controller-to-service. However this approach would allow for an option to simplify the deployment of ACK and reduce the control plane resource footprint.

**Comment by nstogner** [comment]
The kubernetes control plane itself utilizes the bundled approach (i.e. the controller manager). Breaking the controller manager apart into individual binaries per type of controlled resource would greatly increase complexity and resource consumption.

Other examples: Google Config Connector, Crossplane Providers

**Comment by jrake-revelant** [comment]
For our current use cases we started with ACK (coming from Crossplane) and the current permission model is a big plus. If you compromise one controller you can only do limited damage, if you would bundle the permissions that would create a larger attack surface.
We found automating the installation and upgrade path, with integration tests in place, the complexity is manageable.

**Comment by nstogner** [comment]
Hi @jrake-revelant, thanks for adding your experience. I am having a hard time coming up with an example of an attack that is able to compromise one controller but not the rest. Do you have one in mind?

**Comment by a-hilaly** [comment]
As discussed here and in https://github.com/aws-controllers-k8s/community/issues/25 - and for security reasons - ACK controllers won't be shipped as a single binary/one controller.
