### ISSUE TITLE
Create multiple Database in Postgres RDS

### ISSUE THREAD

**Issue by pankajingarud** [aws-controllers-k8s/community#1537]
**Is your feature request related to a problem?**
We were trying to create multiple database through ACK for our product.But there is no such feature we can use for now.

**Describe the solution you'd like**
Currently dbName attribute is there through which we can create single database but Postgres has the ability to create multiple database and there is no attribute to add those directly. Can we have a similar Attribute with which we can create multiple database in postgres RDS directly in yaml.

**Describe alternatives you've considered**
For now it is the manual process is there by connecting through AWS console or with RDS using username or password. But we want a end to end product which can be delivered without any manual intervention.

**Comment by a-hilaly** [comment]
ACK resources are a reflection of a single and unique resource in AWS. This sounds more like a need for an L2 layer for duplicating resources in kubernetes.
