### ISSUE TITLE
[s3-controller] Improve description for id and status field of the bucket lifecycle spec

### ISSUE THREAD

**Issue by AljoschaP** [aws-controllers-k8s/community#1540]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/reference/s3/v1alpha1/bucket/#spec

**Which section(s) is the issue in?**

- lifecycle.rules.[].status
- lifecycle.rules.[].id

**What needs fixing?**

- lifecycle.rules.[].status
This field is described as optional but in fact its mandatory and needs to be set to `Enabled` or `Disabled.` As a user I would like to know thats its a mandatory field and that I need to set it to `Enabled` if I want the rule to be considered.

Possible description:
```
Whether the rule is active or inactive. Must be set to Enabled or Disabled.
```

- lifecycle.rules.[].id
Its not clear that the id is the name of the rule inside the AWS console and that its auto-generated if I omit it. 

Possible description:
```
Optional unique identifier of the rule.
Must be a value no longer than 255 characters.
If you don't provide one, Amazon S3 will assign an ID.
```

**Additional context**

I tried to create a PR (https://github.com/aws-controllers-k8s/s3-controller/pull/88) but missed the auto-generation. @jaypipes was so kind to explain it to me and here is the corresponding issue :-)

**Comment by RedbackThomson** [comment]
With the release of the custom documentation configuration, this should be simple to add: https://github.com/aws-controllers-k8s/code-generator/pull/447
