### ISSUE TITLE
Add support for SourceSecurityGroupName and SourceSecurityGroupId in Ingress in EC2 SecurityGroup kind

### ISSUE THREAD

**Issue by sudohikumar** [aws-controllers-k8s/community#1544]
**Is your feature request related to a problem?**
As I understand from `AuthorizeSecurityGroupIngress` API, there is a request parameter `GroupName` and `GroupId ` which defines the name of the security group and ID of the security group respectively. This should also be present in ACK Controller in my opinion. 
Right now, in Ingress, it takes an array of `IPPermission` object. 
Cloudformation [reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html#aws-properties-ec2-security-group-rule-1-syntax).
Notice `SourceSecurityGroupName` and `SourceSecurityGroupId` in parameters. 

**Describe the solution you'd like**
I guess we need to add extra field in `generator.yaml`,`SecurityGroup` resource. 

**Describe alternatives you've considered**
None

**Comment by sudohikumar** [comment]
Is there any update on this? We are looking to implement this asap.

**Comment by jaypipes** [comment]
@LikithaVemulapalli can you look into this one?

**Comment by LikithaVemulapalli** [comment]
Hello @sudohikumar, currently `Egress` doesn't support `SourceSecurityGroupName` and `SourceSecurityGroupId`, we want both Ingress and Egress Rules to be aligned for our `SecurityGroup` resource, we will implement this feature if `Egress` supports these two fields in future. There is another issue where you can find the detailed information on the current functionality of Ingress and Egress Rules https://github.com/aws-controllers-k8s/community/issues/1511

**Comment by LikithaVemulapalli** [comment]
> Thanks @LikithaVemulapalli . So just to confirm, we can do so currently using the following?
> 
> ```
> apiVersion: ec2.services.k8s.aws/v1alpha1
> kind: SecurityGroup
> metadata:
>   name: tutorial-security-group
> spec:
>   description: "ack security group"
>   name: tutorial-sg
>   vpcID: <VPC-ID>
>   ingressRules:
>     -ipProtocol: <IP_PROTOCOL>
>       fromPort: <FROM_PORT>
>       toPort: <TO_PORT>
>       userIDGroupPairs:
>       - groupID: <SecurityGroup-ID>
> ```

Yes, you can achieve the same thing using `UserIDGroupPairs`
