### ISSUE TITLE
Route53 Operator - HostedZone spec should have tags support in Spec

### ISSUE THREAD

**Issue by sudohikumar** [aws-controllers-k8s/community#1554]
**Is your feature request related to a problem?**
As per the [API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html#API_CreateHostedZone_RequestBody), we don't have this support. But, there is an additional [API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeTagsForResource.html) which does this. 
Probably, we should have this as part of CreateHostedZone API via ACK controller itself. 

**Describe the solution you'd like**
Add support for Tags in HostedZone. It's a good to have feature and provides visibility on resources. 

**Describe alternatives you've considered**
N/A

**Comment by sudohikumar** [comment]
Hello 👋🏻 ,
Is there any update on this? We are looking to implement this asap.

**Comment by nnbu** [comment]
I will implement this in the next week

**Comment by nnbu** [comment]
The change is merged https://github.com/aws-controllers-k8s/route53-controller/pull/26
