### ISSUE TITLE
Add Network ACL support to the EC2 Controller

### ISSUE THREAD

**Issue by p3nda** [aws-controllers-k8s/community#1559]
**Is your feature request related to a problem?**
The EC2 ACK Controller does not have the Network ACL API resource. 

API reference: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkAcl.html

**Describe the solution you'd like**
I would like to be able to create Network ACLs through the EC2 Controller. For example, I can create Security Groups through the EC2 controller - https://aws-controllers-k8s.github.io/community/reference/ec2/v1alpha1/securitygroup/ - the intention would be to create nACLs in the same manner.

**Describe alternatives you've considered**
This can be created through other IaC for example CloudFormation or Terraform. The ultimate goal is to keep everything cohesive avoid working with multiple solutions.

**Comment by LikithaVemulapalli** [comment]
Hello @p3nda, thanks for opening the issue, as we discussed offline regarding the approach, let me know if you need any further help with the implementation. Thank you :)
