### ISSUE TITLE
ENI for AWS CNI

### ISSUE THREAD

**Issue by elasticdotventures** [aws-controllers-k8s/community#1564]
**Is your feature request related to a problem?**

We are attempting to migrate portions of our infrastructure to EKS.    Specifically one requirement - IPSEC VPN. 

Our application must communicate with external trading partners over a IPSEC VPN to a fixed address. 
This requires we reserving an IPv4 Elastic IP, then mapping it to an ENI and then attaching that ENI to a container (inside K8s/EKS)

**Describe the solution you'd like**
I'd like to be able to use a K8s CNI to link a network interface + elastic IP to a pod service definition. 

**Describe alternatives you've considered**
Alternative CNI's including Multus CNI
https://github.com/k8snetworkplumbingwg/multus-cni

How to setup an IPSEC VPN server in k8s using Helm:
https://github.com/taskmedia/helm_ipsec-vpn-server

(Also looked at Cilium, other CNI's searching for a solution other than AWS-VPC CNI)

Asked in K8s Network Plumbling Working Group:
https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit

I've contacted AWS Support related to this request but they've suggested this is not possible inside EKS and to deploy the system and software inside a standalone EC2.
We are hoping to deploy our internal systems using a K8s native CD process and having to manage & secure external configurations is seen as undesirable.

**Comment by A-Hilaly** [comment]
Hi @elasticdotventures this org/repo are dedicated to ACK project. You'll have a better chance asking in https://kubernetes.slack.com/archives/C0LRMHZ1T
/close
