### ISSUE TITLE
Leader election mode not functioning as expected

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1578]
Looks like there is a bug in the controller when it is run in [leader election mode](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/config/config.go#L34). This bug is causing the controllers to fight over resources, which is causing an undesirable behavior. It is suggested that this issue be addressed at some point, but it is not considered urgent.

**Comment by jljaco** [comment]
@jaypipes @A-Hilaly Nick and I were not even aware that we had leader election functionality.  Can we possibly document what is implemented already so that we can more accurately assess the impact of this bug?

**Comment by jaypipes** [comment]
> @jaypipes @A-Hilaly Nick and I were not even aware that we had leader election functionality. Can we possibly document what is implemented already so that we can more accurately assess the impact of this bug?

Sure thing!

Here's the full documentation of our leader election support:

""

**Comment by jaypipes** [comment]
In all seriousness, we don't have any docs because the [leader election options](https://github.com/aws-controllers-k8s/code-generator/blob/c3fefc1cc5cb030c5e893027ba1195d747889aca/templates/cmd/controller/main.go.tpl#L87-L88) come from KubeBuilder/k8s-controller-runtime and we don't modify or use them at all.

**Comment by RedbackThomson** [comment]
Have we ever validated that it works? Is it supposed to work? Is it worth us stripping it out?

**Comment by jaypipes** [comment]
> Have we ever validated that it works?

Nope.

> Is it supposed to work?

Maybe?

> Is it worth us stripping it out?

I don't think it's worth it, no. On the off chance it works properly as-is, no reason to remove it IMHO :)
