### ISSUE TITLE
Prow: auto-generation of controllers following `code-generator` releases should validate e2e tests passing

### ISSUE THREAD

**Issue by jljaco** [aws-controllers-k8s/community#1589]
**Is your feature request related to a problem?**
When auto-generating controllers following a release of `code-generator`, some of the PRs that are created as part of the process end up failing e2e tests even though the code generation step completes successfully.

**Describe the solution you'd like**
When prow starts auto-generation of all controllers, the pass/fail for each controller should take into account not JUST whether code generation succeeds for the controller, but ALSO whether the e2e tests associated with the subsequent PR pass or fail.  This status should be reported back upstream in the Prow dashboard for review by the release manager.

**Describe alternatives you've considered**
Checking on every PR manually to verify whether its tests pass or fail.

**Comment by a-hilaly** [comment]
Now that we have 40+ controller, running all the e2e tests before generating the PRs isn't really optimal.. +PRs will always run e2e now matter what. 

Closing for now, we can re-open if needed.
/close
