### ISSUE TITLE
Creating Lamba function from an image stored in a different account ECR

### ISSUE THREAD

**Issue by pedronieto1206** [aws-controllers-k8s/community#1590]
**Is your feature request related to a problem?**
I am running different k8s environments on eks using one central ECR as repository for images. This approach has been succesful deploying applications granting accounts using "AWS Account IDs" option in the ECR. This way I can use deployments to handle images without using the docker login and only trusting on EKR to get the images. 
My problem was trying to use the same approach for Lambda function, I can publish images into the ECR but this images are not available in the Lambda UI either using the lambda operator.

<img width="1220" alt="Screenshot 2022-12-09 at 18 03 08" src="https://user-images.githubusercontent.com/116560186/206753709-551a69d8-9d79-41d6-888d-924b561ae436.png">

The result I get is the following:

  conditions:
    - message: "AccessDeniedException: \n\tstatus code: 403, request id: XXXXX"
      status: 'True'
      type: ACK.Recoverable
    - lastTransitionTime: '2022-12-09T17:05:35Z'
      message: >-

My expected result would be, be able to use this yaml:

apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: ecrlambda
  annotations:
    services.k8s.aws/region: eu-central-1
spec:
  name: ecrlambda
  packageType: Image
  code:
    imageURI: XXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/lambdaimage:latest
  role: arn:aws:iam::YYYYYY:role/lambda-controller
  description: function created

**Describe the solution you'd like**
My goal would be to be able to create functions from an ECR in the same account or with another one in a "federated" account as shown before.

**Describe alternatives you've considered**
The alternatives I have considered:

- Abandon Container and move to S3: Do not want to deploy code without container
- Create a Job that copies images from ECR Central to the secondary one: Double containers... delay...
- Include pullsecrets in the yaml but this would require a programatic user in the central repository which now is not needed from deployment side.

**Comment by A-Hilaly** [comment]
Hi @pedronieto1206, i don't think this is an ACK-specific issue. If you want to use ECR images from a different AWS account that you use to create Lambda functions, you must enable cross-account ECR access for lambda. Here is an example on how to do that: https://aws.amazon.com/blogs/compute/introducing-cross-account-amazon-ecr-access-for-aws-lambda/

**Comment by pedronieto1206** [comment]
Thanks @A-Hilaly  but even with that done, I am able to pull images from 
a deployment object:

      containers:
        - name: service
          image: XXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/image:latest
          imagePullPolicy: Always

But this approach does not work with lambdas. As I pointed out they do not even appear in the UI option of creating a lambda from an image either.

**Comment by A-Hilaly** [comment]
Hi @pedronieto1206 , i'm trying to understand whether this is an ACK issue or an IAM configuration issue. Can you please try to create the same lambda function using the AWS CLI?

I suspect that the case of Deployment is different from the lambda one since this is a "service" that needs to pull the image:
The ECR policy needs to have:
```
Principal:
              Service: lambda.amazonaws.com
```

**Comment by A-Hilaly** [comment]
Hey @pedronieto1206 any update on this?
