### ISSUE TITLE
ECS service controller

### ISSUE THREAD

**Issue by mikestef9** [aws-controllers-k8s/community#1592]
## New ACK Service Controller

Support for Amazon ECS

### List of API resources

List the API resources in order of importance to you:

1) CapacityProvider
2) Cluster
3) Service
4) Task Set

### More details
May seem like an unusual request at first, but many organizations are standardizing on the Kubernetes API as the model for provisioning and managing resources, and ECS is one such service they may be using.

**Comment by gitbluf** [comment]
Hello, wanted to know what is the status of this and can it be expected anytime soon ?

**Comment by a-hilaly** [comment]
@mreferre and I have worked on a ACK ECS/ELBv2 prototype last year. I will refine the code and start shipping PRs very soon - stay tuned :) @gitbluf

**Comment by mreferre** [comment]
Way to go Amine... I am glad if this prototype get to see the light!
