### ISSUE TITLE
Allow `SetResourceForStruct` to be called for non top-level CRD fields

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1609]
Currently we are unable to use `GoCodeSetResourceForStruct` for fields that are not top-level CRD fields, which causes issues when trying to generate custom code that transforms an eventbridge `v1alpha1.Target` to an `svcsdk.Target`.

Ideally we should allow users to call `GoCodeSetResourceForStruct` for any field, not just CRD top level fields. This will fix the issue and allow users to generate custom code for fields that are not part of a CRD spec or status.

**Comment by jaypipes** [comment]
@A-Hilaly when you write "fields that are not part of a CRD spec or status", are you referring to fields that are not *top-level* fields in the Spec/Status? Because I don't see a reason to use `SetResourceForStruct` for fields that aren't part of a CRD...

**Comment by A-Hilaly** [comment]
@jaypipes Yes i'm referring to non top-level CRD Fields. Changing the description and title
