### ISSUE TITLE
Upgrade Golang version to 1.18/1.19 in code-generator/Dockerfile

### ISSUE THREAD

**Issue by ShacharMalachi** [aws-controllers-k8s/community#1634]
Hi,

**Background**
When you release an ack-controller version, you use Golang version 1.17.X, as I can see here: https://github.com/aws-controllers-k8s/code-generator/blob/c6651c200ba136e5c7f50ad8be751fae060a38e6/Dockerfile#L6

**Issue/Problem**
As far as I understand, Golang will not release new minor versions for 1.17 anymore, after 1.19 was released, according to their release policy: https://go.dev/doc/devel/release#policy
You can see here the latest 1.17.X minor version was released in August 2022, it's almost half a year ago: https://go.dev/doc/devel/release#go1.17

I guess that potentially you can miss some bug fixes or security fixes by not upgrading to a newer Golang version.

**Suggestion**
My suggestion is to upgrade to Golang 1.18 or 1.19, if it's possible and if it does not require a major effort.

Of course it's your decision to make, and I'm just suggesting it as a developer that uses your controllers.

Thanks,
Shachar.

**Comment by RedbackThomson** [comment]
We have an ongoing PR that upgrades each of the required Go versions to 1.19. You can track it here https://github.com/aws-controllers-k8s/code-generator/pull/358

**Comment by ShacharMalachi** [comment]
Hi @RedbackThomson,

Thanks! I didn't notice this one, I will track it.

**Comment by ShacharMalachi** [comment]
I see you released this change in code-generator, so I'm closing this issue.
