### ISSUE TITLE
Sagemaker: support serverless inference

### ISSUE THREAD

**Issue by AlmogBaku** [aws-controllers-k8s/community#1636]
Currently, Sagemaker controller doesn't expose a way to configure serverless inference.

Please add it :)

**Comment by surajkota** [comment]
Hi @AlmogBaku, we are working on it and the feature has been merged - https://github.com/aws-controllers-k8s/sagemaker-controller/pull/193. We will update the issue once we cut a release

Thanks for the patience

**Comment by surajkota** [comment]
Do let us know if you have any timelines on when you would like to use this feature

**Comment by ananth102** [comment]
Hi @AlmogBaku we have released this feature as part of v0.6.0 of the Sagemaker Controller.
