### ISSUE TITLE
Fix API Reference metadata bugs

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1637]
**Describe the bug**
Some of the service names in the index of the API reference have incorrect casing or are missing altogether - https://aws-controllers-k8s.github.io/community/reference/

These service names should be fixed, and there should a basic test for the existence and format linting of the metadata before merging a PR.

**Expected outcome**
All services should have properly cased service names that match the name of the controller

**Comment by jaypipes** [comment]
@RedbackThomson is this a matter of the new ACM and Organizations controller repos not having proper metadata.yaml files or something like that?

**Comment by RedbackThomson** [comment]
> @RedbackThomson is this a matter of the new ACM and Organizations controller repos not having proper metadata.yaml files or something like that?

Correct

**Comment by RedbackThomson** [comment]
Re-opening this because I realised `AMP` is above `RDS` in the table of contents, because its service name is actually `prometheusservice` under the hood - messing with the ordering
