### ISSUE TITLE
code generator returns Error: cannot clone repository: context deadline exceeded

### ISSUE THREAD

**Issue by Julian-Chu** [aws-controllers-k8s/community#1642]
**Describe the bug**
follow the documentation to build controller,  always return `Error: cannot clone repository: context deadline exceeded`

**Steps to reproduce**
```shell
➜  code-generator git:(main) make build-controller SERVICE=ecr
building ack-generate ... ok.
==== building ecr-controller ====
Copying common custom resource definitions into ecr
Building Kubernetes API objects for ecr
Error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1
```

**Expected outcome**
build is successful.

**Environment**
macOS Ventura

**root cause**
- code generator has to clone aws-sdk-go to generate K8s API objs for first time
- default timeout is 180s(3mins)
- regarding to network speed, the clone process can take longer than 3mins( 8 - 15mins with my network)
```shell
➜  src time git clone https://github.com/aws/aws-sdk-go aws-sdk-go-1
Cloning into 'aws-sdk-go-1'...
remote: Enumerating objects: 110265, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 110265 (delta 108), reused 244 (delta 101), pack-reused 109985
Receiving objects: 100% (110265/110265), 293.78 MiB | 404.00 KiB/s, done.
Resolving deltas: 100% (70397/70397), done.
git clone https://github.com/aws/aws-sdk-go aws-sdk-go-1  32.86s user 19.08s system 6% cpu 12:31.19 total
```

will submit a PR to remind user to do manual clone if timeout error

**Comment by A-Hilaly** [comment]
Thank you Julian !
/assign @Julian-Chu

**Comment by Julian-Chu** [comment]
closed by https://github.com/aws-controllers-k8s/code-generator/pull/395
