### ISSUE TITLE
Resource validation for `--reconcile-resource-resync-seconds` arguments

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1647]
As discussed in https://github.com/aws-controllers-k8s/runtime/pull/106#discussion_r1082689001 - we should make code-generator changes to be able to validate the resource names provided by ACK users.

**Comment by jljaco** [comment]
This is a direct follow-up to https://github.com/aws-controllers-k8s/community/issues/1367
