### ISSUE TITLE
Changing dbInstanceClass causes controller to thrash between new and old values

### ISSUE THREAD

**Issue by cogren1** [aws-controllers-k8s/community#1650]
**Describe the bug**
Changing dbInstanceClass on a DBInstance objects causes the controller to change the database in RDS to the new value as expected. As soon as the value changes though, it tries to update the manifest to the old value. Once the database is "available", this succeeds, and the controller commands RDS to change the instance back to the old class. Then again, once the instance class has changed in RDS, the controller tries to update the manifest back to the original new value of dbInstanceClass. The same occurs with the controller waiting for the database to become "available" before the update succeeds, and the database in RDS is instructed to change its instance class. At this point, the controller stops trying to change the manifest, but leaves it with dbInstanceClass having the original old value and pendingModifiedValues specifying the new value.

**Steps to reproduce**
1. Create a DBInstance manifest, and wait for the controller to create it in RDS.
2. Change the dbInstanceClass value in the manifest to a different valid value. (ex. db.t3.micro to db.t3.small).
3. Watch the controller logs and the database in RDS as it changes from the old class to the new class to the old class to the new class before quieting.
4. Note the manifest has the old value in dbInstanceClass, and status.pendingModfiedValues has `{"dbInstanceClass": <new_value> }`

**Expected outcome**
The controller sends only one command to update the RDS controller from the old class to the new class and once complete, it ensures the manifest specifies the new class for dbInstanceClass and pendingModifiedValues has a value of `{}`.

**Environment**

* Kubernetes version v1.21.13
* Using EKS (yes/no), if so version? No
* AWS service targeted (S3, RDS, etc.) RDS

**Comment by jaypipes** [comment]
@brucegucode can you have a look into this one, maybe create an e2e test case that reproduces please? :)

**Comment by cogren1** [comment]
I'm by no means an expert in the ACK code flow, but after looking around a bit, I have a hypothesis.

An update is made to the manifest by a human or other software, etc.
The controller detects this and bundles the changes into a ModifyDBInstanceWithContext call.
The call returns with the new state of the DB instance. Since class changes don't occur instantly, the old value is returned.
The controller patches the manifest with the values from RDS, including the old dbInstanceClass value.
The controller is happy while RDS is modifying the instance until RDS reports the new instance class value.
The controller picks up this change during its normal polling. It sees the RDS value is different that the value in the manifest, and so it attempts to initiate a modify call to "correct" the discrepancy. This fails until the instance status is back in "available", where it then succeeds, and the cycle starts again.

I'm not sure how this cycle would terminate, which it does at some point. Perhaps there is a timeout somewhere.

**Comment by jaypipes** [comment]
Duplicate of #1773 so closing this one out. Yes, I know this one was posted earlier!
