### ISSUE TITLE
List of references are not being generated properly

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1653]
**Describe the bug**
A recent change to the code-generator has introduced a bug whereby it is generating code under the assumption that all references are structs. Formerly it was iterating through the list of references and evaluating them correctly, but now it is trying to access their members. None of the new code-generator output can compile.

For example, in the recent `v0.23.0` auto-generated PR for the `ec2-controller`:
https://github.com/aws-controllers-k8s/ec2-controller/pull/125/files#diff-3bf030d959f0bbfc406565dcff851e040cdc29be0e39df6a4bedb89b18ac0e5aR154-R173

**Steps to reproduce**
Generate the `ec2-controller` using `v0.23.0` and look at the `references.go` file for the `RouteTable` resource. It should contain compilation bugs.

**Expected outcome**
It should not be changed from the previous code-generator output.

**Comment by jljaco** [comment]
Hey @RedbackThomson do you happen to know which `code-generator` PR introduced this bug?
