### ISSUE TITLE
Write e2e tests for drift remediation feature

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1660]
We should have an e2e test that creates an S3 bucket, sets the default period to 3 minutes, changes something on the bucket using boto3, waiting a little bit and then asserting that the bucket changed back

**Comment by A-Hilaly** [comment]
This will require changes to how we run e2e tests.. we'll need to be able to set one of drift remediation flags/helm values before running the tests

**Comment by embano1** [comment]
Would be happy to create one for the E2E framework used in the EventBridge controller :)

**Comment by azpaulp** [comment]
This is blocked on https://github.com/aws-controllers-k8s/community/issues/1359
