### ISSUE TITLE
ACK for EC2 Security Group to support inbound and outbound rules that include a security group not just CIDR

### ISSUE THREAD

**Issue by shancz** [aws-controllers-k8s/community#1661]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

I am using ACK to create a database. However I want to control access to the database via a security group that specifies that only instances that belong to a given security group are permitted. 
For example on the AWS console when creating an inbound rule the options are to select a CIDR block or another security group for the inbound. In ACK only CIDR block can be selected but this is limiting as I might have multiple instances in a given CIDR block that belong to different apps. Using security group would allow for fine grain access same as the AWS console allows it.

**Describe the solution you'd like**
A description of what you want to happen.
Update the ACK EC to also accept a security group for inbound rule not just a CIDR block.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
Currently there is no alternative but to use aws commands but that defeats the purpose of ACK.

**Comment by jljaco** [comment]
This appears to be a duplicate of https://github.com/aws-controllers-k8s/community/issues/1511, closing.
