### ISSUE TITLE
ACK for RDS to support `RestoreDBClusterToPointInTime`

### ISSUE THREAD

**Issue by abatilo** [aws-controllers-k8s/community#1665]
**Is your feature request related to a problem?**
I would like to be able to create DBCluster's from a latest restorable time based on an existing DBCluster.

I'd like to be able to combine the ACK for RDS controller with something like the ArgoCD ApplicationSet controller's PR generator, so that I could create new databases based on the main environment, and then have them be torn down automatically by deleting the custom resource.

**Describe the solution you'd like**
I'd like the ACK for RDS to better support `RestoreDBClusterToPointInTime`

**Comment by jaypipes** [comment]
> My work organization could be open to contributing the work if some initial guidance could be provided?

@abatilo we are always available to help. :) Hop onto the Kubernetes Slack community #aws-controllers-k8s channel. That's the best way to get into design discussions. Myself and @brucegucode can assist you in planning this feature out.

**Comment by RedbackThomson** [comment]
I would also point out a previous PR in the `rds-controller` repository that might be useful as reference: https://github.com/aws-controllers-k8s/rds-controller/pull/101

**Comment by jkatz** [comment]
aws-controllers-k8s/rds-controller#101 lets you restore a [database fully from snapshot](https://aws-controllers-k8s.github.io/community/docs/tutorials/rds-example/#create-a-database-from-snapshot), but it does not let you select the point-in-time. [Here is a walkthrough on how to do that](https://aws-controllers-k8s.github.io/community/docs/tutorials/rds-example/#create-a-database-from-snapshot).

To go to an exact point-in-time, you would need:

* [`RestoreDBClusterToPointInTime`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBClusterToPointInTime.html) (for Aurora)
* [`RestoreDBInstanceToPointInTime`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceToPointInTime.html) (for all other engines)

There are definitely a bunch of use cases for the above -- I've seen the need for this from Kubernetes and have done similar things myself :smile:

@abatilo For your specific use case, is there a need to restore to a specific point in time or does restoring from the last snapshot work?

**Comment by abatilo** [comment]
For my use case, restoring to latest with specifically Aurora Postgres is all I'm looking to do at the moment @jkatz.

Thank you for the reference PRs. I don't want to say we're committing to anything just yet but those are some great starting points!
