### ISSUE TITLE
Prow jobs depending on Github crendentials failing

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1669]
We tried to ship v0.0.1 of eventbridge-controller today and we found out that 3 prow jobs are not working properly:

- `$SERVICE-controller-olm-bundle-pr`
- `$SERVICE-docs-release`
- `$SERVICE-controller-release-tag`

They all have one shared thing in common: They open PRs/push content to Github

**Comment by A-Hilaly** [comment]
Example logs:
- https://prow.ack.aws.dev/view/s3/ack-prow-logs/logs/eventbridge-controller-olm-bundle-pr/1622999863199272960
- https://prow.ack.aws.dev/view/s3/ack-prow-logs/logs/eventbridge-docs-release/1622999863111192576
- https://prow.ack.aws.dev/view/s3/ack-prow-logs/logs/eventbridge-controller-release-tag/1622988021643087872

**Comment by RedbackThomson** [comment]
Updated the PAT to the latest version and re-run the tests
