### ISSUE TITLE
apigatewayv2-controller. Reconciling error for API Custom Resource

### ISSUE THREAD

**Issue by Khuman2** [aws-controllers-k8s/community#1687]
**Describe the bug**
We tried to use the AWS API gateway with a Private link and private ALB inside our private subnet. Our goal is to manage by API 
 Gateway's route and integrations by _apigatewayv2-controller_
During implementation, we got an error from _apigatewayv2-controller_:
```bash
2023-02-09T14:21:15.337Z	ERROR	controller.api	Reconciler error	{"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "API", "name": "test-api-gateway-http-vpc-links", "namespace": "awesome-namespace", "error": "SerializationError: failed to unmarshal response error\n\tstatus code: 404, request id: \ncaused by: UnmarshalError: error message missing"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2023-02-09T14:26:43.083Z	ERROR	controller.api	Reconciler error	{"reconciler group": "apigatewayv2.services.k8s.aws", "reconciler kind": "API", "name": "test-api-gateway-http-vpc-links", "namespace": "awesome-namespace", "error": "SerializationError: failed to unmarshal response error\n\tstatus code: 404, request id: \ncaused by: UnmarshalError: error message missing"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
```

**Steps to reproduce**
Create HTTP API Gateway in AWS like in the picture:
![Screenshot 2023-02-10 at 11 23 27](https://user-images.githubusercontent.com/30404910/218068614-9bcd2ede-8dc4-4c25-94c0-558cec11169c.png)
Integrations look like this:
![Screenshot 2023-02-10 at 11 28 30](https://user-images.githubusercontent.com/30404910/218069376-6688137a-8574-4600-b96a-0b7f042d984c.png)

Deploy  _apigatewayv2-controller_ v1.0.0 by the helm with values:
```yaml
deployment:
  aws:
    region: "eu-central-1"
```
Apply manifests:
```yaml
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "test-api-gateway-http-vpc-links"
  namespace: awesome-namespace
spec:
  name: "test-api-gateway-http-vpc-links"
  protocolType: HTTP
```

**Expected outcome**
I can't imagine the outcome, to be honest. But error, I guess isn't the positive result ;)

**Environment**

* Kubernetes version: v1.22.16-eks-ffeb93d
* EKS version: 1.22
* AWS service targeted: HTTP API Gateway, ALB

**Comment by jaypipes** [comment]
@Khuman2 It looks like you pre-created the API using the AWS Console for API Gateway v2, yes? If that is the case, and you want to have ACK take over the management of that API, you need to use the `AdoptedResource` functionality. You can read about that here: https://aws-controllers-k8s.github.io/community/docs/user-docs/adopted-resource/

Alternately, you can use the ACK apigatewayv2-controller to create API Gateways (and Routes, Integrations, etc) entirely from scratch using YAML manifests for all of those subobjects. You can read about how to do that in this tutorial: https://aws-controllers-k8s.github.io/community/docs/tutorials/apigatewayv2-reference-example/

I think the bug shown in this particular issue is due to the API already existing in the AWS APIGatewayV2 service and the controller not properly handling the Duplicate key error.

**Comment by A-Hilaly** [comment]
@jaypipes the serialization error is a little bit weird, normally we should throw a `NotManagedError` (resource already exist but is not managed by ACK...)

**Comment by Khuman2** [comment]
@jaypipes, I would like to know the best practice on how to use the apigateway controller. 
Let me share my use case. 
Actually, I need to realize approach that described in the [article](https://aws.amazon.com/blogs/containers/integrate-amazon-api-gateway-with-amazon-eks/)
I manage my infrastructure by terraform. In a private subnet, behind internal ALB my services are located. 
My idea was to create API gateway, and attach certificates from ACM and private VPC link by terraform.
In the service's git I want to store manifest files per service for handling service APIGateway integrations, k8s services, ingresses for ALB etc.
I've tried to use Integration and Route from the operator, but it doesn't find API. 

```
---
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "awesome-service-integration"
  namespace: "service-namespace"
spec:
  apiRef:
    from:
      name: "test-api-gateway-http-vpc-links"
  integrationType: HTTP_PROXY
  integrationURI: "arn:aws:elasticloadbalancing:region:profile_id:listener/my_ALB_internal_listener_path"
  integrationMethod: ANY
  payloadFormatVersion: "1.0"

---
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "awesome-service-route"
  namespace: "service-namespace"
spec:
  apiRef:
    from:
      name: "test-api-gateway-http-vpc-links"
  routeKey: "ANY /ack-route-key"
  targetRef:
    from:
      name: "awesome-service-integration"
```
    
But I got an error: "can't find API" 
So, my question is my use case have chance for been alive, or have I got something wrong?
Thanks for the advice!

**Comment by Khuman2** [comment]
I also tried to adopt my API Gateway by code:
```yaml
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-test-api-gateway-http-vpc-links
spec:  
  aws:
    nameOrID: api_id
  kubernetes:
    group: apigatewayv2.services.k8s.aws
    kind: API
    metadata:
      name: adopt-test-api-gateway-http-vpc-links
      namespace: service-namespace
      labels:
        Name: private-api
  ```
  
and I've got the same error message:
```bash
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2023-02-15T11:33:44.905Z	INFO	adoption.adopted-reconciler	starting adoption reconciliation	{"target_group": "apigatewayv2.services.k8s.aws", "target_kind": "API", "namespace": "service-namespace", "name": "adopt-test-api-gateway-http-vpc-links", "generation": 1}
2023-02-15T11:33:44.947Z	ERROR	controller.adoptedresource	Reconciler error	{"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "name": "adopt-test-api-gateway-http-vpc-links", "namespace": "service-namespace", "error": "SerializationError: failed to unmarshal response error\n\tstatus code: 404, request id: \ncaused by: UnmarshalError: error message missing"}
```

**Comment by Khuman2** [comment]
I've reused `AdoptedResource` for my API Gateway. It works fine.

**Comment by jljaco** [comment]
Resolving this -- please reopen if there are any further concerns.
