### ISSUE TITLE
Migrate kustomize files to new clauses

### ISSUE THREAD

**Issue by james-callahan** [aws-controllers-k8s/community#1690]
**Describe the bug**
The kustomization configuration uses deprecated clauses like `bases`.
Instead you should just use `resources`

**Steps to reproduce**
e.g.
```
$ kustomize  build github.com/aws-controllers-k8s/iam-controller/config/default > /dev/null
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

**Expected outcome**

No deprecation warnings

**Environment**

* `kustomize version`: 5.0.0

**Comment by jljaco** [comment]
TODO this should be `kind/installation`

**Comment by jaypipes** [comment]
@james-callahan Hi! Are you interested in submitting a PR that addresses this issue?

**Comment by james-callahan** [comment]
> @james-callahan Hi! Are you interested in submitting a PR that addresses this issue?

Sent https://github.com/aws-controllers-k8s/code-generator/pull/420

**Comment by james-callahan** [comment]
Merged and code generator has had a release; closing as solved.
