### ISSUE TITLE
EventBridge `Pipes` service controller

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1691]
## New ACK Service Controller

Support for EventBridge [`Pipes`](https://github.com/aws/aws-sdk-go/tree/main/models/apis/pipes/2015-10-07). This is an issue to also discuss whether it should be a separate controller (common approach) or be implemented under the `EventBridge` controller as the use cases, resources and API models are quiet similar. If it's a separate controller, it would be good to reuse the API group `eventbridge.services.k8s.aws`. Is this possible with the current code-gen?

As EventBridge is expanding to become a framework/building blocks for event-driven systems, this question might come up again, for example EventBridge `Scheduler` controller.

### List of API resources

`Pipes`

TODOs:

- [x] Support `Pipes` resource
- [x] Write E2E tests
- [x] Write tutorial
- [x] Add license headers
- [x] Add samples to https://github.com/aws-controllers-k8s/examples

**Comment by A-Hilaly** [comment]
Agreed, what a beautiful and simple API https://docs.aws.amazon.com/eventbridge/latest/pipes-reference/API_Operations.html

**Comment by A-Hilaly** [comment]
`CreatePipe`, `DescribePipe` and `UpdatePipe` have the exact same fields :relieved:

**Comment by embano1** [comment]
🥳 https://aws.amazon.com/about-aws/whats-new/2023/03/ack-controllers-amazon-eventbridge-pipes/
