### ISSUE TITLE
SQS controller crashes after deleting Queue resource

### ISSUE THREAD

**Issue by nielstenboom** [aws-controllers-k8s/community#1696]
**Describe the bug**
The controller crashes with the following error after a Queue is deleted: 

```
2023-02-15T10:12:00.728Z	ERROR	controller.queue	Reconciler error	{"reconciler group": "sqs.services.k8s.aws", "reconciler kind": "Queue", "name": "test-queue", "namespace": "aws-controllers", "error": "AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.\n\tstatus code: 400, request id: 2034229b-b201-5e7e-9971-7efd003117fd"}
```

The SQS resource did get deleted from AWS though

**Steps to reproduce**
Create Queue resource, see it created, then delete it.

**Expected outcome**
The queue would be deleted without errors showing in the logs

**Environment**
v0.0.3

**Comment by embano1** [comment]
Just tried to reproduce with `v0.0.3` (Helm chart), but CREATE/DELETE workflows are working for me:

```console
ack-system sqs-chart-1677069769-654c4b6b7-m5pzl controller 2023-02-22T12:57:03.394Z     INFO    ackrt   created new resource    {"account": "331505801289", "role": "", "region": "eu-central-1", "kind": "Queue", "namespace": "default", "name": "sqs-eu-central-1", "is_adopted": false, "generation": 1}
ack-system sqs-chart-1677069769-654c4b6b7-m5pzl controller 2023-02-22T13:00:39.379Z     INFO    ackrt   deleted resource        {"account": "331505801289", "role": "", "region": "eu-central-1", "kind": "Queue", "namespace": "default", "name": "sqs-eu-central-1", "generation": 2}
```

**Comment by nielstenboom** [comment]
> Just tried to reproduce with v0.0.3 (Helm chart), but CREATE/DELETE workflows are working for me:

That's odd, I tried it twice and kept seeing that error in the logs. It was on Kubernetes v1.21, maybe that makes a difference?

**Comment by nielstenboom** [comment]
I actually ran into https://github.com/aws-controllers-k8s/community/issues/1695 before this, maybe that might have something to do with it?

The redacted version I ended up using is: 

```
apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: test-queue
spec:
  queueName: test-queue
  delaySeconds: "0"
```

**Comment by nielstenboom** [comment]
Btw I saw the discussion in https://github.com/aws-controllers-k8s/community/issues/1707 and want to mention that I was also using ArgoCD when I experienced this issue, is it expected?

**Comment by jljaco** [comment]
@jaypipes could this be a duplicate of what's going on in https://github.com/aws-controllers-k8s/community/issues/1759 ?  If this is a duplicate, would it be acceptable to close this one out in favor of that one?

**Comment by jaypipes** [comment]
@jljaco yeah, I believe this is a duplicate. I think it's OK to close as a dup.

**Comment by jljaco** [comment]
Closing in favor of (duplicate) #1759
