### ISSUE TITLE
Chart versions prefixed with `v` aren't compatible with Flux semver ranges 

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1715]
**Describe the bug**
All of our controller charts are versioned, prefixed with a `v` before the semver. eg. `public.ecr.aws/aws-controllers-k8s/ec2-chart:v1.0.1`

The Flux Helm controller has support for Semver ranges:
> The chart.spec.version can be a fixed semver, or any semver range (i.e. >=4.0.0 <5.0.0). It is ignored for HelmRelease resources that reference a GitRepository or Bucket source.

This support is not compatible with the `v`. Instead, the controller complains that it cannot find any images within that range.

**Steps to reproduce**
Create a Flux `HelmRelease` for one of the ACK OCI Helm charts, and use the `chart.spec.version` with a range (eg.` >=1.0.0 <2.0.0`).

**Expected outcome**
The controller should understand the chart versions and be able to use proper semver ranges and filtering.

**Comment by stefanprodan** [comment]
This is not a Flux issue, we conform with the Helm spec and we use the Helm Go SDK. Helm itself does not support the `v` prefix, charts should be versioned using strict semver format. Using the `v` prefix also breaks the Helm CLI https://github.com/helm/helm/issues/11107.

**Comment by wallrj** [comment]
I regard it as a Helm bug. Helm **does** support the `v` prefix when interacting with non-oci registry. For example, the cert-manager Helm chart has a `v` prefix and `helm install` can calculate the latest semver release just fine.

```
$ helm repo add jetstack https://charts.jetstack.io
$ helm repo update jetstack
```

```
$ helm search repo jetstack
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
jetstack/cert-manager                   v1.11.1         v1.11.1         A Helm chart for cert-manager
```

```
$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --set
installCRDs=true
NAME: cert-manager
LAST DEPLOYED: Thu Apr 27 16:58:08 2023
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager v1.11.1 has been deployed successfully!
```
