### ISSUE TITLE
Unable to provision kinesis streams using ACK controller for Kinesis

### ISSUE THREAD

**Issue by grv18** [aws-controllers-k8s/community#1717]
** Problem Statement **
Unable to create a Kinesis stream using ACK. 

**Steps to reproduce**
I have installed the ACK controller for Kinesis following the steps listed [here](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/). I also added the IRSA to the controller and attached the required policies to the kinesis controller deployment.

FYI, 

```
kubectl get pods,deploy  -n $ACK_K8S_NAMESPACE                                                   
NAME                                                        READY   STATUS    RESTARTS   AGE
pod/ack-kinesis-controller-kinesis-chart-78c779d7cf-bjbqf   1/1     Running   0          52m

NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ack-kinesis-controller-kinesis-chart   1/1     1            1           77m
```

```

WSParticipantRole:~/environment $ kubectl apply -f kinesis-stream.yaml 
error: error when retrieving current configuration of:
Resource: "kinesis.services.k8s.aws/v1alpha1, Resource=streams", GroupVersionKind: "kinesis.services.k8s.aws/v1alpha1, Kind=Stream"
Name: "", Namespace: "default"
from server for: "kinesis-stream.yaml": resource name may not be empty


WSParticipantRole:~/environment $ 
WSParticipantRole:~/environment $ cat kinesis-stream.yaml 
apiVersion: kinesis.services.k8s.aws/v1alpha1
kind: Stream
spec:
  name: my-ack-kinesis
```

**Expected outcome**
I expected the kinesis stream resource to be created. However I keep getting the resource name may not be empty error, even though I am passing this in the manifest.  What am i missing here?

**Environment**

* Kubernetes version : EKS v1.23
* Using EKS (yes/no), if so version?  yes
* AWS service targeted (S3, RDS, etc.) Kinesis

**Comment by A-Hilaly** [comment]
Hi @grv18 , can you try with a similar yaml file:
```
apiVersion: kinesis.services.k8s.aws/v1alpha1
kind: Stream
metadata:
  name: my-stream
spec:
  name: my-ack-kinesis
```
