### ISSUE TITLE
Error while generator controller references within lists inside lists aren't supported. crd: "RouteTable", path: "Routes.GatewayID"

### ISSUE THREAD

**Issue by hanumanhuda** [aws-controllers-k8s/community#1718]
**Describe the bug**
Error while generating the controller config references within lists inside lists aren't supported. crd: "RouteTable", path: "Routes.GatewayID"

**Steps to reproduce**

1. pull latest main branch
2. `export SERVICE=ec2`
3. `make build-controller SERVICE=$SERVICE` in code-generator

output 
```
building ack-generate ... ok.
==== building ec2-controller ====
Copying common custom resource definitions into ec2
Building Kubernetes API objects for ec2
Generating deepcopy code for ec2
Generating custom resource definitions for ec2
Building service controller for ec2
Error: template: /Users/hanuman/workspace/go/src/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/references.go.tpl:120:3: executing "/Users/hanuman/workspace/go/src/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/references.go.tpl" at <GoCodeResolveReference $field "ko" 1>: error calling GoCodeResolveReference: references within lists inside lists aren't supported. crd: "RouteTable", path: "Routes.GatewayID"
make: *** [build-controller] Error 2

```

**Expected outcome**

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by A-Hilaly** [comment]
Hi @hanumanhuda we aware of this issue. Currently @RedbackThomson is working on a solution. To unblock the generation temporarily you can try to remove the `RouteTable` [reference configuration](https://github.com/aws-controllers-k8s/ec2-controller/blob/main/generator.yaml#L381-L384) from the generator.yaml

**Comment by cannonpalms** [comment]
@RedbackThomson Has any progress been made on this issue? We are considering support for VPCEndpointService in our own build of ACK (based on https://github.com/aws-controllers-k8s/ec2-controller/pull/134) and are running into the same concern.

**Comment by a-hilaly** [comment]
@hanumanhuda This should be possible now.
