### ISSUE TITLE
Alternative to dockershim in our test framework

### ISSUE THREAD

**Issue by jljaco** [aws-controllers-k8s/community#1722]
[dockershim goes away in k8s v1.24](https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim)

our tests currently rely heavily on Docker and we need our testing framework to be supported to k8s v1.24 and beyond.

https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/
https://kubernetes.slack.com/archives/CCK68P2Q2/p1678375295577289

**Comment by jljaco** [comment]
I deployed a 1.24 EKS cluster.

```
$ aws eks describe-cluster --name TestInfraCluster | grep version
        "version": "1.24",
```

I then copied the manifest for an existing prowjob from the current, production Prow cluster (running on an EKS 1.23 cluster):

`wget "https://prow.ack.aws.dev/rerun?mode=original&prowjob=18c517f7-e363-11ed-9b2d-da0dd0a101b7" -O prowjob-dynamodb-e2e.yaml`

Then

`kubectl -n prow apply -f prowjob-dynamodb-e2e.yaml`

The tests seem to have run just fine.

**Comment by jaypipes** [comment]
Yay! :) Closing...
