### ISSUE TITLE
Rewrite rds-controller e2e tests using fixtures

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1726]
Currently, the rds-controller e2e tests face two important issues:
- when two e2e tests are running simultaneously and using the same AWS account, they are prone to collision and failure due to the usage of constant names.
- If an e2e test assertion fails, resources are not cleaned up and remain dangling in the account.

TO improve the testing process, we need to rewrite the rds-controller e2e tests using pytest fixtures and generate resource names to prevent name collision.

**Comment by jaypipes** [comment]
@A-Hilaly I'll take this.

**Comment by A-Hilaly** [comment]
Thank you Mr. Pipes!
/close
