### ISSUE TITLE
ACK controller dashboard - creation/injection of service & credentials

### ISSUE THREAD

**Issue by bala151187** [aws-controllers-k8s/community#1733]
Right now creation of AWS services are being done with helm using CRD's

I considered using kubeapps for installing AWS controllers. but It would be nice to have a native dashboard from AWS for service Install , creation and bind to a namespace & export the credentials inside the app
[Kubeapps](https://github.com/vmware-tanzu/kubeapps/)

**Comment by bala151187** [comment]
Below is the screenshot from Openshit . You can create a s3 bucket with point & click ..  Is there anything available for EKS 
![Screen Shot 2023-04-06 at 12 10 21 PM](https://user-images.githubusercontent.com/5027627/230436251-5e1c46d0-8387-4b75-bb3e-e7b0bbc774b8.png)

**Comment by A-Hilaly** [comment]
Hi @bala151187 , if I understand well, you are requesting a native dashboard for managing ACK controllers and resources?

**Comment by bala151187** [comment]
> Hi @bala151187 , if I understand well, you are requesting a native dashboard for managing ACK controllers and resources?

Right ..

**Comment by A-Hilaly** [comment]
@bala151187 We have very high priority features for ACK controllers/runtime and unfortunately we will not be able to focus on a similar task anytime in the near future... Have you ever tried to use ArgoCD dashboard?

**Comment by bala151187** [comment]
> @bala151187 We have very high priority features for ACK controllers/runtime and unfortunately we will not be able to focus on a similar task anytime in the near future... Have you ever tried to use ArgoCD dashboard?

Yes.. but it's not intuitive as wat we are looking for ..
