### ISSUE TITLE
Events field has one less event than service side for MemoryDB resources

### ISSUE THREAD

**Issue by kyriechen96** [aws-controllers-k8s/community#1740]
**Describe the bug**
Events field has one less event than service side for MemoryDB resources.

**Steps to reproduce**
Create an cluster resource (kubectl apply), and then describe cluster (kubectl describe). Events field will be empty.

**Expected outcome**
Events from controller side is supposed to match events in service.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)
MemoryDB

**Comment by jljaco** [comment]
closing this as it doesn't have enough importance relative to other priorities
