### ISSUE TITLE
aws-controllers-k8s/prometheusservice-controller aarch64/arm64 support

### ISSUE THREAD

**Issue by aiell0** [aws-controllers-k8s/community#1742]
**Is your feature request related to a problem?**
Cannot run the prometheusservice-controller on arm64/aarch64 gravitron instances.

**Describe the solution you'd like**
Currently receiving the error `exec ./bin/controller: exec format error`  which indicates CPU architecture mismatches and is resulting in the controller pod not starting with `CrashLoopBackOff` errors. Would like to be able to run on Gravitron so we don't get those anymore.

**Describe alternatives you've considered**
None at this time.

**Comment by rommellll** [comment]
Encountering the same issue. We are running on t4g.large node instances.

**Comment by a-hilaly** [comment]
@aiell0 @hgoyal1 @romosa ARM based controller images are now supported for all existing controllers.

/close
