### ISSUE TITLE
Document support for RDS GP3 Volumes

### ISSUE THREAD

**Issue by chrisjgray** [aws-controllers-k8s/community#1747]
**Is your feature request related to a problem?**
When specifying an RDS Instance to be created, currently it only supports io1 / gp2, however RDS supports gp3 now and the controller needs to be updated to support it. Using gp3 will enable our team to gain the cost saving improvements relating to gp3 vs io1. The wins here are going to be fairly significant.

**Describe the solution you'd like**
I would like the controller to be updated to support the use of gp3 volumes with RDS.

**Describe alternatives you've considered**
Alternative is not having the capability to using gp3 volumes which is true today.

**Comment by chrisjgray** [comment]
Hi @jaypipes thank you for your response. One of my coworkers tested it out by specifying storageType: gp3 and IOPS and it worked with the controller. It appears just the documentation needs to be updated.

https://github.com/aws-controllers-k8s/rds-controller/blob/579a01ea42fb37ca925c1d3916c6028e0732e8fa/apis/v1alpha1/db_instance.go#L1040

**Comment by A-Hilaly** [comment]
Look like we just need to bump the [aws-sdk-version ](https://github.com/aws-controllers-k8s/rds-controller/blob/main/go.mod#L9)and regenerate the controller

**Comment by jaypipes** [comment]
Yep. @A-Hilaly I will regen the RDS controller with the latest aws-sdk-go version later today. I've been trying to fix #1727 first :)

**Comment by jaypipes** [comment]
@vmercierfr @chrisjgray @MarkEarhard OK folks, [release v1.1.2](https://github.com/aws-controllers-k8s/rds-controller/releases/tag/v1.1.2) of the RDS controller includes the most up to date version of aws-sdk-go (1.44.232) and contains the updated documentation for storage options.
