### ISSUE TITLE
Support controllers leader election mode

### ISSUE THREAD

**Issue by migueleliasweb** [aws-controllers-k8s/community#1753]
The Helm template seems to not allow such configuration. See: https://github.com/aws-controllers-k8s/iam-controller/blob/main/helm/templates/deployment.yaml#L14

Is there reason why wouldn't this controller work with multiple replicas?

**Comment by jaypipes** [comment]
You'd need to set up the leader election bits, but it should be possible. Is there a particular reason you want to run >1 replica? For performance or for availability reasons?

**Comment by migueleliasweb** [comment]
Hi @jaypipes once again.

Yeah, it my case is the company policy for reliability.

I was looking through the code and the leader election code seems to be mostly configured. It might be missing the key for the election and way to check whether we're running multiple replicas or not so the election is enabled or disabled correctly.

Would you be against implementing this? I could also give it a shot if that's okay.

Thanks for the swift reply, Jay!

**Comment by migueleliasweb** [comment]
I've found there is a flag being set on https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/config/config.go#L106 and all it takes is that flag to be set so it handles the leader election. 

From what I can tell, all it takes to support HA is:
- Enable replicas to be set in the helm chart via the `values.yaml`
- Use the replicas value to check if we need to set the `--enable-leader-election` flag

Let me know what you think, @jaypipes . I will go ahead and create this PR so we have something to talk about =P.

**Comment by migueleliasweb** [comment]
Done :)

**Comment by migueleliasweb** [comment]
Humm yeah I guess you're right...

I've read a bit more about the leader election and the configuration that is missing. The controller runtime 
config should be fairly straightforward to add. What seems to be missing is just the key to be used to determine the election and possibly some rbac configuration to ensure the pods will have access to the configmap/endpoint that is used to orchestrate the election.

I wonder how could we make this change isolated to the ack IAM controller instead of enabling it at the same time for all controllers that pull code from that shared library.

**Comment by A-Hilaly** [comment]
@migueleliasweb All the controllers already import `ack/runtime` and `k8s/controller-runtime` - I we want to fully support this feature, we'll have to touch a bit `ack/runtime` and maybe `code-generator` ? if you have a prototype of leader election working i'm happy to give it a shot :)

**Comment by migueleliasweb** [comment]
https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go

**Comment by A-Hilaly** [comment]
@migueleliasweb I have a patch that worked for lambda/dynamodb controllers https://github.com/aws-controllers-k8s/code-generator/pull/455 - hoping to get it merged/released soon.

**Comment by A-Hilaly** [comment]
> https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go

Thank you for sharing this, it was helpful and interesting to read! controller-runtime hides a lot of the client-go options we only can configure those https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/leaderelection/leader_election.go#L36-L52

**Comment by migueleliasweb** [comment]
I'm the one to should thank you for actioning this so quickly!

Btw, I reckon, under the hood the leader election relies on leases (https://kubernetes.io/docs/concepts/architecture/leases/) to get a "lock" and determine the leader. I don't know what Kubernetes version the ACK controllers aim to be deployable to but if the idea is to support the current EKS versions, this should be just fine ;).

**Comment by a-hilaly** [comment]
Also adding a new flag to be able to configure leader election namespace https://github.com/aws-controllers-k8s/runtime/pull/123

**Comment by a-hilaly** [comment]
@migueleliasweb Leader election is implemented and we are currently in the process of releasing a new version for all the controllers to include this feature.

**Comment by a-hilaly** [comment]
released for all the controllers
/close
