### ISSUE TITLE
Lambda controller not able to create a edge function

### ISSUE THREAD

**Issue by karthik2491** [aws-controllers-k8s/community#1755]
Hi team,
Tried to deploy a lambda function at edge with below manifest :

```apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: test-py-edge
 annotations:
   services.k8s.aws/region: us-east-1
spec:
 name: test-py-edge
 code:
   s3Bucket: S3_BUCKET
   s3Key: test-lambda-edge.zip
 role: ROLE_ARN
 runtime: python3.9
 handler: lambda_function.lambda_handler
 description: function created by ACK lambda-controller e2e tests
 masterARN: arn:aws:lambda:us-east-1:<account>:function:test-py-edge 
```

Not able to create a deploy lambda function at edge, is there already support to deploy at edge

**Comment by A-Hilaly** [comment]
Hi @karthik2491 , can you please share the content of `status.Conditions`? and/or some controller logs related to this issue.

**Comment by karthik2491** [comment]
@A-Hilaly While i try to execute above shared manifest itself got error stating masterARN is not a valid field in spec. Does lambda controller supports lambda function at edge.

**Comment by A-Hilaly** [comment]
@karthik2491  Is this a new feature? If yes we’ll have to bump the sdk version :) 

You can find the supported fields here:
- https://github.com/aws-controllers-k8s/lambda-controller/blob/main/apis/v1alpha1/function.go#L24
- https://aws-controllers-k8s.github.io/community/reference/lambda/v1alpha1/function/
