### ISSUE TITLE
Add `org.opencontainers.image.source` label to docker images

### ISSUE THREAD

**Issue by james-callahan** [aws-controllers-k8s/community#1758]
**Is your feature request related to a problem?**
I'd like to take advantage of renovate's changelog support (https://docs.renovatebot.com/modules/datasource/docker/)

**Describe the solution you'd like**
To do so, the recommended way is to add the standard OCI label `org.opencontainers.image.source` with the value as the github URL of the particular service controller.

**Comment by A-Hilaly** [comment]
Hi @james-callahan, thank you for bringing this to our attention. QQ: is this something we need to add at the pod/deployment config level? or somewhere else?

**Comment by james-callahan** [comment]
> QQ: is this something we need to add at the pod/deployment config level? or maybe you mean like https://docs.docker.com/engine/reference/builder/#label ?

Yeah the latter. i.e. a dockerfile would gain:
```Dockerfile
LABEL org.opencontainers.image.source="https://github.com/aws-controllers-k8s/some-controller"
```

But I never found Dockerfiles for ACK images. Depending on how they are built you will need to pass some flag to your docker image building process.

**Comment by james-callahan** [comment]
> But I never found Dockerfiles for ACK images. Depending on how they are built you will need to pass some flag to your docker image building process.

Is it https://github.com/aws-controllers-k8s/code-generator/blob/b55ae8752ece381c383ffe5b388ed2147c6b30d8/Dockerfile and https://github.com/aws-controllers-k8s/code-generator/blob/b55ae8752ece381c383ffe5b388ed2147c6b30d8/Dockerfile.local?
Looks like it would be simple enough to add `LABEL` in there.

**Comment by A-Hilaly** [comment]
> Is it https://github.com/aws-controllers-k8s/code-generator/blob/b55ae8752ece381c383ffe5b388ed2147c6b30d8/Dockerfile and https://github.com/aws-controllers-k8s/code-generator/blob/b55ae8752ece381c383ffe5b388ed2147c6b30d8/Dockerfile.local?
Looks like it would be simple enough to add LABEL in there.

Correct! Would you be interested in submitting a PR to add the labels?

**Comment by james-callahan** [comment]
> Would you be interested in submitting a PR to add the labels?

https://github.com/aws-controllers-k8s/code-generator/pull/438
