### ISSUE TITLE
IAM controller recommended inline policy needs iam:UpdateAssumeRolePolicy

### ISSUE THREAD

**Issue by rlister** [aws-controllers-k8s/community#1765]
**Describe the bug**

v1.2.0 ack-iam-controller needs `iam:UpdateAssumeRolePolicy`. The [recommended-inline-policy](https://raw.githubusercontent.com/aws-controllers-k8s/iam-controller/main/config/iam/recommended-inline-policy) should be updated to include this action.

**Steps to reproduce**

Run v1.2.0, logs report:

```
"error": "AccessDenied: User: xxx is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role xxx because no identity-based policy allows the iam:UpdateAssumeRolePolicy action
```

**Expected outcome**

Controller should be able to update assume role policy document per https://github.com/aws-controllers-k8s/iam-controller/pull/74

**Environment**

* Kubernetes version: 1.25.6
* Using EKS (yes/no), if so version? yes 1.25
* AWS service targeted (S3, RDS, etc.) IAM

**Comment by A-Hilaly** [comment]
Thank you for catching this @rlister - it's a pretty simple one to fix. Are you interested in contributing to the iam-controller? :)

**Comment by jdockerty** [comment]
This has been open for a little while now, but since it directly relates to a change I made I've linked a PR to fix it.

I don't see any code generation for the inline policy itself and it has the `Sid` of `VisualEditor`, so I believe it is a simple line change.

**Comment by jaypipes** [comment]
Completed now.
