### ISSUE TITLE
ACK EC2 SecurityGroup without default egress rule.

### ISSUE THREAD

**Issue by elops** [aws-controllers-k8s/community#1766]
I want to be able to create Security Group with EC2 controller that has no egress rules. 

For instance I just want security group that will be used as a Label, so other groups can reference it and say, any resource which has label can access X. 

It is frustrating to not be able to just create empty Security Group. Closest thing seems to be is to add some obscure egress rule that will never be matched just so it replaces default egress rule.

**Comment by A-Hilaly** [comment]
Hi @elops - what are errors are you seeing when trying to create an empty security group? Can share the content of `status.Condition` / some controller logs here?

**Comment by elops** [comment]
> Hi @elops - what are errors are you seeing when trying to create an empty security group? Can share the content of `status.Condition` / some controller logs here?

```
$ cat empty_sg.yaml 
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: empty-sg
spec:
  description: "empty security group"
  name: empty-sg
  vpcID: vpc-04ec6ed5bfc59ab03
$ k apply -f empty_sg.yaml 
securitygroup.ec2.services.k8s.aws/empty-sg created

$ k logs ec2-chart-1680703321-5fd58cc98b-4znqz -n ack-system | tail -n1
2023-04-09T10:23:12.383Z	INFO	ackrt	created new resource	{"account": "AccountID-redacted", "role": "", "region": "us-east-1", "kind": "SecurityGroup", "namespace": "default", "name": "empty-sg", "is_adopted": false, "generation": 1}

$ aws ec2 describe-security-groups --group-ids sg-0bd91857a831640d1
{
    "SecurityGroups": [
        {
            "Description": "empty security group",
            "GroupName": "empty-sg",
            "IpPermissions": [],
            "OwnerId": "AccountID-redacted",
            "GroupId": "sg-0bd91857a831640d1",
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "Tags": [
                {
                    "Key": "services.k8s.aws/namespace",
                    "Value": "default"
                },
                {
                    "Key": "services.k8s.aws/controller-version",
                    "Value": "ec2-v1.0.1"
                }
            ],
            "VpcId": "vpc-04ec6ed5bfc59ab03"
        }
    ]
}
```

**Comment by jaypipes** [comment]
Yeah, EC2 automatically creates a default allow all egress rule on all security groups. You have to manually delete this default egress rule unless you use Terraform which made the decision to automatically *delete* the default egress rule because they thought the user experience of a default egress allow all rule was surprising for users. @LikithaVemulapalli what do you think?

**Comment by elops** [comment]
> Yeah, EC2 automatically creates a default allow all egress rule on all security groups. You have to manually delete this default egress rule unless you use Terraform which made the decision to automatically _delete_ the default egress rule because they thought the user experience of a default egress allow all rule was surprising for users. @LikithaVemulapalli what do you think?

I understand there is default rule but the way ACK controller is handling it now is broken.

Behavior of code in version v1.0.1 vs v0.1.0 which is last code I found before 
https://github.com/aws-controllers-k8s/ec2-controller/commit/abe7bda was applied.

v0.1.0
```
$ cat empty_security_group.yaml 
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test-security-group
spec:
  description: "Test security group"
  name: test-security-group
  vpcID: vpc-04ec6ed5bfc59ab03

$ k apply -f empty_security_group.yaml 
securitygroup.ec2.services.k8s.aws/test-security-group created
$ aws ec2 describe-security-groups --group-ids sg-04477664a3f5875ab
{
    "SecurityGroups": [
        {
            "Description": "Test security group",
            "GroupName": "test-security-group",
            "IpPermissions": [],
            "OwnerId": "REDACTED",
            "GroupId": "sg-04477664a3f5875ab",
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "Tags": [
                {
                    "Key": "services.k8s.aws/namespace",
                    "Value": "default"
                },
                {
                    "Key": "services.k8s.aws/controller-version",
                    "Value": "ec2-v0.1.0"
                }
            ],
            "VpcId": "vpc-04ec6ed5bfc59ab03"
        }
    ]
}
```
Up to this point both v0.1.0 and v1.0.1 will behave the same but issue is bug introduced in PR mentioned above.
In short, v0.1.0 when you create a group with no egress is aware that there is default rule in that security group, and when you re-apply your yaml controller will remove the default egress rule (as seen below), but in v1.0.1 code it will just say that it's unchanged and will not apply update.

behavior of v0.1.0 when trying to re-apply the same yaml for 2nd and 3rd time.
```
$ k apply -f empty_security_group.yaml #2nd time 
securitygroup.ec2.services.k8s.aws/test-security-group configured
$ k apply -f empty_security_group.yaml #3rd time 
securitygroup.ec2.services.k8s.aws/test-security-group unchanged
$ aws ec2 describe-security-groups --group-ids sg-04477664a3f5875ab
{
    "SecurityGroups": [
        {
            "Description": "Test security group",
            "GroupName": "test-security-group",
            "IpPermissions": [],
            "OwnerId": "REDACTED",
            "GroupId": "sg-04477664a3f5875ab",
            "IpPermissionsEgress": [],
            "Tags": [
                {
                    "Key": "services.k8s.aws/namespace",
                    "Value": "default"
                },
                {
                    "Key": "services.k8s.aws/controller-version",
                    "Value": "ec2-v0.1.0"
                }
            ],
            "VpcId": "vpc-04ec6ed5bfc59ab03"
        }
    ]
}

```

behavior of v1.0.1 when trying to apply the same yaml for 2nd time.
```
$ k apply -f empty_security_group.yaml 
securitygroup.ec2.services.k8s.aws/test-security-group unchanged
```
Meaning it is unaware that there is default rule so when you try to apply yaml that does not have egress defined it will not delete default rule. 
Only way v1.0.1 code will delete default rule is if you define some egress rule of your own. Then default rule will be deleted and later on if you decide to remove your custom egress rule then applying security group without egress will get you to state where you have no egress rules.

Why not simply delete default egress rule regardless if there is customer specified replacement or not. I understand it was a good intent but IMO it is really causing more headaches than doing good this default egress rule.

**Comment by jaypipes** [comment]
@elops yes, I understand you. @LikithaVemulapalli should we consider deleting the default egress rule?

**Comment by LikithaVemulapalli** [comment]
> Yeah, EC2 automatically creates a default allow all egress rule on all security groups. You have to manually delete this default egress rule unless you use Terraform which made the decision to automatically _delete_ the default egress rule because they thought the user experience of a default egress allow all rule was surprising for users. @LikithaVemulapalli what do you think?

As per the current functionality, yes default egress rule will be attached on creating a security group.

**Comment by A-Hilaly** [comment]
@LikithaVemulapalli I believe that we should have a similar experience to Terraform here. Having a default "egress" role is a surprising experience. Let's consider deleting the default egress rule, after SG creation?

**Comment by LikithaVemulapalli** [comment]
> @elops yes, I understand you. @LikithaVemulapalli should we consider deleting the default egress rule?

We can do that, if it's better this way, then we need to delete default Egress rule.

**Comment by LikithaVemulapalli** [comment]
> @LikithaVemulapalli I believe that we should have a similar experience to Terraform here. Having a default "egress" role is a surprising experience. Let's consider deleting the default egress rule, after SG creation?

Yes @A-Hilaly , may be deleting default Egress rule might resolve the errors.
