### ISSUE TITLE
Getting `missing required field "apiID"` in `apigatewayv2.Integration` when creating API Gateway Integration

### ISSUE THREAD

**Issue by davfsand** [aws-controllers-k8s/community#1767]
**Describe the bug**
A concise description of what the bug is.
I'm following the tutorial to [Manage HTTP APIs with the ACK APIGatewayv2 Controller](https://aws-controllers-k8s.github.io/community/docs/tutorials/apigatewayv2-reference-example/). In the Create HTTP API step, when applying the configuration, the API is created, however the Integration, Route and Stage are not created. The following error appear:
`error: error validating "apigwv2-httpapi.yaml": error validating data: [ValidationError(Integration.spec): unknown field "apiRef" in aws.k8s.services.apigatewayv2.v1alpha1.Integration.spec, ValidationError(Integration.spec): missing required field "apiID" in aws.k8s.services.apigatewayv2.v1alpha1.Integration.spec]; if you choose to ignore these errors, turn validation off with --validate=false`

**Steps to reproduce**
- Follow the [Manage HTTP APIs with the ACK APIGatewayv2 Controller](https://aws-controllers-k8s.github.io/community/docs/tutorials/apigatewayv2-reference-example/) guide to reproduce the error.

**Expected outcome**
A concise description of what you expected to happen.
Be able to use the “*Ref” fields inside the manifest to not to worry about finding APIID, IntegrationID when creating the K8s resource manifests.

**Environment**

* Kubernetes version: 1.25
* Using EKS (yes/no), if so version?: Yes. 1.25
* AWS service targeted (S3, RDS, etc.): API Gateway

**Comment by RedbackThomson** [comment]
It sounds like you may have an older version of the CRDs installed for the controller. The `apiRef` field was added in `v0.0.17` - which was over a year ago. I would ask that you try to re-install the CRDs using the latest version

**Comment by davfsand** [comment]
@RedbackThomson Thanks for your prompt response. I checked the version of the chart and I'm using the [v1.0.3](https://github.com/aws-controllers-k8s/apigatewayv2-controller/releases/tag/v1.0.3). I even delete it and installed the v.0.0.17 as the tutorial indicates and didn't work. The API is created but the other components are not.

**Comment by RedbackThomson** [comment]
Helm doesn't really play nicely with CRDs - see https://helm.sh/docs/chart_best_practices/custom_resource_definitions/. So even though your Helm chart version is `v1.0.3`, if you have previously had an older version of the CRDs installed, Helm would not have uninstalled them. Please try installing the CRDs directly from Github, using `kubectl`:
```bash
kubectl apply -k "github.com/aws-controllers-k8s/apigatewayv2-controller/config/crd"
```

**Comment by davfsand** [comment]
@RedbackThomson you were right. Thanks for your explanation, I'll keep that in mind. I updated the CRDs and it worked as expected. Thank you!
