### ISSUE TITLE
Cross namespace resource references

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1777]
Currently ACK controllers only allow [within-same-namespace resource references ](https://github.com/aws-controllers-k8s/community/blob/main/docs/design/proposals/resource-reference/cross-api-group.md#scope). It would be nice to extend this feature to allow cross-namespace references and have a similar experience to resources secret fields. This is technically not very complicated to implement.

Runtime changes:
- https://github.com/aws-controllers-k8s/runtime/blob/main/apis/core/v1alpha1/identifiers.go#L72-L76

Code generator changes:
- After https://github.com/aws-controllers-k8s/code-generator/pull/435 merge - we need to stop passing the parent resource namespace and use the one mentioned in the ref field.

If anyone wanna give this a stab feel free to drop questions in this thread
/good-first-issue
/help-wanted

**Comment by the-cybersapien** [comment]
Hi! 
I'll take a stab at this!

/assign @the-cybersapien
