### ISSUE TITLE
Support resource adoption for SQS queues

### ISSUE THREAD

**Issue by arjunrn** [aws-controllers-k8s/community#1778]
**Is your feature request related to a problem?**
Resource adoption of SQS doesn't work. I investigated this and the reason I found is that the [SetIdentifier](https://github.com/aws-controllers-k8s/sqs-controller/blob/af24f6d9df9989dee3f8dce4682cf01108a52d29/pkg/resource/queue/resource.go#L87-L89) is empty. This is empty because the code-generator does not implement this functionality for when resources which are queried for their attributes. [Relevant code](https://github.com/aws-controllers-k8s/code-generator/blob/4be9ee71ea7f759452623047ca62716a240c8b6f/pkg/generate/code/set_resource.go#L958-L961).

This issue also affects:
- [SNS Topic](https://github.com/aws-controllers-k8s/sns-controller/blob/ad2b4e4b2351b4f2f9c15d3ff9f96aa5d49ce481/pkg/resource/topic/resource.go#L87-L89)
- [SNS Subscription](https://github.com/aws-controllers-k8s/sns-controller/blob/ad2b4e4b2351b4f2f9c15d3ff9f96aa5d49ce481/pkg/resource/subscription/resource.go#L87-L89).

**Describe the solution you'd like**
Support for resource adoption of queues.

**Describe alternatives you've considered**
None

**Comment by jaypipes** [comment]
Thanks @arjunrn! Are you interested in taking on this work? If so, I can help walk you through the code?

**Comment by jaypipes** [comment]
For the record, this is the code that needs to be implemented for attribute-based APIs:

https://github.com/aws-controllers-k8s/code-generator/blob/74d546580f0b0eaf583469bc174fe6007d62e008/pkg/generate/code/set_resource.go#L958-L961

**Comment by jaypipes** [comment]
@arjunrn you did it perfectly. :)

**Comment by arjunrn** [comment]
PRs for this feature have been merged and released.
