### ISSUE TITLE
SNS Topics created with sns-controller <v1.0.0 fail to reconcile in v1.0.0

### ISSUE THREAD

**Issue by jessebye** [aws-controllers-k8s/community#1779]
**Describe the bug**
When an SNS topic has been created with `sns-controller` on an earlier version (such as v0.0.12), it fails to reconcile when the `sns-controller` is updated to the latest version (v1.0.0) with the following error:

```
2023-04-18T16:10:17.020Z    ERROR    Reconciler error    {"controller": "topic", "controllerGroup": "sns.services.k8s.aws", "controllerKind": "Topic", "Topic": {"name":"test-api-client-created-event","namespace":"test"}, "namespace": "test", "name": "test-api-client-created-event", "reconcileID": "bf8fb0c4-46c6-4fce-a7d6-ce65e0635fd6", "error": "InternalFailure: \n\tstatus code: 500, request id: 0230d8b4-482c-553f-8483-840c8b04c09d"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235
```

**Steps to reproduce**
1. Create a topic with sns-controller v0.0.12.
2. Update sns-controller to v1.0.0.
3. Observe the errors in the logs when it tries to reconcile the existing topics.

**Expected outcome**
It should be backwards-compatible with topics created in previous versions.

**Environment**

* Kubernetes version **1.25**
* Using EKS (yes/no), if so version? **yes, 1.25**
* AWS service targeted (S3, RDS, etc.) **SNS**

**Comment by jessebye** [comment]
Sure. Inspecting a diff of the topics created by each version, I noticed that v1.0.0 adds a `policy` to the `spec`:
```
<   policy: '{"Version":"2008-10-17","Id":"__default_policy_ID","Statement":[{"Sid":"__default_statement_ID","Effect":"Allow","Principal":{"AWS":"*"},"Action":["SNS:GetTopicAttributes","SNS:SetTopicAttributes","SNS:AddPermission","SNS:RemovePermission","SNS:DeleteTopic","SNS:Subscribe","SNS:ListSubscriptionsByTopic","SNS:Publish"],"Resource":"arn:aws:sns:us-east-2:REDACTED:test-api-account-cash-distribution-updated-event","Condition":{"StringEquals":{"AWS:SourceOwner":"REDACTED"}}}]}'
49,54c48

```
Otherwise the manifests look identical.

**Comment by a-hilaly** [comment]
Are you still experiencing this issue @jessebye ?

**Comment by jessebye** [comment]
no, we've long since recreated our SNS topics on >1.0 and no longer have the issue

**Comment by a-hilaly** [comment]
Thank you @jessebye !
/close
