### ISSUE TITLE
same-named fields in Input and Output shapes with different Go types

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#178]
When building the RDS service controller, there are still two failures when running`make test` after generating the controller with `scripts/build.controllers.sh rds`.

The first failure is in `services/rds/pkg/resources/db_proxy/sdk.go` and the other in `services/rds/pkg/resources/db_instance/sdk.go`

Both of those failures are due to the following: when the name of a field in a Create Input shape is the same as the name of a field in the corresponding ReadOne or ReadMany output shape, but the data types of those fields are different, we run into problems. The RDS APIs have two places where this happens. The first case is CreateDBInstance's Input shape has a field "DBSecurityGroups". It is of type `[]*string`:

https://github.com/aws/aws-sdk-go/blob/master/models/apis/rds/2014-10-31/api-2.json#L2838.

However, the DescribeDBInstanceGroups API's Output shape has a DBSecurityGroups field that is of type `[]*DBSecurityGroupMembership`:

https://github.com/aws/aws-sdk-go/blob/master/models/apis/rds/2014-10-31/api-2.json#L3629.

The code that is generated to handle the setting of Spec and Status fields does so by looking for Spec and Status fields that match the field names (member names) of an Output shape:

https://github.com/aws/aws-controllers-k8s/blob/main/pkg/model/crd.go#L1222-L1278

Unfortunately, that code assumes that the data types of the Spec and Status fields with the same member name are the same as the data types of the member name in the Output shape. And, as noted for RDS, there are two exceptions to this behaviour. 

The fastest way to solve the above problem is to add something to the GeneratorConfig that will instruct the code generator about these types of exceptional behaviours. Long term, we might be able to do something more magical and introspective...

**Comment by brycahta** [comment]
Another data point is [CreateDhcpOptions](https://github.com/aws/aws-sdk-go/blob/main/models/apis/ec2/2016-11-15/api-2.json#L497).

* In the request, users provide [NewDhcpConfigurationList](https://github.com/aws/aws-sdk-go/blob/main/models/apis/ec2/2016-11-15/api-2.json#L8090)

* In the response, configurations are returned as [DhcpConfigurationList](https://github.com/aws/aws-sdk-go/blob/main/models/apis/ec2/2016-11-15/api-2.json#L15410)

The difference is [DhcpConfiguration.Value](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DhcpConfiguration.html) is of type `AttributeValue` whereas [NewDhcpConfiguration.Value](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_NewDhcpConfiguration.html) is of type `String`

**Comment by RedbackThomson** [comment]
Closing since https://github.com/aws-controllers-k8s/code-generator/pull/232 implements basis of issue. Follow-ups to come
