### ISSUE TITLE
Support for arm64 instances

### ISSUE THREAD

**Issue by romosa** [aws-controllers-k8s/community#1781]
**Is your feature request related to a problem?**
We are running t4g.large node instances on our EKS cluster and unable to make SQS controller working.

**Describe the solution you'd like**
Support arm64 architecture instances. The error is similar to [issue # 1742](https://github.com/aws-controllers-k8s/community/issues/1742) but for sqs controller.

```
$ k logs -f ack-sqs-controller-sqs-chart-5dd87b7994-7st79  --namespace ack-system 
exec ./bin/controller: exec format error
```

**Describe alternatives you've considered**
None

**Comment by a-hilaly** [comment]
@romosa this is supported now :)
/close
