### ISSUE TITLE
[IAM] On policy creation allow role attachment

### ISSUE THREAD

**Issue by jdockerty** [aws-controllers-k8s/community#1788]
**Is your feature request related to a problem?**
An IAM `Policy` can be attached to a `Role` on the `Role`'s creation time via the [`policies`](https://doc.crds.dev/github.com/aws-controllers-k8s/iam-controller/iam.services.k8s.aws/Role/v1alpha1@v1.2.0#spec-policies) or [`policyRef`](https://doc.crds.dev/github.com/aws-controllers-k8s/iam-controller/iam.services.k8s.aws/Role/v1alpha1@v1.2.0#spec-policyRefs) fields, but it is not always the case that they are created together.

In our case, we have some pre-existing IAM Roles which would benefit from being able to be attached to from new policies created from Kubernetes manifests via ACK.

**Describe the solution you'd like**
I can see 2 possible solutions (although there is likely a better one):

1. The current `Policy` resource is updated to include a `roleRef` (or equivalently named field) that allows the attaching of the created `Policy ` directly to a specified role.
2. A new resource is created which handles this attachment, e.g. `PolicyAttachment`.

I believe that both of these would be possible through the use of the [`AttachRolePolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html) API.

**Describe alternatives you've considered**
Initially I thought that the `AdoptedResource` kind would solve this issue, but from what I understand this simply allows the editing of metadata from the Kubernetes API perspective and whilst the relevant object is created this is after-the-fact of applying the `AdoptedResource`, i.e. we do not have the specific kind (e.g. `Role`) to then manipulate in code - it only exists within the Kubernetes API and not from inception of an entirely new cluster.

**Happy to consider any other alternatives that I may have missed or contribute to this feature request in anyway I can. It may also be possible that this request muddies the lines between the resource's responsibilities and may need further consideration.**

**Comment by jaypipes** [comment]
Hi @jdockerty. Please see https://github.com/aws-controllers-k8s/community/issues/1579#issuecomment-1345606976 for an explanation as to why we won't be supporting `Policy.RoleRefs` and will only be supporting the Role -> Policy relationship via `Role.PolicyRefs`.

**Comment by jdockerty** [comment]
Makes sense! Thanks for the explanation @jaypipes
