### ISSUE TITLE
AdoptedResource requires aws.nameOrId for kind Role

### ISSUE THREAD

**Issue by wdonne** [aws-controllers-k8s/community#1799]
**Describe the bug**
According to the [documentation](https://aws-controllers-k8s.github.io/community/reference/common/v1alpha1/adoptedresource/) the field `aws.nameOrId` is optional. However, if you omit it from an `AdoptedResource` object with kind `Role` you get the error "Expected name or ID, found nil". This is not the case for the kind `Policy`, for example.

**Steps to reproduce**

- Create a role resource for the IAM controller.
- Also create an `AdoptedResource` for it without the field `aws.nameOrId`.
- Watch the `status` field of the latter.
- Add the field `aws.nameOrId`.
- Watch the `status` field.

**Expected outcome**
The error message shouldn't appear in the `status` field, because the `aws.nameOrId` field is optional.

**Environment**

* Kubernetes version: 1.26
* eks.2
* IAM roles through ACK IAM 1.2.1.

**Comment by RedbackThomson** [comment]
`nameOrId` is only optional because the controller requires `nameOrId` XOR `arn`. Either way, the controller needs *some* identifier for the resource so it knows what to adopt. Unfortunately, because the AWS APIs require different unique identifiers depending on the service and the individual resource, we can't be more prescriptive with our documentation about which of these fields is actually required.

**Comment by wdonne** [comment]
Indeed, I should have mentioned the `aws.arn` field. In my test for both the kinds `Role` and `Policy` that field is present, but only for `Role` the field `nameOrId` must also be present. Why is that different?

**Comment by RedbackThomson** [comment]
Yeah so what's happening here is that `policy` only requires `arn` - and it seems we don't throw an error if it's not specified - https://github.com/aws-controllers-k8s/iam-controller/blob/main/pkg/resource/policy/resource.go#L87-L94

Whereas `role` requires only `nameOrId` - and it does throw an error if it's not specified - https://github.com/aws-controllers-k8s/iam-controller/blob/main/pkg/resource/role/resource.go#L87C36-L94

Resources cannot require both `arn` and `nameOrId`. So it's just a matter of the errors not being clear about expectations
