### ISSUE TITLE
Install documentation needs to be updated to remove the `v` prefix in image tags

### ISSUE THREAD

**Issue by aaroniscode** [aws-controllers-k8s/community#1818]
**What is the URL of the document?**

https://aws-controllers-k8s.github.io/community/docs/user-docs/install/

**Which section(s) is the issue in?**

## Install an ACK service controller with Helm (Recommended)

**What needs fixing?**

The instructions:
```
export RELEASE_VERSION=$(curl -sL https://api.github.com/repos/aws-controllers-k8s/$SERVICE-controller/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
```
will create a version like `v1.0.3` and install will fail currently on the EC2 service controller as the result will be `v1.0.3` and that tag doesn't exist: https://gallery.ecr.aws/aws-controllers-k8s/ec2-controller. The correct version is `1.0.3` without the `v`.

**Additional context**

See #1802 where it states new charts/images will not be published the `v`.

**Comment by aaroniscode** [comment]
This is still an issue. The EC2 controller release version has a `v` and the latest image tags in ECR Public do not.

**Comment by a-hilaly** [comment]
Hi @aaroniscode, It seems that the current command for obtaining the release version is: 
```
export RELEASE_VERSION=$(curl -sL https://api.github.com/repos/aws-controllers-k8s/${SERVICE}-controller/releases/latest | jq -r '.tag_name | ltrimstr("v")')
```
Could you please confirm if this command is still not functioning as expected on your end?

**Comment by aaroniscode** [comment]
@a-hilaly You are right, this has been fixed. I looked too quickly and missed the `ltrimstr("v")` that has been added to the instructions.
