### ISSUE TITLE
All Helm charts need to be updated to remove the `v` prefix in `version` and `appVersion`

### ISSUE THREAD

**Issue by aaroniscode** [aws-controllers-k8s/community#1819]
**Describe the bug**
All Helm charts need to be updated to remove the `v` prefix in `version` and `appVersion`. With the decision in #1802 to use a new format for Helm chart and image tag versions, the Helm charts need to be updated to reflect that change.

This will also include the `image.tag` in the values.yaml file.

**Steps to reproduce**
N/A

**Expected outcome**
N/A

**Environment**
N/A

* Kubernetes version
N/A

* Using EKS (yes/no), if so version? 
N/A

* AWS service targeted (S3, RDS, etc.)
All

**Comment by RedbackThomson** [comment]
This change has already been applied for all GA controllers, and should be rolling out to developer preview controllers. Do you see a particular controller that hasn't been updated correctly?

**Comment by aaroniscode** [comment]
Hi @RedbackThomson ... I had been looking at the EKS controller but that was updated about 4 hours ago. As I review others I see what you are saying and they are updated.

I did find the IAM controller, which is GA, still hasn't been updated: https://github.com/aws-controllers-k8s/iam-controller/blob/main/helm/Chart.yaml

**Comment by RedbackThomson** [comment]
@aaroniscode Thank you. This issue reminded me that even though I had made the change to the release code, most of the controllers had not issued a new release since then. I have just gone through all of our auto-generated PRs, made sure they remove the `v` prefix, and merged them. You should now see all of our GA controllers are consistent.

**Comment by aaroniscode** [comment]
It looks like the few places I noticed this already had PR's in the queue to fix this that hadn't been merged. Looks good to me now. Thanks!
