### ISSUE TITLE
Bug Report: Unpublished Image Tags in sqs-controller and iam-controller Helm Charts

### ISSUE THREAD

**Issue by asonnleitner** [aws-controllers-k8s/community#1829]
**Describe the bug**
I have noticed that the recent update for the `sqs-controller` and `iam-controller` Helm charts in the `aws-controllers-k8s` repository might be referencing unpublished image tags. The specified tags in the Helm charts are not available in the respective ECR repositories.

**Steps to reproduce**
1. Refer to the following Helm chart files:
   - `iam-controller`: [values.yaml](https://github.com/aws-controllers-k8s/iam-controller/blob/main/helm/values.yaml)
   - `sqs-controller`: [values.yaml](https://github.com/aws-controllers-k8s/sqs-controller/blob/main/helm/values.yaml)
2. Observe the image tag configurations mentioned in the Helm charts.
3. Compare them with the available tags in the respective ECR repositories:
   - `iam-controller`: [ECR Repository](https://gallery.ecr.aws/aws-controllers-k8s/iam-controller) (ends at version 1.2.1)
   - `sqs-controller`: [ECR Repository](https://gallery.ecr.aws/aws-controllers-k8s/sqs-controller) (ends at version 1.0.3)

**Expected outcome**
The image tag references in the `sqs-controller` and `iam-controller` Helm charts should correspond to the published tags available in the respective ECR repositories.

**Environment**
Please provide the following details about your environment:
* Kubernetes version: `v1.26.4`
* Using EKS (yes/no), if so, version: yes, `v1.26.4-eks-0a21954`
* AWS service targeted (S3, RDS, etc.): `IAM`, `S3`

Please let me know if you need any further information.

**Comment by RedbackThomson** [comment]
It appears there is a bug in the [latest Golang `1.19.10` image](https://gallery.ecr.aws/docker/library/golang) that we use for building and releasing the controller images. All release builds, started after the `1.19` tag was moved up to `1.19.10`, got stuck on `go mod download` without any error messages. I ssh'd into these build jobs, manually tested with `1.19.8` and confirmed that they were unblocked. I released [a temporary fix](https://github.com/aws-controllers-k8s/test-infra/pull/362) to pin the `GOLANG_VERSION` of the release scripts to `1.19.8` just to see these current releases pushed through, but plan on reverting this once we can validate that `1.19.11` works.
