### ISSUE TITLE
RDS controller resource sync issue

### ISSUE THREAD

**Issue by bala151187** [aws-controllers-k8s/community#1831]
**Describe the bug**
Using RDS ack version v1.1.2 .. Trying to create RDS backend and the RDS creation is successful and database is available But the FieldExport values are not populated .Which causing the application container failing to start 

Kubectl describe DBInstance

> Status:
>   Ack Resource Metadata:
>     Arn:               arn
>     Owner Account ID:  xxxxxxx
>     Region:            us-east-1
>   Conditions:
>     Last Transition Time:     2023-06-15T19:32:24Z
>     **Status:                   False**
>     Type:                     ACK.ResourceSynced
>     Last Transition Time:     2023-06-15T19:32:24Z
>     Message:                  Late initialization successful
>     Reason:                   Late initialization successful
>     Status:                   True
>     Type:                     ACK.LateInitialized

Logs from RDS controller 

> 2023-06-15T19:19:53.285Z	INFO	ackrt	desired resource state has changed	{"account": "xxx", "role": "", "region": "us", "kind": "DBInstance", "namespace": "devops", "name": "dev-devops-demo", "is_adopted": false, "generation": 2, "diff": [{"Path":{"Parts":["Spec","CACertificateIdentifier"]},"A":null,"B":"rds-ca-2019"},{"Path":{"Parts":["Spec","StorageThroughput"]},"A":null,"B":0}]}
> 
> 2023-06-15T19:19:54.039Z	INFO	ackrt	updated resource	{"account": "xxxx", "role": "", "region": "us", "kind": "DBInstance", "namespace": "devops", "name": "dev-devops-demo", "is_adopted": false, "generation": 2}

**Steps to reproduce**
 The CRD is updated 
$ kubectl get crds | grep dbinstances

> **dbinstances.rds.services.k8s.aws                     2022-12-16T17:52:32Z**

But the RDS controller version v1.1.2 was updated a month ago But the CRD is not updated bcoz of helm3 limitation

**Expected outcome**
I was expecting these logs from RDS controller

> 2023-06-16T13:11:28.070Z	INFO	exporter.field-export-reconciler	patched target config map

I know Just bcoz the resource sync status `FALSE` But wat it really made to `NOT` sync bcoz of oudated CRD

I used this [repo](https://github.com/a-hilaly/ack-crds) to download the CRDS. Then ran below command to fix this issue . This updated the CRD

>  **kubectl patch crd dbinstances.rds.services.k8s.aws --patch-file rds.services.k8s.aws_dbinstances.yaml**

I got in touch with #aws-controllers-k8s channel on the Kubernetes Slack community

Heard from ppl that the **CRD** is backward compatible But it's not . Bcoz the OLD crd was missing some SPEC information like `caCertificateIdentifier` & `StorageThroughPut`

So which means do i have to fix using the patch command . Please advise

**Environment**

* Using EKS (yes/no), if so version?  
1.24
* AWS service targeted (S3, RDS, etc.) 
RDS

**Comment by aberle** [comment]
I am seeing the same issue with version `1.1.5`. I installed version `0.0.27` and I see the ConfigMap getting correctly patched. I followed the steps in [this tutorial](https://aws-controllers-k8s.github.io/community/docs/tutorials/rds-example/) exactly and it only worked with version `0.0.27`. I haven't tried other versions yet, I just picked `0.0.27` since that's the version that the linked tutorial mentions.
