### ISSUE TITLE
Failing e2e prow jobs for all controllers

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1848]
Currently, all the e2e tests prow jobs are failing for all controllers: https://prow.ack.aws.dev/

Sample logs: https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_lambda-controller/103/lambda-kind-e2e/1681363420122714112

/priority critical-urgent

**Comment by A-Hilaly** [comment]
My first impression is that this might be related to the python-pip version 
/cc @RedbackThomson @jljaco

**Comment by A-Hilaly** [comment]
python-pip 23.2 was released 4 days ago - we started seeing failures since then. https://pypi.org/project/pip/23.2/

**Comment by a-hilaly** [comment]
Instructions on how to fix this https://kubernetes.slack.com/archives/C0402D8JJS1/p1689795748826559?thread_ts=1689703915.721729&cid=C0402D8JJS1

**Comment by msvechla** [comment]
@a-hilaly thanks, I updated my PR!
