### ISSUE TITLE
New UpdateAssumeRolePolicy is causing unexpected spike in cloudtrail events/cost

### ISSUE THREAD

**Issue by twstewart42** [aws-controllers-k8s/community#1869]
**Describe the bug**
Since my team rolled out the update to [ack-iam-controller 1.2.1](https://github.com/aws-controllers-k8s/iam-controller/releases/tag/v1.2.1) and maybe related to [this issue](https://github.com/aws-controllers-k8s/community/issues/1765). we've noticed a big uptick in guardDuty/cloudtrail events for UpdateAssumeRolePolicy on any IAM Role controlled by this controller. The controller is sending an update request every second for every role. We have ~7 unique Roles generated by this controller. This change has doubled our guardDuty bill from the previous month.

redacted screenshot of activity

![Screenshot 2023-08-04 at 2 12 04 PM](https://github.com/aws-controllers-k8s/community/assets/5286873/d3ece46d-883b-4d36-aac3-eb8bfc77a8f6)

**Steps to reproduce**
Deploy an IAM role associated with the ack-iam-controller. View cloudtrail events filtered on event name = UpdateAssumeRolePolicy

**Expected outcome**
A way to tune how often the controller is attempting to update IAM roles or slow down how often the controller is sending an Update command to these IAM roles.

**Environment**

* Kubernetes version 1.27
* Using EKS (yes/no), if so version? yes. 1.27
* AWS service targeted (S3, RDS, etc.) IAM

**Comment by jaikanth-arcadia** [comment]
Related to #1837
AWS API minifies the JSON while the CRD definition has the pretty formatted version of JSON.

**Comment by a-hilaly** [comment]
Hey @jaikanth-arcadia @twstewart42 i'm currently working on fixing this, expect a new release by end of this week.
/assign

**Comment by a-hilaly** [comment]
@jaikanth-arcadia @twstewart42 expect a release in the upcoming days.. once https://github.com/aws-controllers-k8s/iam-controller/pull/85 is merged ship a new release.

**Comment by universam1** [comment]
@a-hilaly This turns out to be a major issue causing our CI to fail since we are monitoring the status `ACK.ResourceSynced` to pass.
Is it possible to bump the priority of the fix?

**Comment by a-hilaly** [comment]
Fixed in `iam-controller` 1.3.1
/close
