### ISSUE TITLE
ECR: policy is not set in some cases

### ISSUE THREAD

**Issue by jackivanov** [aws-controllers-k8s/community#1873]
**Describe the bug**
We've noticed that the ECR repo policy is not set upon repository creation if **encryptionConfiguration**, **imageScanningConfiguration** and **imageTagMutability** are present in the spec. If the spec doesn't have either of the mentioned attributes the policy is set normally. Also the policy is updated according to the spec after controller restart.

**Steps to reproduce**
```
apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  name: test-repo-01
  namespace: ecr-controller
spec:
  encryptionConfiguration:
    encryptionType: "AES256"
  imageScanningConfiguration:
    scanOnPush: true
  imageTagMutability: IMMUTABLE
  name: test-repo-01
  registryID: "1111111111111111"
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "Test",
          "Effect": "Allow",
          "Principal": {
            "AWS": [
              "arn:aws:iam::000000000000:root"
            ]
          },
          "Action": [
            "ecr:*"
          ]
        }
      ]
    }
```

```
% aws ecr get-repository-policy --repository-name test-repo-01

An error occurred (RepositoryPolicyNotFoundException) when calling the GetRepositoryPolicy operation: Repository policy does not exist for the repository with name 'test-repo-01' in the registry with id '1111111111111111'
````

**Expected outcome**
The policy should be always set normally

**Environment**

ecr-controller:1.0.5

* Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954"
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17"
```
Client version is irrelevant, we tried to use different clients

* Using EKS (yes/no), if so version? **No**

* AWS service targeted (S3, RDS, etc.): **ECR**

**Comment by a-hilaly** [comment]
@jackivanov We just released ecr-controller v1.0.9 to address this issue. Can you give it a shot and share if it's working properly for you?
