### ISSUE TITLE
S3 controller - it is not clear how to create the bucket in different region

### ISSUE THREAD

**Issue by gecube** [aws-controllers-k8s/community#1877]
Hello!

Right now I can easily create a S3 buckets with the help of S3 controller like a simple YAML:

```
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: my-bucket
spec:
  name: my-bucket
  publicAccessBlock:
    blockPublicACLs: true
    blockPublicPolicy: true
    ignorePublicACLs: true
    restrictPublicBuckets: true
  logging:
    loggingEnabled:
      targetBucket: "log-access"
      targetPrefix: ""
  objectLockEnabledForBucket: true
  versioning:
    status: Enabled
  policy: >
    {
      "Id": "DenyNonSSL",
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "AllowSSLRequestsOnly",
          "Action": "s3:*",
          "Effect": "Deny",
          "Resource": [
            "arn:aws:s3:::my-bucket",
            "arn:aws:s3:::my-bucket/*"
          ],
          "Condition": {
            "Bool": {
              "aws:SecureTransport": "false"
            }
          },
          "Principal": "*"
        }
      ]
    }
```

Unfortunately, the bucket can be created only in the same region as S3 controller is running. I am seeking the way how to create a bucket in different region without creating the separate instance of S3 controller. I will appreciate any assistance.

**Comment by gecube** [comment]
Please discard. I accidentally found good documentation page: https://aws-controllers-k8s.github.io/community/docs/user-docs/multi-region-resource-management/
I will try in next few hours. I wonder why it was not highlighted...

**Comment by a-hilaly** [comment]
Normally you'll have to add an annotation like
```us-east-1
  annotations:
    services.k8s.aws/region: us-east-1
```
I'm not sure if you also have to configure https://github.com/aws-controllers-k8s/s3-controller/blob/main/apis/v1alpha1/bucket.go#L41C29-L41C54

**Comment by gecube** [comment]
@a-hilaly thanks, the annotations is working. Regarding the `CreateBucketConfiguration` - I did not find the proper examples.

**Comment by gecube** [comment]
@a-hilaly Thanks for the link to the docs. Unfortunately, it is not enough. For instance, many parameters defined like a "string", but in fact only accept values like "Enabled"/"Disabled" or some other options... So every time I need to refer to terraform, cloud formation and other documentation to get idea which parameters are allowed.

**Comment by a-hilaly** [comment]
@gecube  I understand :) - since the docs are fully generated is very hard for us to put specific enums/examples for every resource per controller. I personally refer to the AWS API documentation, for example you can read more about the possible values for `LocationConstraints` here https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#AmazonS3-CreateBucket-request-LocationConstraint
