### ISSUE TITLE
EC2 controller needs to support Internet Gateway and route table Association

### ISSUE THREAD

**Issue by nnbu** [aws-controllers-k8s/community#1892]
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateRouteTable.html 
This api allows setting association of internet gateway and route table in a VPC. EC2 controller needs to support this functionality.

**Comment by nnbu** [comment]
I will work on this if this is accepted as valid feature request

**Comment by a-hilaly** [comment]
Does this mean that we need add a new "Association" field to one of the existing CRs? i see that multiple parameters are defined in `AssociateRouteTable` call request: `SubnetId`, `GatewayId`, `RouteTableID`. Only `RouteTableID`is required.

**Comment by nnbu** [comment]
The implementation could be similar to what subnet resource has. It adds [RouteTables](https://github.com/aws-controllers-k8s/ec2-controller/blob/685cd7e0fec41dc0d7c9563f3e1c8e0a69a4c52d/apis/v1alpha1/subnet.go#L67) field in it for the association. and association is done [here](https://github.com/aws-controllers-k8s/ec2-controller/blob/685cd7e0fec41dc0d7c9563f3e1c8e0a69a4c52d/pkg/resource/subnet/hooks.go#L267)

Similarly, we could have RouteTables field in [InternetGatewaySpec](https://github.com/aws-controllers-k8s/ec2-controller/blob/685cd7e0fec41dc0d7c9563f3e1c8e0a69a4c52d/apis/v1alpha1/internet_gateway.go#L26) and implement the association of gateway and RouteTable.

**Comment by nnbu** [comment]
Fixed
