### ISSUE TITLE
Add the ability to export a DSN for all datastore controllers

### ISSUE THREAD

**Issue by jose-fully-ported** [aws-controllers-k8s/community#1921]
**Is your feature request related to a problem?**

My applications all expect a Database URL in DSN format (`scheme://user:password@host:port/database`). This functionality is fairly common amongst modern web frameworks, and provides developers the ability to skip configuration in many cases.

Currently, I need to manually construct a DSN when connecting to RDS using the provided FieldExport functionality. It would be great to not need to do this, as sometimes I need to write a wrapper script to pass the argument properly (when the DSN is expected via flag/env var) or vendor the codebase to write a custom Dockerfile in cases where I am installing third-party software.

**Describe the solution you'd like**

I would like all datastores (Elasticache, Redis, DynamoDB, etc.) to provide a `URL` FieldExport. This would collate the existing config in the correct format so I can display this to my app automatically.

**Describe alternatives you've considered**

My alternative atm is to either do this in code (blech) or somehow write a custom controller that watches for the desired secrets and does this for me based on other secrets.

**Comment by a-hilaly** [comment]
Somewhat related to https://github.com/aws-controllers-k8s/community/issues/1542 and https://github.com/aws-controllers-k8s/community/issues/1417 -  we shouldn't solve this at the ACK controller's level.
