### ISSUE TITLE
Turning on enableIAMDatabaseAuthentication after the DBCluster creation has no effect

### ISSUE THREAD

**Issue by pciang** [aws-controllers-k8s/community#1937]
**Describe the bug**

Turning on `enableIAMDatabaseAuthentication` after the DBCluster creation has no effect.

**Steps to reproduce**

1. Create a valid DBCluster resource with `spec.enableIAMDatabaseAuthentication` turned off. (I was using `aurora-postgresql` engine version `12.15`)
2. Wait until the actual DB cluster has been created in the AWS cloud
3. Turn on `spec.enableIAMDatabaseAuthentication` after that

**Expected outcome**

IAM database authn should be enabled after the step (3) above.

**Environment**

* Kubernetes version `v1.25.14-eks-f8587cb`
* Using EKS (yes), version `v1.25.14-eks-f8587cb`
* AWS service targeted: RDS

**Comment by gecube** [comment]
@pciang Hi! What's going on in RDS controller logs? Could you kindly share them here?

**Comment by arjunrn** [comment]
https://github.com/aws-controllers-k8s/rds-controller/pull/159

**Comment by a-hilaly** [comment]
https://github.com/aws-controllers-k8s/rds-controller/pull/159 is merged rds-controller 1.1.8 has just been released. Thanks for your contribution @arjunrn !
/close
