### ISSUE TITLE
Ability to configure Amazon SQS key (SSE-SQS) as encryptuon key type

### ISSUE THREAD

**Issue by karthichu** [aws-controllers-k8s/community#1942]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]
We have already provisioned few SQS queues manually in production whiich we need to own through controller, however to our surpirse we found that it does not have an option to configure encryption type as Amazon SQS key (SSE-SQS)

**Describe the solution you'd like**
A description of what you want to happen.
A spec to configure encryption on/off with capability to configure Amazon SQS key (SSE-SQS) as encryptuon type.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
Manual configuration after the queue is managed while owning this queue without this config.

**Comment by a-hilaly** [comment]
This is now fixed in [sqs-controller v1.1.0](https://github.com/aws-controllers-k8s/sqs-controller/releases/tag/v1.1.0)
