### ISSUE TITLE
Add `VPCPeeringConnection` support to ec2-controller

### ISSUE THREAD

**Issue by a-hilaly** [aws-controllers-k8s/community#1943]
The current state of the `ec2-controller` lacks support for managing VPC Peering Connections. This feature request aims to enhance the capabilities of the ec2-controller by adding comprehensive support for creating, updating, deleting, and accepting VPC Peering Connections.
API definitions:
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcPeeringConnection.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteVpcPeeringConnection.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AcceptVpcPeeringConnection.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcPeeringConnectionOptions.html

**Comment by marcdavoli** [comment]
A bit of additional context:

This PR adds the `VpcPeeringConnection` custom resource and covers the standard API lifecycle CRUD operations.
- https://github.com/aws-controllers-k8s/ec2-controller/pull/158

<br>

This PR adds an enhancement to the `VPC` custom resource to allow it to Accept or Reject VPC Peering Connection coming from allow-listed or block-listed VPC IDs.
- https://github.com/aws-controllers-k8s/ec2-controller/pull/159

**Comment by marcdavoli** [comment]
I'll try to be at the meeting tomorrow to discuss this PR:
https://github.com/aws-controllers-k8s/ec2-controller/pull/159 

But given the original purpose of this Issue, I think we can close it.
