### ISSUE TITLE
Errors with AdoptedResources for flowlog and securitygroup ec2 resources

### ISSUE THREAD

**Issue by alan-j-byrne** [aws-controllers-k8s/community#1946]
**Describe the bug**
The Adopted Resources reconciller errors out when trying to adopt flowlog.ec2.services.k8s.aws or securitygroup.ec2.services.k8s.aws resources.

**Steps to reproduce**
Flowlog:
spec.aws.nameOrID: fl-xxxx
spec.kubernetes.group: ec2.services.k8s.aws
spec.kubernetes.kind: FlowLog
"error": "FlowLog.ec2.services.k8s.aws \"my-resource\" is invalid: [spec.resourceID: Required value, spec.resourceType: Required value]"}

SecurityGroup:
spec.aws.nameOrID: sg-xxx
spec.kubernetes.group: ec2.services.k8s.aws
spec.kubernetes.kind: SecurityGroup
"error": "SecurityGroup.ec2.services.k8s.aws \"my-resource\" is invalid: spec.name: Required value"}

It appears in both cases, the adopted resources reconciller is trying to create invalid resources for flowlog and securitygroup.

**Expected outcome**
SecurityGroup and FlowLog kind resources should be automatically created by the adoptedresources reconciller.

**Environment**

* Kubernetes version v1.27.3
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.), securitygroup.ec2 & flowlog.ec2

**Comment by nnbu** [comment]
The error
```
"error": "FlowLog.ec2.services.k8s.aws "my-resource" is invalid: [spec.resourceID: Required value, spec.resourceType: Required value]"}
```
comes from following code
https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/adoption_reconciler.go#L157

I will identify a fix for this
