### ISSUE TITLE
Launch template

### ISSUE THREAD

**Issue by speedfl** [aws-controllers-k8s/community#1952]
**Is your feature request related to a problem?**
When using EKS node groups the tags are not propagated to the instances. For that you need to specify a launch template.
https://doc.crds.dev/github.com/aws-controllers-k8s/eks-controller/eks.services.k8s.aws/Nodegroup/v1alpha1@v1.0.2

This launch template cannot be created using the controller which makes it unusabled when you need to add dedicated tags

**Describe the solution you'd like**
launch template should be created using the controller and then referenced using NodeGroup

**Describe alternatives you've considered**
Crossplane is proposing this feature.

**Comment by a-hilaly** [comment]
We already have two PRs introducing [EC2 Launch template](https://github.com/aws-controllers-k8s/ec2-controller/pull/151)s and [Launch templates versions](https://github.com/aws-controllers-k8s/ec2-controller/pull/155). Once these are merged we can enable cross-controller resources references for this field
