### ISSUE TITLE
EKS Pod Identity causes restart

### ISSUE THREAD

**Issue by stefanmcshane** [aws-controllers-k8s/community#1953]
**Describe the bug**

I just enabled EKS Pod identity to attempt to run the controllers with a service account. 
Everything has been setup on the EKS side fine (using same role that has all the correct permissions), but I get the following error on startup:
Ignoring, HTTP credential provider invalid endpoint host, "169.254.170.23", only loopback hosts are allowed

I dug in a little and found that this error is returned from aws-sdk-go v1 only.
[169.254.170.23 is an EKS address](https://github.com/aws/aws-sdk-go/blob/074b1dfaa25f8a28efdc673a1c4490a8b2327b82/aws/defaults/defaults.go#L131), which is valid and expected.
There are open issues on the [SDK](https://github.com/aws/aws-sdk-go/issues/4436) which suggest that using session.New is the cause of the issue, however it seems that [we are using session.NewSession](https://github.com/aws-controllers-k8s/runtime/blob/3b1e4813c162b0dc4f3c241141b5009ec0a41c5b/pkg/runtime/reconciler.go#L162) (if I am understand the flow correctly).
In theory from the pods perspective, this should work the exact same as the irsa.

I am able to get the pod to run using IRSA/OIDC on the same service account, and I can see that the eks pod identity token is mounted into the pod also, so the controller and association is working fine.

I wasnt running the OIDC controller at the same time, to ensure that there were no conflicts

**Steps to reproduce**

- Create role in AWS with trust policy service including `pods.eks.amazonaws.com` 
- Enable EKS Pod Identity Addon (EKS console)
- Enable EKS Pod Identity Association on EKS console, mapping to iam controller service account
- Restart IAM controller

**Expected outcome**
IAM controller restarts, authenticating as the mapped role.

**Environment**

* Kubernetes version -1.24, 1.27 (tried on both)
* Using EKS (yes/no), if so version? yes
* AWS service targeted (S3, RDS, etc.) IAM

**Comment by a-hilaly** [comment]
Hi @stefanmcshane - this should be resolved in the latest eks-controller release.

**Comment by countbytedown** [comment]
Is there a work around for this? I'm using -> https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/addons/external-dns/ and running into the same issue. Is there something I can do with the underlying chart for the external_dns controller or is this associated with the managed control plane in EKS?

**Comment by a-hilaly** [comment]
Hello @countbytedown, it seems this is linked to k8s external-dns. For compatibility with pod identity, they need to ensure that the `external-dns` controller is using an up-to-date version of `aws-sdk-go` library. They recently updated their aws-sdk-go [two weeks ago](https://github.com/kubernetes-sigs/external-dns/commit/cfd16acca70df21e3d43b1517ac5fa57dc5b8a62) but their last release (0.14.0) was in November 2023. I'd recommend to reach out and ask for a release cut: https://github.com/kubernetes-sigs/external-dns/issues

**Comment by countbytedown** [comment]
Thanks very much @a-hilaly , I'll do that. 
Regards
