### ISSUE TITLE
Updating function's architectures parameter is not recognized by lambda-controller

### ISSUE THREAD

**Issue by eugenyuk** [aws-controllers-k8s/community#1971]
**Describe the bug**
Updating `architectures` parameter is not recognized by lambda-controller

**Steps to reproduce**
1. Specify function's `architectures' parameter
2. Trigger the update with ACK

**Expected outcome**
lambda-controller redeploys function with specified architectures parameter.

**Environment**
* Kubernetes version: 1.27
* EKS version: eks.10

**Additional Notes**
After `Function` CRD updated, lambda-controller doesn't see this change:
```
{"level":"debug","ts":"2023-12-26T22:41:57.997Z","logger":"ackrt","msg":"no difference found between metadata and spec for desired and latest object.","account":"1234567890","role":"","region":"eu-wes
t-1","kind":"Function","namespace":"infra","name":"lambda-function-test-v1","is_adopted":false,"generation":14}
```

**Comment by carlturnerfs** [comment]
A similar issue also seems to affect other parameters, such as `imageConfig` overrides for `entrypoint` and `command`. The controller doesn't seem to notice any diff. (I also once thought I observed some weird behaviour involving `vpcConfig` but haven't been able to recreate it.)

**Comment by Vandita2020** [comment]
@carlturnerfs there is another issue (https://github.com/aws-controllers-k8s/community/issues/2051) open for `imageConfig` we are going to handle it there.
