### ISSUE TITLE
ACK EKS does not update the NodeGroup tags

### ISSUE THREAD

**Issue by speedfl** [aws-controllers-k8s/community#1985]
**Describe the bug**
When updating tags on the NodeGroup, the NodeGroup in AWS is not updated. The rest of the fields is working.
Probably because tagging in AWS is another api call

**Steps to reproduce**

- Create a NodeGroup with:
  - tags   `tagone=toto` and `tagtwo=tutu`
  - labels `tagone=toto` and `tagtwo=tutu`
- Update tag and label `tagone=tata` 
- Observe in AWS the NodeGroup labels are updated but not the tags

**Expected outcome**
Tags must be updated

**Environment**

* Kubernetes version 1.24
* Using EKS (yes/no), if so version?  eks.15
* AWS service targeted (S3, RDS, etc.) eks NodeGroup 1.1.1

**Comment by a-hilaly** [comment]
Currently none of the eks-controller CRDs support tag updates.. It should be doable with some copy pasta from other controllers. @speedfl interested into working on this? other wise i'll get into it once we ship `AccessEntry` CRD

**Comment by a-hilaly** [comment]
AccessEntries will come with tag support.. Tags update code is here https://github.com/aws-controllers-k8s/eks-controller/pull/84

**Comment by a-hilaly** [comment]
@speedfl This should be supported now - for all eks-controller resources.
/close
