### ISSUE TITLE
Not able to use IAM controller when nodes are run in private vpc subnet

### ISSUE THREAD

**Issue by vivekskrishna** [aws-controllers-k8s/community#1997]
**Is your feature request related to a problem?**
When running the EKS in a private subnet and trying to use the IAM controller, i get error that the controller is not able to connect to https://iam.amazonaws.com and as of now there is not possibility to create a VPC endpoint for IAM

**Describe the solution you'd like**
If this controller needs to be used realistically, we would need support for reaching IAM url from private subnet as I dont think too many people will run a EKS cluster in a public subnet. So one possible solution is to enable vpc endpoint for IAM or come up with some other mechanism for this.

**Describe alternatives you've considered**
I cant think of any otehr way to make it work.

**Comment by a-hilaly** [comment]
Hi @vivekskrishna - currently, all the ACK controllers support setting custom URL endpoints: https://github.com/aws-controllers-k8s/iam-controller/blob/main/helm/values.yaml#L89

**Comment by vivekskrishna** [comment]
dThanks for the reply. Does it support connecting to aws endpoint via a proxy. We use a proxy which needs a certificate based authentication to allow connectivity to internet. is it something that the controller will support if i set the env variables like http_proxy etc?

**Comment by vivekskrishna** [comment]
I was able to make it work via a proxy by using http_proxy, https_proxy, no_proxy and aws_ca_bundle env variables in deployment. thank you for your help. this can be closed.
