### ISSUE TITLE
Kubernetes native way to consume CustomResources

### ISSUE THREAD

**Issue by martin-ducar-gd** [aws-controllers-k8s/community#20]
Default functionality in K8s is to contact an Application by its Service DNS. To Contact AWS resources created in K8s it would be also great to have this native like functionality, If I own service A and it requires S3 bucket B which is created together in same namespace it would be great to be able to just point to bucket B and the DNS takes care of translating it to aws url. Have you thought about such feature?

The other alternative which is easy to implement and I assume that would be first iteration is that parameters of the AWS object are just added to the Custom Resource but to use such object then in an application the application must be K8s aware.

**Comment by mhausenblas** [comment]
Thanks for raising this issue @martin-ducar-gd and I'd say it would make sense for ASO to support it, not sure if we'll  get it into the MVP scope, though. I'll create the MVP issue later today and reference it from there.

**Comment by jaypipes** [comment]
Related: https://github.com/aws/aws-controllers-k8s/issues/292

**Comment by A-Hilaly** [comment]
related to https://github.com/aws-controllers-k8s/community/pull/1057
/remove-lifecycle stale

**Comment by vijtrip2** [comment]
closing in favor of https://github.com/aws-controllers-k8s/community/issues/740
