### ISSUE TITLE
ack-iam-controller: Role not created when watchNamespace leaved empty since 1.3.3

### ISSUE THREAD

**Issue by derbauer97** [aws-controllers-k8s/community#2006]
**Describe the bug**
Since 1.3.3 of the iam controller helm chart the following condition prevents the creation of the RBAC Role if installScope is namespace and watchNamespace ist empty.

This leads to permissions error of the ack controller cause the pod is not allowed to list crd ressource:

{"level":"error","ts":"2024-01-30T11:52:55.477Z","msg":"pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.OpenIDConnectProvider: failed to list *v1alpha1.OpenIDConnectProvider: openidconnectproviders.iam.services.k8s.aws is forbidden: User \"system:serviceaccount:system-ack-iam:ack-iam-controller\" cannot list resource \"openidconnectproviders\" in API group \"iam.services.k8s.aws\" in the namespace \"system-ack-iam\"\n","stacktrace":"k8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\t/go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:147\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:292\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:227\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\t/go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:290\nk8s.io/client-go/tools/cache.(*controller).Run.(*Group).StartWithChannel.func2\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/wait.go:55\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/wait.go:72"}

**Steps to reproduce**

Install ack-iam-controller 1.3.3 with watchNamespace leaving at "" and installScope: namespace

**Expected outcome**

Role is created always for the releaseNamespace as the description states.

**Environment**

* Kubernetes version 1.24
* Using EKS (yes/no), if so version? yes 1.24
* AWS service targeted (S3, RDS, etc.) IAM

**Comment by derbauer97** [comment]
This is caused by this condition which leads to false with the default value watchNamespace: "" https://github.com/aws-controllers-k8s/iam-controller/blob/v1.3.3/helm/templates/cluster-role-controller.yaml#L13

Additonally, i found that there are two new roles iam-reader and iam-writer but no RoleBidning to bind them to the iam controller.

**Comment by a-hilaly** [comment]
@derbauer97 The release namespace and the watchname space are two different things. Are you asking that we default to the release namespace is watchNamespace is not provided? that sounds reasonable to me.

**Comment by a-hilaly** [comment]
Also note that before making this release we also discovered an unintended behaviour described here https://github.com/aws-controllers-k8s/community/issues/1996

**Comment by derbauer97** [comment]
Hey @a-hilaly,

thanks for the quick response. I would expect that the controller works with the default values and if i trust the description above watchNamespace it should work withput specifying watchNamespaces:

```
# This value is only used when the `installScope` is set to "namespace". If left empty, the default value is the release namespace for the chart.

https://github.com/aws-controllers-k8s/iam-controller/blob/main/helm/values.yaml#L109C1
```

So like you mentioned it would be great to always include the releaseNamespace if watchNamespace is emtpy

**Comment by a-hilaly** [comment]
@derbauer97 Nice catch, i completely missed that part of the documentation .. i will expedite a release for all controllers very soon!

**Comment by a-hilaly** [comment]
@derbauer97 iam-controller have been patched!
/close
