### ISSUE TITLE
[SecurityGroups] Add support for `securityGroupRef` and `vpcRef` settings inside the `userIDGroupPairs`

### ISSUE THREAD

**Issue by adriananeci** [aws-controllers-k8s/community#2059]
**Is your feature request related to a problem?**

Add support for `securityGroupRef` and `vpcRef` settings inside the `userIDGroupPairs` of a SecurityGroup object

**Describe the solution you'd like**

We are creating/grouping multiple SecurityGroups ACK objects into a single helm chart, along with other ACK objects (VPC, Subnets, etc). Some of these SGs need to be referenced in other SGs that are part of the same chart. Based on https://aws-controllers-k8s.github.io/community/reference/ec2/v1alpha1/securitygroup/ there are few options via `userIDGroupPairs` when a SG needs to be referenced in another SG: `groupID` or `groupName`. Given the SG ID is not known beforehand the only option left in this case is `groupName`. But in order to use the `groupName` option we'll also need to pass the VPC ID is again is not know beforehand since the VPC object creation is part of the same helm chart.

**Describe alternatives you've considered**

https://github.com/aws-controllers-k8s/community/issues/2058

**Comment by a-hilaly** [comment]
@adriananeci thank you for reporting this! Shipping a release soon :)

**Comment by adriananeci** [comment]
Closing as https://github.com/aws-controllers-k8s/ec2-controller/pull/187 was released
