### ISSUE TITLE
DynamoDB service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#206]
## New ACK service controller

Support for Amazon DynamoDB.

### List of API resources

List the API resources in order of importance to you:

* [Table](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html)
* [GlobalTable](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateGlobalTable.html)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
