### ISSUE TITLE
APIGatewayv2 service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#207]
## New ACK service controller

Support for Amazon API Gateway v2.

### List of API resources

List the API resources in order of importance to you:

* [API](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis.html#CreateApi)
* [VPCLink](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/vpclinks.html#CreateVpcLink)
* [APIMapping](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/domainnames-domainname-apimappings.html#CreateApiMapping)
* [Authorizer](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers.html#CreateAuthorizer)
* [Deployment](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-deployments.html#CreateDeployment)
* [DomainName](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/domainnames.html#CreateDomainName)
* [Integration](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-integrations.html#CreateIntegration)
* [IntegrationResponse](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-integrations-integrationid-integrationresponses.html#CreateIntegrationResponse)
* [Model](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-models.html#CreateModel)
* [Route](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-routes.html#CreateRoute)
* [RouteResponse](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-routes-routeid-routeresponses.html#CreateRouteResponse)
* [Stage](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-stages.html#CreateStage)

**Comment by wszarmach-koia** [comment]
Could someone tell me whether there are plans to consider the controller as generally available any time soon ?

**Comment by vijtrip2** [comment]
> Could someone tell me whether there are plans to consider the controller as generally available any time soon ?

Hi @wszarmach-koia , thanks for reaching out! We definitely want to graduate all our service controllers to GA in future. 
Unfortunately, I cannot give you specific date but ACK team will reach out to APIGateway team next year regarding promoting controller to GA.

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
