### ISSUE TITLE
ECR service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#208]
## New ACK service controller

Support for Amazon ECR.

### List of API resources

List the API resources in order of importance to you:

* [Repository](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
