### ISSUE TITLE
Multi-account deployment for AWS Lambda Controller for Kubernetes

### ISSUE THREAD

**Issue by blueacidification** [aws-controllers-k8s/community#2099]
**Is your feature request related to a problem?**
My org has multiple aws accounts. I don't want one controller on each eks cluster per account. I'd rather have one central controller on one eks in one account deploying lambda functions to multiple accounts.

**Describe the solution you'd like**
Have one central controller on one cluster in one account, deploying lambda functions on multiple accounts.

**Describe alternatives you've considered**
One controller on each eks cluster per account.

**Comment by a-hilaly** [comment]
@blueacidification a controller can deploy resources to multiple AWS acocunt, checkout CARM feature: https://aws-controllers-k8s.github.io/community/docs/user-docs/cross-account-resource-management/

**Comment by blueacidification** [comment]
I see. Thanks for the response. :)
