### ISSUE TITLE
AMP controller keeps creating new workspace when restoring from Velero backup 

### ISSUE THREAD

**Issue by twang418** [aws-controllers-k8s/community#2105]
**Describe the bug**
AMP controller creates a new AMP workspace during Velero restoration 

**Steps to reproduce**
- delete AMP CR, while keep the ACK controller running
- run `velero create restore` to restore the AMP CR (even with `--status-include-resources workspaces.prometheusservice.services.k8s.aws` to restore the status)

**Expected outcome**
- ACK controller will keep use the existing AMP

**Environment**
* Kubernetes version: 1.28.9
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.): AMP

**workaround**
- need to scale down the ACK controller deployment to 0 before the CR is restored and scale it back afterward

**Comment by a-hilaly** [comment]
Hi @twang418 thank you for reporting this. It looks like the prometheusservice-controller uses the `status.workspaceID` to track whether a workspace exists or not (https://github.com/aws-controllers-k8s/prometheusservice-controller/blob/main/pkg/resource/workspace/sdk.go#L152-L154).

>delete AMP CR, while keep the ACK controller running

If you delete an AMP CR "while" the controller is running, the controller will delete from AWS. I guess you would want to delete it using `retain` mode. Checkout https://aws-controllers-k8s.github.io/community/docs/user-docs/deletion-policy/

**Comment by twang418** [comment]
Thanks for your response, @a-hilaly 
I got my answer from the slack channel. 
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/00e5df8e-6da4-48db-81d3-434911619008">

It would be nice if https://github.com/aws-controllers-k8s/community/issues/1381 get implemented, so that we don't need to remember this ordering issue
