### ISSUE TITLE
SSM first release

### ISSUE THREAD

**Issue by leecalcote** [aws-controllers-k8s/community#2109]
Hi,

Will the SSM-Controller project be released in the near-term?

Context:

The CNCF project, [Meshery](https://meshery.io), enables collaborative design and operation of cloud and cloud native infrastructure. In doing so, it integrates ACK and incorporates each controller's CRDs into Meshery [models](https://docs.meshery.io/concepts/logical/models).

Each Meshery model is versioned and relies on versioned CRDs (released) in order to provider compatibility guarantees to users. 

Thanks for considering this question.

\- Lee

**Comment by a-hilaly** [comment]
duplicated of https://github.com/aws-controllers-k8s/community/issues/485
