### ISSUE TITLE
Don't exit the controller container when the credential validation fails.

### ISSUE THREAD

**Issue by rahtr** [aws-controllers-k8s/community#2111]
**Is your feature request related to a problem?**

With the current setup, AWS credentials are validated when the controller starts, checking details like the region and account ID. If validation fails, the controller exits, retries, and eventually enters a `CrashLoopBackOff` state. In environments using auto-sync tools like ArgoCD, this leads to the application degrading, triggering alerts and requiring intervention. This is particularly challenging in multi-tenant environments where different teams handle different tasks. For instance, an ACK controller admin team might deploy the controller without providing the credentials, while service teams are responsible for setting up their namespaces with the necessary service accounts and configmaps.
**Describe the solution you'd like**
We could possible do something like this:

- We could just stdout errors in the controller for invalid credential.
- For a CARM based implementation, the controller should just keep watching for the namespaces with the ACK annotations.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by michaelhtm** [comment]
Hi @rahtr,
Thanks for reaching out about your issue and suggesting a solution. We looked into it, but unfortunately, it wouldn't work as intended with CARM. The system is designed to use the main provided credentials to call STS::AssumeRole and switch between roles in the config maps. Not using a default Account number is not possible.
Let us know if you have any other questions or concerns.
