### ISSUE TITLE
SQS resource MissingParameter error

### ISSUE THREAD

**Issue by omri-shilton** [aws-controllers-k8s/community#2139]
**Describe the bug**
when creating a SQS resource im getting this error in the status message
MissingParameter: The request must contain the parameter Attribute.Name.\n\tstatus code: 400, request id: db047e34-c891-50a8-8b3a-210f137c5f41

**Steps to reproduce**
create an sqs resource

**Expected outcome**
not getting this error

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.) SQS

**Comment by a-hilaly** [comment]
Hi @omri-shilton can you please provide an SQS manifest sample?

**Comment by driv** [comment]
I'm getting the same issue with `image: public.ecr.aws/aws-controllers-k8s/sqs-controller:1.0.16 `

**Comment by driv** [comment]
Should an issue be opened in https://github.com/aws-controllers-k8s/sqs-controller ?

**Comment by a-hilaly** [comment]
I was able to reproduce locally... working on patch for this.

**Comment by a-hilaly** [comment]
This is now fixed in [sqs-controller v1.1.0](https://github.com/aws-controllers-k8s/sqs-controller/releases/tag/v1.1.0)
