### ISSUE TITLE
Expose Finalizer String as Public Constant in AWS Controllers for Kubernetes Code Generator

### ISSUE THREAD

**Issue by bugbuilder** [aws-controllers-k8s/community#2201]
**Is your feature request related to a problem?**
It would be great to have the finalizerString exposed. This way, I wouldn't need to manually define the string, for example, "finalizers.route53.services.k8s.aws/HealthCheck", in my custom controller to check if the resource is already being managed, and then add my own finalizer. I have another custom controller that performs some logic after the resource is managed by ACK, and exposing this string would simplify the process.

**Describe the solution you'd like**
Capitalize finalizerString to FinalizerString in the [AWS Controllers for Kubernetes code generator](https://github.com/aws-controllers-k8s/code-generator), making the finalizer string accessible across packages. This would allow external controllers to easily reference the finalizer without redefining it, ensuring consistency and reducing potential errors.

**Describe alternatives you've considered**
none

**Comment by a-hilaly** [comment]
This is a great idea @bugbuilder - currently our finalizers aren't exported https://github.com/aws-controllers-k8s/s3-controller/blob/main/pkg/resource/bucket/descriptor.go#L30-L32 - would like to send a patch to the code generator? it should be a pretty simple addition. Happy to help if needed!
