### ISSUE TITLE
RDS service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#237]
## New ACK Service Controller
Support for Amazon RDS

### List of API resources

List the API resources in order of importance to you:

* [DBInstance](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html)
* [DBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) (Amazon Aurora Serverless)
* [DBProxy](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBProxy.html)

**Comment by rektide** [comment]
There was an interesting ask that crossed my feeds, [about using cloud-native infrastructure to manage users & databases on a legacy/non-cloud postgres](https://retro.social/@freakazoid/104903310704708872).

That seems like a pretty wild use case, but I do think it's important to surface the question of how, if at all, legacy RDS users can migrate to ACK-managed RDS. I proposed that perhaps RDS service controller might be able to seed a new database from an existing databases backup. That way there's some migration into ACK-managed RDS available.

**Comment by jaypipes** [comment]
> There was an interesting ask that crossed my feeds, [about using cloud-native infrastructure to manage users & databases on a legacy/non-cloud postgres](https://retro.social/@freakazoid/104903310704708872).
> 
> That seems like a pretty wild use case, but I do think it's important to surface the question of how, if at all, legacy RDS users can migrate to ACK-managed RDS. I proposed that perhaps RDS service controller might be able to seed a new database from an existing database's backup. That way there's some migration into ACK-managed RDS available.

Hi @rektide! :) Here is a related GH issue around this: #41

**Comment by stevehipwell** [comment]
I'm interested if there has been any discussions around managing multiple DBs and users on a RDS instance? We currently manage this via Terraform but supporting this workflow in a controller would be really useful.

**Comment by PatTheSilent** [comment]
@stevehipwell you could argue that that shouldn't really be a use case for an RDS controller. Mostly because it would mean managing multiple, completely different APIs by the controller. I use a custom PostgesDB operator to do that - users declare what database/user they want created on what Postgres host and the operator manages that. I'd generally recommend a split like that, I've been very happy to use it.

**Comment by stevehipwell** [comment]
@PatTheSilent I don't disagree; which operator are you using?

**Comment by PatTheSilent** [comment]
@stevehipwell I wrote one myself using the Ansible Operator Framework https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/ (not affiliated with them :) ). It wasn't really hard to throw something usable together in a day or two.

**Comment by stevehipwell** [comment]
@PatTheSilent I suspected you might say that. I've been looking for a good community PSQL DB operator for a while now and as Terraform works well enough I haven't been able to prioritise writing my own. Crossplane and the [provider-sql](https://github.com/crossplane-contrib/provider-sql) look like promising leads.

**Comment by PatTheSilent** [comment]
@stevehipwell oh, I didn't know about that. I use crossplane to manage my AWS stuff so that would be a perfect fit (and less maintenance on the long run). Thanks!

**Comment by gazal-k** [comment]
The RDS resources are looking pretty great. Are there any milestones to achieve before it becomes GA?

**Comment by gazal-k** [comment]
Looks like it's pretty close 🙂. If I'm reading that right. Just 1 in progress item and 1 to-do.

We are just waiting on this to be GA to use it in our applications. Right now, cloud infra like RDS and S3 are provisioned separately for our k8s applications.

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
