### ISSUE TITLE
Lambda service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#238]
## New ACK Service Controller

Support for AWS Lambda

### List of API resources

List the API resources in order of importance to you:

* [Function](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html)
* [EventSourceMapping](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
