### ISSUE TITLE
SFN service controller

### ISSUE THREAD

**Issue by tabern** [aws-controllers-k8s/community#239]
## New ACK Service Controller

Support for AWS Step Functions

### List of API resources

List the API resources in order of importance to you:

* [StateMachine](https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html)
* [Activity](https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateActivity.html)

**Comment by russmackenzie** [comment]
Now that the 'sfn' controller and end-to-end test are merged (https://github.com/aws/aws-controllers-k8s/pull/450), should I submit a PR to add Step Functions as 'developer preview' to the Testing and Services pages or are there any other prerequisites?

**Comment by jaypipes** [comment]
@russmackenzie yep. :)

**Comment by russmackenzie** [comment]
I believe this issue can now be closed.

**Comment by jaypipes** [comment]
@russmackenzie we're going to keep these service controller issues open since they are on the Service Controller Roadmap project and provide a good top-level landing page...

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
