### ISSUE TITLE
CloudFront service controller

### ISSUE THREAD

**Issue by akshayvvr** [aws-controllers-k8s/community#249]
## New ACK Service Controller

Support for CloudFront

### List of API resources

List the API resources in order of importance to you:

* [Distribution](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html)
* [CachePolicy](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateCachePolicy.html)

**Comment by jrake-revelant** [comment]
It would be great to get support for CloudFront in ACK.

**Comment by bala151187** [comment]
It would be great to get support for CloudFront in ACK.

**Comment by matheushent** [comment]
any update on this?

**Comment by karthik2491** [comment]
@jaypipes i tried to install the helm chart for cloudfront controller, got below error:
ImagePullBackOff (Back-off pulling image "public.ecr.aws/aws-controllers-k8s/cloudfront-controller:v0.0.0-non-release-version")
Is there a docker image to test this cloudfront controller

**Comment by A-Hilaly** [comment]
@karthik2491 it's a bit expected, we didn't make a release yet. Sending a release PR soon /cc @jaypipes

**Comment by karthik2491** [comment]
@A-Hilaly thanks for confirming , is there any tentative timeline for availability of cloudfront controller for testing

**Comment by jaypipes** [comment]
@karthik2491 probably not for a couple weeks at least. Been fixing RDS and IAM bugs recently...

**Comment by bala151187** [comment]
@jaypipes Any updates on releasing cloudfront ?

**Comment by a-hilaly** [comment]
@bala151187 We're working on this and tracking updates in https://github.com/aws-controllers-k8s/community/issues/1915 and https://github.com/aws-controllers-k8s/community/issues/1914

**Comment by mikestef9** [comment]
Closing as controller is now 1.0

https://github.com/aws-controllers-k8s/cloudfront-controller
