### ISSUE TITLE
EFS service controller

### ISSUE THREAD

**Issue by wreed4** [aws-controllers-k8s/community#328]
## New ACK Service Controller
Support for EFS

### List of API resources

List the API resources in order of importance to you:

* [FileSystem](https://docs.aws.amazon.com/efs/latest/ug/API_CreateFileSystem.html)
* [AccessPoint](https://docs.aws.amazon.com/efs/latest/ug/API_CreateAccessPoint.html)

**Comment by mikestef9** [comment]
Is access point still a priority given EFS CSI driver supports dynamic provisioning of access points? There is also open issue on EFS CSI driver repo for dynamic provisioning of file systems https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/310

**Comment by absmith82** [comment]
IT seems that this Kubernetes-sigs issue has been closed without a resolution to create EFS filesystems.  Currently only EFS access points are able to be created dynamically.  This is still an option that should be looked into, even if the CSI driver does end up implementing it in the future it is something that currently doesn't exist hand there is a need for.

**Comment by a-hilaly** [comment]
The latest version (v0.0.3) of the `efs-controller` is now live, offering CRDs to manage  `FileSystem`, `MountTarget` and `AccessPoint` resources. CRDs Documentation is available here https://aws-controllers-k8s.github.io/community/reference/efs/v1alpha1/filesystem/

cross-controller resource references is also possible with CRs managed by EC2 and KMS controller (Keys, Subnets and SecurityGroups)

---


<img width="1425" alt="Screenshot 2024-02-10 at 22 18 37" src="https://github.com/aws-controllers-k8s/community/assets/10897901/4a7d865c-6be9-4949-b690-b5347a30c8a2">

**Comment by mzeeshan1** [comment]
After creating EFS with ACK, I want to automatically use file system id in storage class. A functionality similar to field export. But filed export only adds data to secrets or configmaps, is there a possibility for me to do this via ACK?

**Comment by mikestef9** [comment]
Closing as controller is now 1.0 

https://github.com/aws-controllers-k8s/efs-controller
