### ISSUE TITLE
SageMaker service controller

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#385]
## New ACK Service Controller
Support for [Amazon Sagemaker](https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html)

There already exists a [custom Kubernetes controller for Sagemaker](https://github.com/aws/amazon-sagemaker-operator-for-k8s). This controller is developed and maintained by the Amazon Sagemaker service team. They would like to eventually deprecate their custom controller and have a Sagemaker ACK service controller replace it.

### List of API resources

List the API resources in order of importance to you:

* [Model](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModel.html)
* [EndpointConfig](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpointConfig.html)
* [HyperParameterTuningJob](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateHyperParameterTuningJob.html)

Other items specific to Sagemaker here:

- Outline an approach to migrate CR data from the original Sagemaker Kubernetes controller to the ACK one

**Comment by surajkota** [comment]
V0.0.1 released

**Comment by akartsky** [comment]
v0.3.0 Released

ACK SageMaker is now GA and is marked stable 
https://github.com/aws-controllers-k8s/sagemaker-controller/releases
