### ISSUE TITLE
Test framework for long-running "soak" testing to ensure controller reliability and stability

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#440]
**Is your feature request related to a problem?**
This feature request is to have a test framework for long-running "soak" testing to ensure controller reliability and stability

**Describe the solution you'd like**
Test framework which enables long-running "soak" testing for ACK controller to ensure controller reliability and stability
Documentation on creating corresponding test suite, setting up, running, collecting results of test run.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by vijtrip2** [comment]
Started the draft: https://quip-amazon.com/aPJPAF76lijS/DRAFT-ACK-Soak-Test-Framework

**Comment by vijtrip2** [comment]
Feedback from service teams after demoing the initial implementation of soak-test runner.
1. Add prerequisite before next e2e run so that cleanup can take place.
2. cloud-watch integration for monitoring
3. Enhance the vended ACK metrics
4. Soak test configuration should accept:
    a) How many resource of a type that you want to run 
    b) How long each of them should not be cleaned up for

**Comment by jaypipes** [comment]
@vijtrip2 please go ahead and create separate issues/tasks for the above items and we'll go ahead and close this particular issue out.
