### ISSUE TITLE
Practise and automate release mechanism and pipeline

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#456]
**Is your feature request related to a problem?**
Document release mechanism and pipeline for ACK service controllers

Related issue #434 
**Describe the solution you'd like**
This feature request is to have document on release mechanism and pipeline for ACK service controllers.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by RedbackThomson** [comment]
Release mechanism outlined in documentation - https://aws-controllers-k8s.github.io/community/docs/contributor-docs/release/
Release scripts in the continuous deployment directory - https://github.com/aws-controllers-k8s/test-infra/blob/main/cd/scripts/release-controller.sh
