### ISSUE TITLE
Move container images to ECR public registry

### ISSUE THREAD

**Issue by mhausenblas** [aws-controllers-k8s/community#461]
Currently, the service controller images are hosted as public images in Docker Hub. Now that ECR [https://aws.amazon.com/ecr/faqs/) are available, we should move them there, along with the Helm Charts that were being published to the `gh-pages` branch of the repo.

Things we need to get done here:

- [x] Create a new AWS account for ACK administration/infra (internal accounts)
- [x] Create a new AWS sub-account under the top-level AWS account that we use for publishing artifacts (internal accounts)
- [x] Reserve the `ack` domain in the ECR public registry list
- [x] Modify the [image publication script](https://github.com/aws/aws-controllers-k8s/blob/main/scripts/helm-publish-charts.sh) to publish to ECR public registry
- [ ] Modify the [Helm publication script](https://github.com/aws/aws-controllers-k8s/blob/main/scripts/helm-publish-charts.sh) to publish to an external repo instead of the `gh-pages` branch of the source repository
- [x] Update our internal wiki docs about the above changes to our AWS accounts

**Comment by paulcarlton-ww** [comment]
This issue is closed but it doesn't seem that the helm repo has yet been setup?

**Comment by vijtrip2** [comment]
> This issue is closed but it doesn't seem that the helm repo has yet been setup?

Helm repo is setup and functional. Are you exporting following variable? `export HELM_EXPERIMENTAL_OCI=1`

Please see [this](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/) doc which installs ACK controllers using Helm.

**Comment by narcosis** [comment]
Hi,
Still having the original issue when trying to add the helm repository for S3.
Has this issue been resolved?
"helm repo add ack https://aws.github.io/aws-controllers-k8s/charts"

`Error: looks like "https://aws.github.io/aws-controllers-k8s/charts" is not a valid chart repository or cannot be reached: failed to fetch https://aws.github.io/aws-controllers-k8s/charts/index.yaml : 404 Not Found`

**Comment by jaypipes** [comment]
> Hi, Still having the original issue when trying to add the helm repository for S3. Has this issue been resolved? "helm repo add ack https://aws.github.io/aws-controllers-k8s/charts"
> 
> `Error: looks like "https://aws.github.io/aws-controllers-k8s/charts" is not a valid chart repository or cannot be reached: failed to fetch https://aws.github.io/aws-controllers-k8s/charts/index.yaml : 404 Not Found`

Please see the doc that @vijtrip2 linked. The correct repository URL for you would be public.ecr.aws/aws-controllers-k8s/s3-chart

**Comment by narcosis** [comment]
Hi Jaypipes,
Thank you for the quick response.

I saw the document but Im looking for a public path to download a specific version during my landscape creation.
The flow as described in the doc (downloading the package and extracting it) is not really how we wanted to run.

p.s while trying ``helm repo add ack-s3 public.ecr.aws/aws-controllers-k8s/s3-chart'  I get the this error 
`Error: could not find protocol handler for:     `

Is downloading the package locally our only way to get the chart?
