### ISSUE TITLE
EC2 VPC service controller

### ISSUE THREAD

**Issue by mdykes-gw** [aws-controllers-k8s/community#489]
## New ACK Service Controller

Support for EC2 VPC

### List of API resources

List the API resources in order of importance to you:

1) [VPC](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpc.html)
1) [Subnet](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSubnet.html)
1) [RouteTable](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRouteTable.html)
1) [Route](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html)
1) [InternetGateway](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateInternetGateway.html)
1) [TransitGateway](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGateway.html)
1) [VPC Endpoint](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html)
1) [DHCP Options](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDhcpOptions.html)
1) [SecurityGroup](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSecurityGroup.html)

**Comment by gowrisankar22** [comment]
@jaypipes we are looking for an operator which can create a vpc endpoint .. Any idea what is the tentative timeline when this controller will be available?

**Comment by jaypipes** [comment]
> @jaypipes we are looking for an operator which can create a vpc endpoint .. Any idea what is the tentative timeline when this controller will be available?

I will start the build process for this controller in early January. The order of resources that I will be working on is listed above. Sounds like you would like me to prioritize VPC Endpoint over some of the other resources. Is that a fair statement? :)

Of course, I can't give you a timeline on how long it will take to get the EC2 VPC controller into developer preview. Once I start the build process I should be able to give you a rough timeline of which quarter in 2021 this should land.

**Comment by gowrisankar22** [comment]
@jaypipes 
Yeah, correct. But you have to consider the quota limitations. Currently, per VPC you can create an upper hard limit of 200 for the VPC endpoint. 

Some of the below requirements if you consider that will makes everyone's life easier.

1. aws vpc endpoint controller should check for the quota before creating the endpoint.
2. example: by default, I have added 3 vpcs, then the controller should do the loadbalance or on round-robin basis it should select the vpc and it should work if I again add 4th vpc later.
3. If my vpc is running in a different aws account, it should read the credentials accordingly.

**Comment by brycahta** [comment]
Starting work on this implementation. I'll be tackling the resources in the order listed above due to dependencies between resources (i.e. cannot create route without referencing a route table) and will update the issue should anything change.

Repo for the ec2 controller can be found [here](https://github.com/aws-controllers-k8s/ec2-controller)

**Comment by brycahta** [comment]
**Update:** Putting `Route` development on hold.

Given the EC2 `Route` api and coupling with `RouteTable` we think it makes the most sense to implement `Route` as a Spec field to the RouteTable CR, ex: *Spec.Routes []CreateRouteInput*. This override feature is in development, so I will continue to implement other Networking resources and circle back to `Route` upon feature completion.

Related issues:
* https://github.com/aws-controllers-k8s/community/issues/881
* https://github.com/aws-controllers-k8s/community/issues/914

**Comment by haarchri** [comment]
faced some problem in ec2 transitgateway during code-gen in crossplane project https://github.com/crossplane/provider-aws/pull/831 in` func GenerateModifyTransitGatewayInput`

https://github.com/haarchri/provider-aws/blob/ec2-transitgateway/pkg/controller/ec2/transitgateway/zz_conversions.go#L209-L272


wrong:
cr.Spec.ForProvider.Options.AddTransitGatewayCIDRBlocks
cr.Spec.ForProvider.Options.AssociationDefaultRouteTableID 
cr.Spec.ForProvider.Options.PropagationDefaultRouteTableID
cr.Spec.ForProvider.Options.RemoveTransitGatewayCIDRBlocks

correct:
cr.Spec.ForProvider.Options.TransitGatewayCIDRBlocks 
cr.Spec.ForProvider.Options.DefaultRouteTableAssociation 
cr.Spec.ForProvider.Options.DefaultRouteTablePropagation 
cr.Spec.ForProvider.Options.TransitGatewayCIDRBlocks

**Comment by brycahta** [comment]
As of `v0.0.8`, [ec2-controller](https://github.com/aws-controllers-k8s/ec2-controller) supports Create/Delete functionality for the resources listed above. An issue to track implementing `update` functionality for each resource has been opened in [community issues](https://github.com/aws-controllers-k8s/community/issues?q=is%3Aissue+is%3Aopen+implement+update+in%3Atitle). 

In the meantime, the service team will shift its focus to implementing the `Instance` resource (and dependencies); the work will be tracked [here](https://github.com/aws-controllers-k8s/community/issues/1196).

Feel free to react/comment on any of these issues to discuss in more detail & help us prioritize the work.

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
