### ISSUE TITLE
KMS service controller

### ISSUE THREAD

**Issue by mdykes-gw** [aws-controllers-k8s/community#491]
## New ACK Service Controller

Support for KMS

### List of API resources

List the API resources in order of importance to you:

1) [Key](https://docs.aws.amazon.com/ja_jp/kms/latest/APIReference/API_CreateKey.html)
1) [Grant](https://docs.aws.amazon.com/ja_jp/kms/latest/APIReference/API_CreateGrant.html)

**Comment by sura8257** [comment]
+1

**Comment by arajakul** [comment]
I would love to take a stab at this and create a PR for this feature request.

**Comment by jaypipes** [comment]
> I would love to take a stab at this and create a PR for this feature request.

@arajakul we would be honoured to have you contribute to ACK (for the KMS controller or anywhere else!)

Feel free to hop on #provider-aws channel on Kubernetes Slack and find me if you have any questions and/or want to do a deep dive on the code generator. Happy to help you :)

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
