### ISSUE TITLE
Business logic

### ISSUE THREAD

**Issue by mhausenblas** [aws-controllers-k8s/community#5]
This design issue is about how the business logic of ASO custom controllers is implemented. The goal is to find a scalable and flexible way to manage AWS services. Usage of requirements key words as per [RFC 2119](https://tools.ietf.org/html/rfc2119).

## Scope

In scope for this issue is the question how the business logic of ASO custom controllers is implemented, that is, how the management of  AWS services is achieved. Out of scope for this issue is the selection of the custom controller framework, see #4 for this.

## Input

Relevant technologies that could be used, either on their own or in combination:

* The [AWS SDK for Go](https://aws.amazon.com/sdk-for-go/)
* The [AWS Cloud Development Kit](https://aws.amazon.com/cdk/)
* AWS [CloudFormation](https://aws.amazon.com/cloudformation/)
* [Terraform](https://www.terraform.io/)
* [Validating Webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)

Input from roadmap issue https://github.com/aws/containers-roadmap/issues/456:

* @whereisaaron in:
  * https://github.com/aws/containers-roadmap/issues/456#issuecomment-543518513
  * https://github.com/aws/containers-roadmap/issues/456#issuecomment-544301101
* @daviddyball in:
  * https://github.com/aws/containers-roadmap/issues/456#issuecomment-543607777
  * https://github.com/aws/containers-roadmap/issues/456#issuecomment-544427379
  * https://github.com/aws/containers-roadmap/issues/456#issuecomment-548292982
* @cpoole in https://github.com/aws/containers-roadmap/issues/456#issuecomment-548095520
* @iAnomaly in https://github.com/aws/containers-roadmap/issues/456#issuecomment-548124442
* @sftim in https://github.com/aws/containers-roadmap/issues/456#issuecomment-548279907

## Requirements

1. It MUST be possible to write business logic in Go.
1. The implementation details of the business logic implementation SHOULD NOT leak to the ASO client.
1. All AWS services MUST be supported; where not possible, a mechanism MUST exist to provide a custom support.

**Comment by daviddyball** [comment]
1. **It MUST be possible to write business logic in Go.**
    I know framework is discussed in issue 4, but it should be noted that both `kubebuilder` and `operator-sdk` are Go, so a choice for either will mean that Go is the default language used.

2. **The implementation details of the business logic implementation SHOULD NOT leak to the ASO client.**

    As per my comments [here](https://github.com/aws/aws-service-operator-k8s/issues/3#issuecomment-551201262), a lot of separation can be done by implementing a Validating Webhook to control admission of objects to K8s and should leave the ASO "controller" portion to simply act upon the Objects once they're created in K8s. This would mean that the `client` has no actual insight into what the ASO controller portion is doing (unless they can read container logs for the `aso-controller` Pod :stuck_out_tongue:)

3. **All AWS services MUST be supported; where not possible, a mechanism MUST exist to provide a custom support.**

    If we stick to using `aws-sdk-go` for any ASO->Service implementation should insulate the controller from having to write custom AWS Service integrations.

    Coming up with a reusable pattern for each `CustomResource` also makes implementation of new AWS Services trivial. The logic is generally the same for all controllers:

    Depending on whether we're Creating, Updating or Deleting the incoming `Object`:
    a) If `Create` -> call `<service>.Create(object)` 
    b) If `Updated` -> `diff` object -> call `<service>.UpdateXYZ(object)` where `XYZ` could be `UpdateTags()`, `UpdateIAMPolicies()`, `UpdateVpcSubnetGroups()` etc.
    c) If `Delete` -> Add `finalizer: [ "aso-delete" ]` to object -> call `<service>.Delete(object)` -> remove `finalizer`

**Comment by daviddyball** [comment]
Just to add to my original comment, I strongly believe that this project should _not_ use Terraform or CloudFormation for any part of its implementation. Doing so not only increases the scope of the project, but also introduces competing methods for achieving similar goals. Kubernetes object storage _is_ the state-store and Terraform/CF have a whole other method for managing state.

On top of this, kubernetes controllers are level-headed, in that they look at objects as they change, not as a whole graph of connected items. Trying to mix the two behaviours in the way resources are treated well most likely cause confusion for end users.

**Comment by marcindulak** [comment]
I wonder whether a `dry-run` feature which reports the changes that are about to be performed in AWS is in scope for ASO. Cloudformation has change sets and there is `cdk diff` but they are are inferior to `terraform plan`, see also https://github.com/pulumi/pulumi-kubernetes/issues/352 and https://github.com/k14s/kapp/blob/master/docs/diff.md. This `dry-run` feature would be useful for emergency actions in production environments and it would speed up the debugging process when setting up the AWS resources managed by ASO.

**Comment by marcindulak** [comment]
Another practical question that will surely be asked at some point is: how do I convert my Cloudformation nested stacks into ASO? Is this in scope for ASO?

**Comment by chrisfowles** [comment]
`kubectl` should be able to provide diff and dry-run functionality without needing to re:invent the wheel, especially if the ASO matches closely to the sdk apis.

**Comment by mhausenblas** [comment]
@daviddyball thanks for your input, I've added validating webhooks as potential building blocks. This sounds like something we should seriously consider.

**Comment by mhausenblas** [comment]
@marcindulak thanks for your input and I tend to agree with @chrisfowles that dry-run, if possible should be done native. As to your question concerning CF to ASO conversion, I'd say for the first phase it's not in scope, but certainly something  we should consider, down the line.

**Comment by ghostsquad** [comment]
> Another practical question that will surely be asked at some point is: how do I convert my Cloudformation nested stacks into ASO? Is this in scope for ASO?

like @marcindulak many users will want to know how to convert their Terraform into ASO.

**Comment by RedbackThomson** [comment]
Closing as this information has become largely out of date, and superseded by other issues.
