### ISSUE TITLE
Standardize structure of Bash scripts

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#504]
We currently have quite a few Bash scripts in the [`scripts/`](https://github.com/aws/aws-controllers-k8s/tree/main/scripts) directory.

I've tried to keep the calling format and structure of these Bash scripts relatively consistent. However, because some of the scripts have roots in other repositories (aws/aws-node-termination-handler, aws/amazon-vpc-cni-k8s, etc), there are inconsistencies in:

- [ ] whether and how getopts/CLI options vs environment variables to control the script
- [ ] how the `$ROOT_DIR` is determined
- [ ] how variables are defaulted
- [ ] how errors and Bash options are set
- [ ] documentation about scripts is inconsistent and we should have a Bash script writing guide

It would be awesome to clean all these inconsistencies up and have a `scripts/` directory that we can be proud of :)

## `getopts` vs environment variables

Some scripts use `getopts` to process CLI arguments. Here's an example from the `scripts/kind-build-test.sh` script:

https://github.com/aws/aws-controllers-k8s/blob/079fa26fe98aa289e5770e8226129917971473f8/scripts/kind-build-test.sh#L84-L113

Other scripts don't use `getopts` and prefer instead to simply have a fixed number of arguments and rely on environment variables for optional behaviour switches. An example would be the `scripts/helm-package-controller.sh` script:

https://github.com/aws/aws-controllers-k8s/blob/079fa26fe98aa289e5770e8226129917971473f8/scripts/helm-package-controller.sh#L16-L34

My **personal** preference is for the latter environment variable approach. However, if contributors feel strongly about the former, I will bias more towards having a consistent calling structure than my personal preference.

## how the `$ROOT_DIR` is determined

Some scripts use this:

```bash
SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
ROOT_DIR="$SCRIPTS_DIR/.."
```

other scripts use this:

```bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
```

others use this:

```bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```

(that last one is from `test/e2e/run-tests.sh`)

There's also the potential of using this technique as our standard:

https://github.com/aws/eks-charts/blob/d721c97c339c8b1060ac8b76a247ce67a470e90c/scripts/publish-charts.sh#L4

Regardless, let's have a single way of doing this and standardize :)

## how variables are defaulted

Some scripts use this technique to default a variable:

https://github.com/aws/aws-controllers-k8s/blob/079fa26fe98aa289e5770e8226129917971473f8/scripts/build-controller.sh#L23

Other scripts use this technique:

https://github.com/aws/aws-controllers-k8s/blob/079fa26fe98aa289e5770e8226129917971473f8/scripts/kind-build-test.sh#L17

Let's pick one and stick with it.

## how errors are handled and Bash options are set

Some scripts use:

```bash
set -Eo pipefail
```

others do:

```bash
set -E
```

Some scripts trap errors and handle them in error catch functions:

https://github.com/aws/aws-controllers-k8s/blob/079fa26fe98aa289e5770e8226129917971473f8/scripts/kind-build-test.sh#L158

There's not really any consistency to this, and there should be.

**Comment by lxfontes** [comment]
>  whether and how getopts/CLI options vs environment variables to control the script

agree with env variables

>  how the $ROOT_DIR is determined

IMO the git top-level approach feels OK if these scripts are always running in dev/CI context. Expecting `.git` to be available in a docker image seems 🤔  . So if always git lets go with git top-level, otherwise any variation of `$(cd "$(dirname "$0")"; pwd)` would do.

>  how variables are defaulted

I vouch for `${VAR:-default}` as this says: "if the var is not set, use the default value". `${VAR:=default}` will modify the variable (side effect).

> how errors and Bash options are set

I would go with 
```
set -euo pipefail
[ "${DEBUG:+set}" == "set" ] && set -x
```

by default error on:
- unset vars ( -u )
- exit on command errors ( -e )
- exit on pipe errors too ( -o pipefail )

and turn on bash trace in case `DEBUG` var is set.

**Comment by niconosenzo** [comment]
I might have some fun working on this based on @lxfontes suggestions (if nobody else is doing it already). I'd also start a script-contribution guide encouraging those practices.

**Comment by jaypipes** [comment]
@lxfontes @niconosenzo I'd be super excited to have either or both of you contribute here. Let me know if you'd like more information about it or would like me to officially assign the task to one or both of you. Thank you!

**Comment by lxfontes** [comment]
@niconosenzo feel free to take the lead! I can second chair and help with bash-isms / shell weirdness 😂 
a good starting point is to run [shellcheck](https://github.com/koalaman/shellcheck) to identify easy fixes. Example:

<img width="1841" alt="Screen Shot 2020-11-17 at 12 26 01 PM" src="https://user-images.githubusercontent.com/35205/99424965-48864600-28d0-11eb-966b-2e09b0be4a12.png">

**Comment by niconosenzo** [comment]
Thanks @lxfontes :), @jaypipes I will work on it.

**Comment by jaypipes** [comment]
> Thanks @lxfontes :), @jaypipes I will work on it.

Awesome, thanks @niconosenzo :) Please remember to submit small, bite-sized PRs to make it easier on reviewers!

**Comment by tbutler4** [comment]
@niconosenzo I spent a good amount of time finding an open issue to work on and landed here. Do you have any suggestions on how I can help you tackle all of this?

**Comment by niconosenzo** [comment]
@tbutler4 Hi! You can pick up any of the inconsistencies listed by Jay in the very first comment (I'm already working in the first one about getopts and env variables). Just be sure to let me know which one you're picking up so we avoid the re-work.

**Comment by tbutler4** [comment]
> @tbutler4 Hi! You can pick up any of the inconsistencies listed by Jay in the very first comment (I'm already working in the first one about getopts and env variables). Just be sure to let me know which one you're picking up so we avoid the re-work.

On it!! Happy to be working on these with you.

**Comment by tbutler4** [comment]
@niconosenzo I went backwards and started with the bash error handling. I will be sure to reach out on here before I start the next one.

**Comment by tbutler4** [comment]
@jaypipes with the error handling  I wanted to confirm if keeping the traps was appropriate while keeping the set options uniform?

**Comment by niconosenzo** [comment]
@jaypipes, Should this issue be closed ?

**Comment by jaypipes** [comment]
Yup, I think we're good on this, thank you so much for your contributions @niconosenzo! :)

**Comment by niconosenzo** [comment]
It has been a pleasure! :smiley:
