### ISSUE TITLE
[ElastiCache] DescribeEvents support for Replication Group, Cache Parameter Group, Cache Subnet Group

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#527]
**Is your feature request related to a problem?**
ElastiCache `DescribeEvents` API provides events for replication group, cache parameter group, cache subnet group
Reference: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/describe-events.html

This feature request is to provide recent events for replication group, cache parameter group, cache subnet group custom resources as status.events

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by echen-98** [comment]
@kumargauravsharma probably ok to close right?

**Comment by kumargauravsharma** [comment]
yes this issue can be closed.
