### ISSUE TITLE
ECR: updating tags ignored

### ISSUE THREAD

**Issue by maust** [aws-controllers-k8s/community#581]
**Describe the bug**
Updating an existing ecr does ignore changes to the tags.

**Steps to reproduce**
- build current image for ECR from main branch
- create a ECR repo using the controller
- update the ECR by changing/adding/removing tags
- logs in controller show no problem, but ECR repo tags are unchanged

**Expected outcome**
Tags should be updated.

**Environment**

* Kubernetes version: 1.17
* Using EKS (yes/no), if so version? yes, eks.4
* AWS service targeted (S3, RDS, etc.): ECR

**Comment by vijtrip2** [comment]
tags are now supported for ECR repository custom resource
https://github.com/aws-controllers-k8s/ecr-controller/commit/81f131f6e61de5dbcf62df105a5cc1d416d77a48
