### ISSUE TITLE
ApplicationAutoScaling service controller

### ISSUE THREAD

**Issue by bwagner5** [aws-controllers-k8s/community#589]
## New ACK Service Controller

Support for Application Auto Scaling

### List of API resources

List the API resources in order of importance to you:

1) [ScalingPolicy](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScalingPolicy.html)

**Comment by surajkota** [comment]
Preview - v0.0.1 released

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
