### ISSUE TITLE
Technical feasibility prototype for Service Updates API

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#635]
**Is your feature request related to a problem?**
Create a prototype to check Technical feasibility to enable Service Updates API of ElastiCache for replication group

**Describe the solution you'd like**
Code/Design describing technical feasibility

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by vijtrip2** [comment]
Please reopen if this is still relevant.

/close
