### ISSUE TITLE
DynamoDB GlobalTable deletion does not work

### ISSUE THREAD

**Issue by muvaf** [aws-controllers-k8s/community#637]
**Describe the bug**

ACK controllers do not have a deletion procedure for `GlobalTable` resource.

**Steps to reproduce**

Create a `GlobalTable` and delete it. In AWS console, it will still appear in `GlobalTable` properties of the `Table`.

**Expected outcome**

Deletion of `GlobalTable` would result in deletion of entries in `GlobalTable` properties of `Table`. This action is possible in AWS console

I noticed this while I was testing `GlobalTable` for Crossplane. Apparently, you need to make a `UpdateGlobalTable` call with `DeleteAction`, hence ACK won't find a function called `DeleteGlobalTable`. I had to solve this by manually writing that logic as [custom hook](https://github.com/crossplane/provider-aws/blob/b65c7f9/pkg/controller/dynamodb/globaltable/hooks.go#L146) but thought I'd let you know so that maybe we can find a better solution for code generation to cover it.

**Comment by jaypipes** [comment]
Hmmm, `UpdateGlobalTable` API call with a `DeleteAction`. Gotta love the inconsistency. :)

OK, thanks @muvaf, I will get working on a fix ASAP!

**Comment by A-Hilaly** [comment]
Thanks for reporting the issue! Global table deletion is currently supported in dynamodb-controller (using `UpdateGlobalTable`)
