### ISSUE TITLE
ack-generate fails when aws-sdk-go v1.36.26 is used

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#642]
**Describe the bug**
`ack-generate` fails when `aws-sdk-go v1.36.26` is used

**Steps to reproduce**
1. Update `go.mod` to use `github.com/aws/aws-sdk-go v1.36.26`
2. Run `SERVICE=apigatewayv2 && make build-controller`
3. Observe error:
```
aws-controllers-k8s/services/apigatewayv2/apis/v1alpha1/integration.go:41:33: map values must be a named type, not *ast.MapType
Error: not all generators ran successfully
```

**Expected outcome**
Controllers getting generated when `aws-sdk-go v1.36.26` is used

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by jaypipes** [comment]
@vijtrip2 can you look into this one? not sure if it is still happening with latest code-gen/runtime.

**Comment by vijtrip2** [comment]
Yeah, it will still happen. The root-cause is the functionality on controller-tools, which does not allow Map<K,Map<>> shapes. APIGWv2 introduced such shape in integration resource for SDK version after v1.35.5 .

A PR is out to support this shape in controller-tools and I will try to address latest comments on that PR.
https://github.com/kubernetes-sigs/controller-tools/pull/518

P.S. it is possible to generate apigatewayv2 controller locally for new sdk versions, but controller-tools copy has to be patched locally.

**Comment by vijtrip2** [comment]
Raised a PR in controller-tools for handling this. https://github.com/kubernetes-sigs/controller-tools/pull/569
