### ISSUE TITLE
[s3] implement Bucket Update code paths

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#653]
We don't support Update operations on the Bucket resource in the S3 service controller:

https://github.com/aws/aws-controllers-k8s/blob/e45948e03e8bbd1bcdd3ff31c7eb01c169a36aad/services/s3/pkg/resource/bucket/sdk.go#L179

This is because each attribute for an S3 Bucket has a separate update API call :(

- [ ] [PutBucketLifecycleConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_PutBucketLifecycleConfiguration.html)
- [ ] [PutBucketPolicy](https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_PutBucketPolicy.html)
- [ ] [PutBucketTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_PutBucketTagging.html)

Eventually I'd like to have the code generator create code to handle this kind of situation, but I think for the immediate future, we'll have to hand-code this in the S3 service controller.

**Comment by vijtrip2** [comment]
Kudos @RedbackThomson
