### ISSUE TITLE
Generating components necessary for OLM bundle Creation

### ISSUE THREAD

**Issue by komish** [aws-controllers-k8s/community#667]
## Goal

Be able to offer the AWS Controllers for Kubernetes via any Operator Lifecycle Manager-enabled cluster. 

## References

* Operator Lifecycle Manager ("OLM"): https://github.com/operator-framework/operator-lifecycle-manager

* Bundle Generation Docs: https://sdk.operatorframework.io/docs/cli/operator-sdk_generate_bundle/

### Summary

Being able to bundle a given controller just requires a few additional files be generated for each service. With these files, the `operator-sdk generate bundle` command can be called, with certain flags, generating an appropriate `bundle/` directory and `bundle.Dockerfile`. This can then be offered via a catalog in OLM-enabled clusters.

### High-level implementation

The [code generation documentation](https://github.com/aws/aws-controllers-k8s/blob/main/docs/contents/dev-docs/code-generation.md) describes the phased approach used by the aws-controllers-k8s project today. With this in mind, the proposed implementation would be an additional (and optional) phase which generates all assets necessary to feed the `operator-sdk generate bundle` command. Automation can then execute `operator-sdk generate bundle`.

### What needs to be generated

From the perspective a given service's config directory, which lives in the generated service directory (e.g. [ack-controller-k8s/services/s3/config](https://github.com/aws/aws-controllers-k8s/tree/main/services/s3/config), here's the breakdown of what needs to be changed or added:

```
key:
	m : existing file that needs modification
	+ : net-new file
	T : file needs templating/generation
	c : file can be copied statically

---
m   ├── controller/
m   │   ├── kustomization.yaml	
+ c │   └── patch-user-env.yaml
+   ├── manifests/
+   │   ├── bases/
+ T │   │   └── SERVICE.clusterserviceversion.yaml
+ T │   └── kustomization.yaml
+   ├── samples/
+ T │   ├── SERVICE-CRD.yaml
+ T │   └── kustomization.yaml
+   └── scorecard
+       ├── bases/
+ c     │   └── config.yaml
+ c     ├── kustomization.yaml
+       └── patches/
+ c         ├── basic.config.yaml
+ c         └── olm.config.yaml
```

### Descriptions by parent directory

These directories are within the `ack-controllers-k8s/services/SERVICENAME/config/` directory, so the directory **controllers/** would effectively mean ``ack-controllers-k8s/services/SERVICENAME/config/controllers/`.``

---

#### controllers/

**patch-user-env.yaml**

​	This allow a cluster administrator to prepare the controller namespace with credentials and controller configuration in a fail-safe way. Today, OLM-managed controller deployments will be reconciled on change which causes issues with credential-management implementations that inject authentication bits to the controller directly. Including this in the deployment manifest that is provided to OLM to install allows cluster administrators to make changes to the configuration and secrets without impacting the deployment directly.

**kustomization.yaml**

This already exists, but would need to have `patchesStrategicMerge` populated if the above patch is to be included.

---

#### manifests/

This directory can be renamed, as `operator-sdk generate bundle` accepts a flag that allows the user to change the path definition for finding these files.

**bases/SERVICE.clusterserviceversion.yaml**

The [ClusterServiceVersion](https://olm.operatorframework.io/docs/concepts/crds/clusterserviceversion/) ("CSV") is the key asset that needs generation. This is a Kubernetes custom resource that contains a bulk of the metadata necessary for OLM to "see" and be able to deploy the service controller.

This will need a template.

**kustomization.yaml**

The `operator-sdk generate bundle` command operates on a series of inputs (YAML manifests) that help render the final CSV. That final CSV is then bundled for a given release. 

It takes, as input, a series of YAML manifests (e.g. the controller deployment yaml, the contents of the samples/ directory, etc). This kustomization is in place to facilitate calling `kustomize build` on a single target, which in turn calls downstream targets, resulting in all the necessary inputs for `operator-sdk generate bundle` to complete.

---

#### samples/

**SERVICE-CRD.yaml**

This is a sample custom resource yaml for the given service (e.g. for S3, this is a "Bucket" YAML manifest).  Projects built with [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) get this out of the box when `create`-ing APIs. 

I don't believe the naming convention here to be important to operator-sdk, but is more for user visibility. 

Services with multiple custom resources can have an individual file per-resource, or have all resources in a single file with YAML separators. Either appeared to work in testing.

**kustomization.yaml**

This is in place to ensure that calling `kustomize build config/manifests` properly includes this directory. Projects built with [OperatorSDK](https://sdk.operatorframework.io/) get this by default. This file just needs to include the name of the SERVICE-CRD.yaml file listed under the `resources` section.

---

#### scorecard/

This parent directory ships basic tests with every operator built using OperatorSDK.

At the time of writing, the AWS Controllers for Kubernetes don't have any Scorecard tests to include so this directory can effectively be a "copy/paste" from what OperatorSDK scaffolds for new projects

Should ACK want to include Scorecard tests in the future, additional patches can be configured. Documentation on generating custom tests is found [here](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/custom-tests/).

**bases/config.yaml**

This is a blank [Scorecard](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/scorecard/) configuration. The patches in this kustomize directory patch in test specifications.

**patches/basic.config.yaml**

This is the included basic test suite which makes sure that all custom resources have a spec block. See [definition](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/scorecard/#basic-test-suite).

**patches/olm.config.yaml**

This is the included OLM-specific test which ensures that the resulting assets have niceties for usage within OLM. See [definition](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/scorecard/#olm-test-suite).

**kustomization.yaml**

Similar to **samples/kustomization.yaml**. this ensures that this directory is included when calling `kustomize build config/manifests`, as well as sets up the bases/patches relationship present in this directory.

**Comment by komish** [comment]
Hi folks, just want to touch base here and make sure the implementation details manifested here are sound. If so, I'll do some testing and work towards a PR!

**Comment by jaypipes** [comment]
> Hi folks, just want to touch base here and make sure the implementation details manifested here are sound. If so, I'll do some testing and work towards a PR!

@komish yes, the steps look proper. We're just in the process of splitting the monorepo into multiple source repositories, one for each service controller (please see #666). Hoping to get that merged today. You would want to make most of your changes to the github.com/aws-controllers-k8s/code-generator repository.

**Comment by komish** [comment]
Understood, thanks @jaypipes ! I'll look to start getting spun up probably early next week.
