### ISSUE TITLE
DocumentDB: nil pointer in generated code

### ISSUE THREAD

**Issue by MisterMX** [aws-controllers-k8s/community#697]
**Describe the bug**

When generating the respective controller for DocDB `DBInstance` the `external` type is defined containing a field `filterList` in `zz_controller.go`.

However, in `newExternal` this field is never set to its default value `nopFilterList`. Causing a 
panic when called in `Observe` in line 86 `resp = e.filterList(cr, resp)`.

When the default value is added to `newExternal` the error disappears:
```golang
e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
		filterList:     nopFilterList,  <---------
	}
```

**Steps to reproduce**

1. Generate a controller for Crossplane provider-aws using 
```shell
go run -tags codegen cmd/ack-generate/main.go crossplane docdb --provider-dir ../provider-aws 
```
2. Run generated controller without setting `filterList` in your connector `opts`

**Expected outcome**

`nopFilterList` should be called if not configured differently in `opts`.

**Environment**

* Kubernetes version: `v1.18.9-eks-d1db3c`
* Using EKS `eks.3`
* AWS service targeted: DocumentDB

**Comment by jaypipes** [comment]
@muvaf ping on this. fancy having a look into it in your morning?

**Comment by muvaf** [comment]
It's a small fix in Crossplane template, https://github.com/aws-controllers-k8s/code-generator/pull/24 takes care of it. Thanks @MisterMX for letting us know!
