### ISSUE TITLE
Update build scripts to have additional tasks for OLM bundle generation

### ISSUE THREAD

**Issue by komish** [aws-controllers-k8s/community#705]
**Describe the solution you'd like**
Release workflows should include optionally executing necessary steps to generate an OLM bundle as a release asset.

The code-generator is capable of generating assets already: https://github.com/aws-controllers-k8s/code-generator/pull/22

The remaining automation probably looks like this:

1. Execute new generators `ack-generate olm ...`
2. Execute operatorSDK bundling workflows
3. Execute publishing of the bundle to a registry

Per [previous discussion](https://github.com/aws-controllers-k8s/code-generator/pull/22#discussion_r581178961) the first (1.) item makes sense to include in the release scripts (https://github.com/aws-controllers-k8s/community/blob/main/scripts/build-controller-release.sh). The challenge there would seem to be that the input service configuration for the `olm` generator is required, so if the developer hasn't prepared that ahead of time, such as in cases where someone is not interested in consuming the bundle assets for any reason, then the script would fail.

The second (2.) and third (3.) items feel like separate scripts, docs, or both. The second item requires operatorSDK be installed on the build machine. The third is relatively varied on how it gets done.

Let me know what you think!

**Describe alternatives you've considered**
These build steps were initially covered in the previously mentioned [PR's](https://github.com/aws-controllers-k8s/code-generator/pull/22) original design which generated a partial Makefile (borrowed from OperatorSDK/Kubebuilder) that contained just the necessary bits for these steps. However, updating existing automation tooling definitely makes more sense.

**Comment by jaypipes** [comment]
> Per [previous discussion](https://github.com/aws-controllers-k8s/code-generator/pull/22#discussion_r581178961) the first (1.) item makes sense to include in the release scripts (https://github.com/aws-controllers-k8s/community/blob/main/scripts/build-controller-release.sh). The challenge there would seem to be that the input service configuration for the `olm` generator is required, so if the developer hasn't prepared that ahead of time, such as in cases where someone is not interested in consuming the bundle assets for any reason, then the script would fail.

You are referring to the OLM-specific config file, right? Not the `generator.yaml` file that is in the root directory of each service controller source repository?

If so, yes, and I'd like to see PRs for each of the service controller repositories that adds the OLM configuration file that describes the metadata about the controller and the basic traits that the `operator-sdk` needs. @komish are you interested in pushing those files? Eventually, I'd like to have the OLM configuration file be part of the https://github.com/aws-controllers-k8s/template-controller repository that we're going to use for new service controller projects, too.

> The second (2.) and third (3.) items feel like separate scripts, docs, or both. The second item requires operatorSDK be installed on the build machine. The third is relatively varied on how it gets done.

We have install scripts for various tooling dependencies in the [scripts/](https://github.com/aws-controllers-k8s/community/tree/main/scripts) directory. Recommend copying one of those and adapting for operator-sdk install :)

**Comment by komish** [comment]
> You are referring to the OLM-specific config file, right? Not the `generator.yaml` file that is in the root directory of each service controller source repository?

Yes, the OLM-specific configuration is what I'm referring to here.

In my mind, the workflow deviates a bit there because the file is static (read: not generated), so it needs to be prepared/put-in place. Assuming it's only going to exist in a given service controller's repository, it seemed like a strange flow to go pull it from the existing, generated code for a service controller (i.e. https://github.com/aws-controllers-k8s/s3-controller) , and then use it to drive newly generated code (as opposed to, say, storing it in a static place and pulling it form there). 

@jaypipes This might be a nit-pick/overthink. I'll tinker with this workflow and come back if I still have questions.

> If so, yes, and I'd like to see PRs for each of the service controller repositories that adds the OLM configuration file that describes the metadata about the controller and the basic traits that the operator-sdk needs. @komish are you interested in pushing those files? Eventually, I'd like to have the OLM configuration file be part of the https://github.com/aws-controllers-k8s/template-controller repository that we're going to use for new service controller projects, too.

Definitely! More to come as I have it.

**Comment by komish** [comment]
Hi @jaypipes was this implemented? Apologies for the delays on my end (side tracked at the moment)

**Comment by jaypipes** [comment]
> Hi @jaypipes was this implemented? Apologies for the delays on my end (side tracked at the moment)

Hi @komish! Sorry, I thought this was implemented with your patches to code-generator... I was mistaken. :) Re-opening!

**Comment by komish** [comment]
@jaypipes No problem, thanks for re-opening! Still have this on my radar, just need to circle back to it. Should be able to do so in the next few weeks!
