### ISSUE TITLE
Explicit mapping for ARN field

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#737]
**Is your feature request related to a problem?**
Currently, the code generator expects the ARN field name to be `Arn` or `ResourceName+Arn` (case insensitive) which does not match for some resources like ModelQualityJobDefinition in SageMaker ARN field is named JobDeifinitionArn.

**Describe the solution you'd like**
option to specify `isARN` under `field_config` similar to `isOwnerAccountId`

**Describe alternatives you've considered**
None

**Comment by RedbackThomson** [comment]
Perhaps another acceptable solution would be to support another field as part of the `resource` such as `ARNField` or `ARNFieldName`.

**Comment by jaypipes** [comment]
> Perhaps another acceptable solution would be to support another field as part of the `resource` such as `ARNField` or `ARNFieldName`.

I'd prefer to use `FieldConfig.is_arn`to align with the other boolean field attributes.
