### ISSUE TITLE
Immutable fields in Spec

### ISSUE THREAD

**Issue by nmvk** [aws-controllers-k8s/community#739]
**Is your feature request related to a problem?**
Currently many APIs have fields which are valid during creation but cannot be modified later. This can potentially create confusion as the resource would not be updated.

Example -

https://docs.aws.amazon.com/cli/latest/reference/elasticache/create-replication-group.html

In this ElastiCache API, `--transit-encryption-enabled ` , `--at-rest-encryption-enabled` are currently immutable.

**Describe the solution you'd like**
Validate if an immutable spec field is modified, then set appropriate condition.

**Describe alternatives you've considered**
Webhook to validate the immutable fields.

**Comment by A-Hilaly** [comment]
I believe this is done in https://github.com/aws-controllers-k8s/code-generator/pull/77 and https://github.com/aws-controllers-k8s/runtime/pull/17.

/close
