### ISSUE TITLE
Output fields consumable by pods, config maps, etc.

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#740]
**Is your feature request related to a problem?**
Although custom resources display their outputs in their own status fields, there is currently no way to consume these fields from other (native) k8s resources. Such an example would be consuming the `configurationEndpoint` field from the ElastiCache `ReplicationGroup` resource into a pod's environment variable.

**Describe the solution you'd like**
- Exporting some subset of the status (and spec fields?) into a config map - possibly through an annotation

**Describe alternatives you've considered**

**Comment by jaypipes** [comment]
See: https://github.com/aws-controllers-k8s/community/issues/292

**Comment by jaypipes** [comment]
In short, I think ACK should focus on control plane operations. A controller that integrates data plane fields into various native Kubernetes resources is interesting but primarily the purview of things like https://github.com/redhat-developer/service-binding-operator

**Comment by RedbackThomson** [comment]
Done! https://github.com/aws-controllers-k8s/runtime/pull/75
