### ISSUE TITLE
Password shown in plain text in Broker Describe output

### ISSUE THREAD

**Issue by phanimullapudi** [aws-controllers-k8s/community#743]
**Is your feature request related to a problem?**
When we describe kubectl describe broker/brokername - the password is shown as plain text. 

**Describe the solution you'd like**
It should be hidden like any other secret. 

**Describe alternatives you've considered**
N.A

`
  Users:
    Console Access:  true
    Groups:
    Password:  adminpassneeds12chars
    Username:  admin
`
@jaypipes @mcmains7812

**Comment by jaypipes** [comment]
Working on #748 as a pre-requisite step for this.

**Comment by jaypipes** [comment]
This is in v0.0.3 release of mq-controller (being released today)
