### ISSUE TITLE
Support struct slices and maps comparisons for delta code generation

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#757]
**Problem description**
Currently the code generated to compare resource fields (`newResourceDelta`) still don't support slices of structs and string to structs maps.

**Describe the solution you'd like**
Support [struct slices](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/compare.go#L437) and [string to struct maps](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/compare.go#L369
) types in resource field comparison functions

/priority important-soon 
/assign

**Comment by vijtrip2** [comment]
Handled using reflect.DeepEqual()
