### ISSUE TITLE
ACK runtime pkg/compare.Difference.Path not being set properly

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#772]
When running AmazonMQ e2e tests, I'm seeing the controller constantly trying to update the broker because it sees differences in the desired ("A") and latest ("B") resources. The log messages look like this:

```
2021-05-12T13:03:49.136Z	DEBUG	ackrt	desired resource state has changed	{"kind": "Broker", "namespace": "default", "name": "my-rabbit-broker-non-public", "generation": 1, "is_adopted": false, "diff": [{"Path":{},"A":null,"B":["sg-c5a50d89"]},{"Path":{},"A":null,"B":["subnet-74d9d90d"]}], "arn": "arn:aws:mq:us-west-2:750630568209:broker:my-rabbit-broker-non-public:b-1655abaa-17c5-4f28-8502-1a66c5e02625"}
```

Note that the `diff` field in the log message is this:

```
"diff": [{"Path":{},"A":null,"B":["sg-c5a50d89"]},{"Path":{},"A":null,"B":["subnet-74d9d90d"]}
```

That should instead be this:

```
"diff": [{"Path": "Spec.SecurityGroups","A":null,"B":["sg-c5a50d89"]},{"Path":"Spec.SubnetIDs","A":null,"B":["subnet-74d9d90d"]}
```

Need to figure out why that is not occurring...

**Comment by surajkota** [comment]
+1 noticed this too, should be prioritized

**Comment by A-Hilaly** [comment]
It looks like this is a logging issue, `zap/zapcore` doesn't log unexported fields and [`ackcompare.Path` `parts` field is unexported](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/compare/path.go#L21) - reason why zap is logging an empty object `{}`

**Comment by A-Hilaly** [comment]
Ohh i just realised that this is more related to `encoding/json` library, `json.Marshall` doesn't serialize unexported fields
