### ISSUE TITLE
[s3] `sdkFind` need to make extra API Calls to retrieve `Bucket` spec fields

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#798]
I’ve been debugging the s3 controller and it looks like we have a bug (some missing API calls) in the generated resourceManager methods , more precisely in the `resourceManager.sdkFind` function

The `ListBuckets` API call only returns bucket names, which causes the `sdkFind` to merge data from the “latest” state, hence the reconciler doesn’t detect any changes. Code bloc: https://github.com/A-Hilaly/s3-controller/blob/main/pkg/resource/bucket/sdk.go#L63-L79

We need to make extra API GET call for each of the s3 bucket properties like `ACL` for example https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketAcl.html

/priority important-soon

**Comment by echen-98** [comment]
Linking a similar issue we faced/are facing with the ElastiCache controller in case it helps: https://github.com/aws-controllers-k8s/elasticache-controller/pull/29

**Comment by RedbackThomson** [comment]
This functionality is being added as part of implementing the CRUD logic per field. Closing this in favour of more specific issues I have created for the remaining fields.
