### ISSUE TITLE
Controller logs for PR test runs

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#825]
**Describe the bug**
Sometimes it's hard to understand the reason for the underlying test failure reason without controller logs in PR builds
Sample - https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_sagemaker-controller/43/sagemaker-kind-e2e/1402342973965864960

**Expected outcome**
controller logs printed after a failed test run or uploaded to S3 bucket in service teams account with test run-id

**Alternatives**
have a try-catch block around the test methods and print the CR status in the catch block. One of the `Status.Conditions` should most probably have the error message

**Comment by RedbackThomson** [comment]
Prow is also able to publish artifacts along with jobs. I think we could export a dump of the controller logs `kubectl logs ...` into a file and then tag that as a job artifact. That should make it available to the web interface. (Just need to make sure it doesn't expose anything undesirable)

**Comment by RedbackThomson** [comment]
I have added this functionality as part of https://github.com/aws-controllers-k8s/test-infra/pull/71

You should find them alongside the pod logs in the test artifacts viewer.

**Comment by surajkota** [comment]
Logs should be exported even if the tests fail which is when we need it more

**Comment by surajkota** [comment]
sample - https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_sagemaker-controller/51/sagemaker-kind-e2e/1418400752233091072

**Comment by RedbackThomson** [comment]
Yep. That's a bug. Good catch, thanks.

**Comment by surajkota** [comment]
Sg, make sure to record the exit code for run-test and return it in the end or else even the failed test runs will also show up a passed

**Comment by RedbackThomson** [comment]
Created https://github.com/aws-controllers-k8s/test-infra/pull/81 to address this
