### ISSUE TITLE
Status of RMQ Broker is stale

### ISSUE THREAD

**Issue by phanimullapudi** [aws-controllers-k8s/community#831]
**Describe the bug**
Even after the broker is created after many minutes. The state of the broker is not updated back by ACK MQ controller.

**Steps to reproduce**
1. Use the MQ v.0.0.4 image
2. Create a RMQ broker using version 3.8.6
3. Notice the Broker is created in the AWS UI and its shows up and running
4. Check the status of the broker from ACK K8s environment like

`kubectl describe broker.mq.services.k8s.aws/ackrmq-broker-simple032221`
` Broker State:  CREATION_IN_PROGRESS`

5. You can notice the state of the broker is not updated back after  many minutes. I checked even after 30 minutes after creation

**Expected outcome**
The latest status of the broker should be updated back immediately

**Environment**

* Kubernetes version
v1.19.7
* Using EKS (yes/no), if so version? 
no
* AWS service targeted (S3, RDS, etc.)
MQ

@jaypipes FYI

**Comment by A-Hilaly** [comment]
I'm observing the same problem with dynamodb `Table` CRs. Re-queuing after an `sdkFind` call if tables are creating/updating solved the issue for me: https://github.com/A-Hilaly/ack-dynamodb-controller/blob/crd/table/pkg/resource/table/sdk.go#L397-L399
