### ISSUE TITLE
Enable crd variables and functions and hooks within hook templates

### ISSUE THREAD

**Issue by kumargauravsharma** [aws-controllers-k8s/community#838]
**Is your feature request related to a problem?**
Hook template implementation does not support:
* [variables (like .CRD)](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/ack/controller.go#L159-L162), 
* [controller functions](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/ack/controller.go#L53-L110), 
* and hooks within their templates

[Reference code: hook.go#L148-L159](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/ack/hook.go#L148-L159)

Thus, dynamic code generation capabilities of templates can not be utilized.
This results in static code inside the hook templates which is hard to reuse across multiple Custom Resources inside a service controller.

**Describe the solution you'd like**
Ability to  use crd variables, controller functions and hooks within hook templates from inside the service controllers.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by kumargauravsharma** [comment]
Related PR: https://github.com/aws-controllers-k8s/elasticache-controller/pull/36 where dynamic hook template is used to auto generate reusable setOutput method.

**Comment by RedbackThomson** [comment]
All of these fields are available when hooking as part of `sdk_end`.
