### ISSUE TITLE
Fix `service_bootstrap` such that `service_cleanup` runs and there are no leaking resources

### ISSUE THREAD

**Issue by mbaijal** [aws-controllers-k8s/community#845]
**Describe the bug**
This issue refers to a bug in the python test infra. If the `service_bootstrap.py` file fails to create all the resources required, the service_bootstrap function fails and thus the `bootstrap.yaml` file is not created at all. This means cleanup does not know what resources to delete and these are left hanging behind. 

**Steps to reproduce**
For example in the applicationAutoscaling tests, there was a case where the tests were failing due to failure to create the S3 bucket. Since one resource was not created, none was cleaned up leaving behind dynamoDB tables. Since accounts by default have a limit of 256 dynamoDB tables, we quickly ran out of limits leading to further test failures even after the S3 issue was fixed requiring manual cleanup everywhere.

**Expected outcome**
Ensure that the bootstrap.yaml file is created/written to even if some resources are not created. This guarantees whatever is created is deleted.
I have attempted to fix it only for the applicationAutoscaling service [in this PR](https://github.com/aws-controllers-k8s/applicationautoscaling-controller/pull/22) but we need a broader fix for all services and thus this logic should ideally be moved to common code in test-infra. 

**Environment**

* Kubernetes version - **any**
* Using EKS (yes/no), if so version? - **Happens on both KIND and EKS**
* AWS service targeted (S3, RDS, etc.) - **all services**

**Comment by RedbackThomson** [comment]
Fixed within https://github.com/aws-controllers-k8s/test-infra/pull/63
