### ISSUE TITLE
Remove Github Actions from all controller repos and runtime/code-generator

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#847]
Now that we are using [Prow](https://prow.ack.aws.dev/) for all CI jobs, we should remove all the older Github Actions (.github/workflows) from all service controller repositories as well as the runtime and code-generator repositories.

**Comment by RedbackThomson** [comment]
All service controller repositories should be cleaned of `.github` files - no controller should have their own Github action or templates. These are now managed in Prow and the `.github` repository, respectively.

`runtime` runs all of its tests in Prow, so `.github` can be safely deleted. `code-generator` runs unit tests in Prow, but does not run the `version-check` workflow. This will need to be added to Prow before deleting `.github`. `dev-tools` will eventually need to be migrated, but can be ignored for the moment.
