### ISSUE TITLE
DBCluster CRD missing from rds-controller 0.0.2 Helm chart

### ISSUE THREAD

**Issue by cogren1** [aws-controllers-k8s/community#851]
**Describe the bug**
The dbclusters.rds.services.k8s.aws Custom Resource Definition file is not present in /helm/crds. To make the controller happy, I had to dig through the repository to find /config/crd/bases/rds.services.k8s.aws_dbclusters.yaml and apply that manually to my K8 cluster.

**Steps to reproduce**
1. Install the 0.0.2 Helm chart for rds-controller onto a K8 cluster. (I used ArgoCD to handle the deployment.)
2. Look at the log for the controller pod. You should see this message:
`2021-06-25T15:22:33.640Z ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {"kind": "DBCluster.rds.services.k8s.aws", "error": "no matches for kind \"DBCluster\" in version \"rds.services.k8s.aws/v1alpha1\""}
github.com/go-logr/zapr.(*zapLogger).Error
/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/source/source.go:105
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:165
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:198
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/manager/internal.go:514`
`2021-06-25T15:22:33.640Z INFO controller-runtime.controller Starting workers {"controller": "dbsubnetgroup", "worker count": 1}`
`2021-06-25T15:22:33.640Z INFO controller-runtime.controller Stopping workers {"controller": "dbsubnetgroup"}`
`2021-06-25T15:22:33.640Z ERROR setup unable to start controller manager {"aws.service": "rds", "error": "no matches for kind \"DBCluster\" in version \"rds.services.k8s.aws/v1alpha1\""}`
3. If you apply /config/crd/bases/rds.services.k8s.aws_dbclusters.yaml, the error will go away.

**Expected outcome**
I expected to not see the aforementioned error.

**Environment**

* Kubernetes version v1.19.7 (Rancher Kubernetes Environment, RKE)
* Using EKS (yes/no), if so version?  No
* AWS service targeted (S3, RDS, etc.) RDS

**Comment by jaypipes** [comment]
>     1. Install the 0.0.2 Helm chart for rds-controller onto a K8 cluster. (I used ArgoCD to handle the deployment.)

Hi @cogren1, unfortunately this is not an issue with ACK (or the RDS controller). This is an issue with Helm, which does not support upgrading CRDs at all.

I know that FluxCD *does* have support for upgrading CRDs with Helm:

https://fluxcd.io/docs/components/helm/helmreleases/#crds

From reading the [ArgoCD Helm documentation](https://argoproj.github.io/argo-cd/user-guide/helm/), I cannot tell if something similar is possible in ArgoCD. :(

**Comment by cogren1** [comment]
Okay. The CRD file for DBCluster is absent from the helm/crds directory in the repository in v0.0.2, while the other CRD files are present. Is that directory not used for the Helm installation?

**Comment by jaypipes** [comment]
> Okay. The CRD file for DBCluster is absent from the helm/crds directory in the repository in v0.0.2, while the other CRD files are present. Is that directory not used for the Helm installation?

Oh, if that's the case, that's definitely a bug. :) I will look into this first thing in the morning.

**Comment by jaypipes** [comment]
@cogren1 I see you are absolutely correct that the `helm/crds` is missing dbcluster. I am not sure why our release script didn't generate the `helm/crds` file even though it generated the `config/crd/bases` file for dbcluster. Will look into this today and let you know what I find out!

**Comment by jaypipes** [comment]
@cogren1 OK, this was a total goof on my part, apologies. I simply forgot to `git add` the darn YAML file before `git commit`ing the release artifacts. :(

I will have a new release of RDS controller that includes the DBCluster Helm artifacts along with support for the DBClusterParameterGroup resource later today (it will be the 0.0.3 release).

Sorry for this, and thanks for your patience!
-jay

**Comment by jaypipes** [comment]
@cogren1 OK, the RDS controller v0.0.3 has now been released. It includes support for DBClusterParameterGroup resource and includes the missing DBCluster CRD files in the helm/crds directory. Thank you!

**Comment by cogren1** [comment]
No worries! Thank you for addressing this so quickly.
