### ISSUE TITLE
Enable Helm tests in e2e script

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#863]
**Describe the bug**
Helm tests are currently disabled due to them requiring `ack-generate` to build the Helm charts. This should not be necessary, as Helm charts should be published as part of the release process and not require code generation. 

**Steps to reproduce**
1. Enable the `test-helm.sh` invocation in the `kind-build-test.sh` script of `test-infra`
2. See the error `ERROR: Unable to find an ack-generate binary.`

**Expected outcome**
1. Helm tests run without requiring the `ack-generate` binary, or:
2. The test scripts correctly identify the version of `ack-generate` to build

**Comment by vijtrip2** [comment]
Closing in favor of https://github.com/aws-controllers-k8s/community/issues/885
