### ISSUE TITLE
CodeGen and Runtime v.0.5.0 delete causing crashloopbackoff

### ISSUE THREAD

**Issue by ryansteakley** [aws-controllers-k8s/community#866]
**Describe the bug**
When delete is called on a resource it causes a null pointer exception to be thrown and then the controller pod goes into crashloopbackoff. The resource does get deleted but the pod is stuck in a restarting state.

**Steps to reproduce**
Create a sagemaker resource using ACK i.e(endpoint) then attempt to delete it and throws an exception.

**Expected outcome**
Delete to run without crashloopbackoff. 

**Environment**
Sagemaker-Contoller

**Comment by ryansteakley** [comment]
Controller logs


2021-07-14T20:47:26.551Z	DEBUG	ackrt	<< r.cleanup	{"kind": "EndpointConfig", "namespace": "default", "name": "random-name", "generation": 2, "account": "024825446905", "role": "", "region": "us-west-2", "kind": "EndpointConfig", "namespace": "default", "name": "random-name", "generation": 2}
E0714 20:47:26.551606       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 684 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x186a800, 0x2b964a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x186a800, 0x2b964a0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/aws-controllers-k8s/sagemaker-controller/pkg/resource/endpoint_config.(*resource).RuntimeObject(0x0, 0x1e58ce0, 0xc0001d6938)
	/github.com/aws-controllers-k8s/sagemaker-controller/pkg/resource/endpoint_config/resource.go:56 +0x5
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).patchResource(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e9a940, 0xc000418070, 0x1e9a940, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:325 +0x20d
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).cleanup(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e8c6a0, 0xc0001de400, 0x1e9a940, 0xc000418070, 0x0, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:368 +0x6e8
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).reconcile(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e8c6a0, 0xc0001de400, 0x1e9a940, 0xc000418070, 0x9, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:178 +0x92
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Reconcile(0xc0001d8360, 0xc0008a4ce9, 0x7, 0xc0008a4cd0, 0xb, 0x0, 0xc033f1375c690750, 0xc0007ea1b0, 0xc0007c0908)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:169 +0x76e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001a26c0, 0x18e0d20, 0xc000c4f340, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001a26c0, 0x203000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001a26c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000bb6440)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000bb6440, 0x1e49360, 0xc000914210, 0x1, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bb6440, 0x3b9aca00, 0x0, 0x1, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000bb6440, 0x3b9aca00, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1639335]

goroutine 684 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x186a800, 0x2b964a0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/aws-controllers-k8s/sagemaker-controller/pkg/resource/endpoint_config.(*resource).RuntimeObject(0x0, 0x1e58ce0, 0xc0001d6938)
	/github.com/aws-controllers-k8s/sagemaker-controller/pkg/resource/endpoint_config/resource.go:56 +0x5
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).patchResource(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e9a940, 0xc000418070, 0x1e9a940, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:325 +0x20d
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).cleanup(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e8c6a0, 0xc0001de400, 0x1e9a940, 0xc000418070, 0x0, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:368 +0x6e8
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).reconcile(0xc0001d8360, 0x1e85720, 0xc0009144b0, 0x1e8c6a0, 0xc0001de400, 0x1e9a940, 0xc000418070, 0x9, 0x0)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:178 +0x92
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Reconcile(0xc0001d8360, 0xc0008a4ce9, 0x7, 0xc0008a4cd0, 0xb, 0x0, 0xc033f1375c690750, 0xc0007ea1b0, 0xc0007c0908)
	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.5.0/pkg/runtime/reconciler.go:169 +0x76e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001a26c0, 0x18e0d20, 0xc000c4f340, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001a26c0, 0x203000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001a26c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000bb6440)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000bb6440, 0x1e49360, 0xc000914210, 0x1, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bb6440, 0x3b9aca00, 0x0, 0x1, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000bb6440, 0x3b9aca00, 0xc000092360)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x305

**Comment by RedbackThomson** [comment]
@ryansteakley Would you mind checking that runtime#30 fixed this, and close the issue if it has. Thanks!

**Comment by ryansteakley** [comment]
fixed with v.0.6.0
