### ISSUE TITLE
RDS AutoScaling Edit not working

### ISSUE THREAD

**Issue by phanimullapudi** [aws-controllers-k8s/community#867]
**Describe the bug**
Unable to modify or add Second Autoscaling condition to the RDS Aurora - it does not work.

**Steps to reproduce**

-  Create RDS Aurora using ACK DBCluster
- Add Nodes to the Cluster using ACK DBInstances - add two instance - one for write and one for Reads
- Add AutoScaling using applicationautoscaling.services.k8s.aws for CPU

Now try to add second AutoScale condition on Threads or modify the above CPU autoscaling. Both does not work. You can notice below error

`2021-07-02T18:31:53.294Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "scalingpolicy", "request": "ns-kube2iamtesting-new/ack-scaling-policy-predefined", "error": "not implemented"}`

**Expected outcome**

- AutoScale changes should be applied or throw valid reason for not applying

**Environment**

* Kubernetes version
v1.19.7

* Using EKS (yes/no), if so version? 
No
* AWS service targeted (S3, RDS, etc.)
RDS, AutoScaling

**Comment by jaypipes** [comment]
@RedbackThomson mind taking a look into this one please?

**Comment by surajkota** [comment]
Thanks for using application autoscaling controller.
Looking at the error, my guess is that a scalingpolicy was created and you were trying to update it. Can you check if `status.ackResourceMetadata.arn` was populated? you might also see a bunch of alarm arns under status

Note: scalable target and scaling policy do not support updates. So, the controller throws "not implemented" error(which I agree is not descriptive and should be more updated) if you try to update it. To update the resource, please delete and recreate it

@phanimullapudi if my analysis above is not true, can you help us with steps to reproduce? (sample spec files)

**Comment by phanimullapudi** [comment]
@surajkota - Yes we are trying to update it and its not working. Deleting and creating it may work - but does not fit our work flow. We are looking for all CRUD operations for the controller to work. What are the next steps here ?

**Comment by jaypipes** [comment]
The [PutScalingPolicy API](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScalingPolicy.html) is used for both create and update of a scaling policy.

We currently only have the ability to override the operation type for an operation to a single string, as evidenced by this block in the controller's generator configuration:

https://github.com/aws-controllers-k8s/applicationautoscaling-controller/blob/main/generator.yaml#L3

I will work with @surajkota to add the ability to specify that a single API call is used for both create and update.

**Comment by surajkota** [comment]
@phanimullapudi Please try out the latest 0.1.0 release of the application autoscaling controller. @mbaijal has added support for updating ScalableTarget and ScalingPolicy.

In case the resource is created successfully, `status.creationTime` and `status.lastModifiedTime` fields will be set. In case of a successful update, `status.lastModifiedTime` will be updated.

In case of failure, check for the error message in `ACK.Terminal` or `ACK.Recoverable` conditions under `status.Conditions`.

This applies to both ScalableTarget and ScalingPolicy. Please re-open this issue if needed
