### ISSUE TITLE
Properly handle Parameters for RDS `DBParameterGroup` and `DBClusterParameterGroup`

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#869]
There are a number of problems with the way that RDS Parameter Groups handle parameters, and those problems surfaced in investigating #868.
                                                                                                
1) There is a separate DescribeDBParameters API call to get Parameters, even though the way you update Parameters is via the ModifyDBParameterGroup API. And yes, there is already a DescribeDBParameterGroups API call that returns the name of the DB Parameter Group and its parameter group family, but not its parameters.

Currently, we have a `Spec.Parameters` field that we register with the `DBParameterGroup` CRD from this section of the RDS controller's generator.yaml file:

https://github.com/aws-controllers-k8s/rds-controller/blob/1dedf846dc06951f23fe27aa366f95ae995c3c4d/generator.yaml#L149-L153

What this means is that we will need to add custom code to the `sdkFind` method of the DBParameterGroup resource manager that will call the `DescribeDBParameters` API call after the normal call to `DescribeDBParameterGroups` API call is made and the CR's Spec fields have been set from the Output shape. The additional call to DescribeDBParameters and the corresponding setting of the CR's `Spec.Parameters` field will need to go in the `sdk_find_post_set_output` hook point.

2) Individual parameters in the parameter group can only by "applied immediately" if the parameter apply type is "dynamic". Parameters of apply type "static" have to have the "pending-reboot" ApplyMethod set and RDS will barf out an error if you attempt to change a static parameter and pass the "immediately" value for ApplyMethod.

This problem and the sub-optimal user experience it manifests in for Terraform is highlighted effectively in a blog post here:

https://tech.instacart.com/terraforming-rds-part-3-9d81a7e2047f

We should be able to at the very least make the user experience more tenable in the ACK RDS controller by handling the whole "I set apply method to 'immediate' for a static appy-type parameter" mistake.

3) Parameters don't have to return a ParameterValue. Even though all parameters have some default value. And there isn't any API call to get the default value of a parameter. There is only an API call to get the *names* of parameters in the engine's default parameter group.

**Comment by chlunde** [comment]
@jaypipes a related issue is that if you remove a parameter, you have to call https://docs.aws.amazon.com/cli/latest/reference/rds/reset-db-parameter-group.html

I don't think code gen exposes this?

Out of curiosity, I wonder why there has to be a separate call for this. It's a bit painful that everything is a string pointer, but you can never send a nil. Should't a nil value here reset the value?

**Comment by jaypipes** [comment]
@robertgates55 yes, you can definitely set parameters. The problem is when you try to update certain parameters...

**Comment by robertgates55** [comment]
Hey, so I've definitely got an instance of this not working.

Helm version - `rds-chart`: `v0.0.19`

My object:
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBClusterParameterGroup
metadata:
  annotations:
    meta.helm.sh/release-name: robgates
    meta.helm.sh/release-namespace: dev
  creationTimestamp: "2022-03-12T18:17:04Z"
  finalizers:
  - finalizers.rds.services.k8s.aws/DBClusterParameterGroup
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: robgates-dbclusterparametergroup
  namespace: dev
  resourceVersion: "569098315"
  uid: 8f89be52-40a0-48b6-be3c-821c15c4f48f
spec:
  description: robgates-dbclusterparametergroup
  family: aurora-mysql5.7
  name: robgates-dbclusterparametergroup
  parameters:
  - applyMethod: immediate
    parameterName: innodb_strict_mode
    parameterValue: "0"
  - applyMethod: immediate
    parameterName: sql_mode
    parameterValue: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
  - applyMethod: immediate
    parameterName: character_set_server
    parameterValue: utf8
  - applyMethod: immediate
    parameterName: collation_server
    parameterValue: utf8_general_ci
  - applyMethod: pending-reboot
    parameterName: performance_schema
    parameterValue: "1"
  - applyMethod: immediate
    parameterName: max_connections
    parameterValue: "500"
status:
  ackResourceMetadata:
    arn: arn:aws:rds:eu-west-1:722198220036:cluster-pg:robgates-dbclusterparametergroup
    ownerAccountID: "722198220036"
  conditions:
  - lastTransitionTime: "2022-03-12T18:17:04Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
```

But, my resource via the console shows that none of the params have been set:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/7437497/158031506-5f9d1921-43d9-4b06-a169-b3b229fb3c4e.png">

Any advice on which of these might be causing my troubles? Is the parameterValue always a string, even for bools, ints, etc?

**Comment by jaypipes** [comment]
@robertgates55 I will need to look further into this. I will create a new e2e test in the rds-controller with your example above and reproduce.

**Comment by robertgates55** [comment]
Let me know if I can help in any way. Should I raise a specific ticket maybe?

**Comment by jaypipes** [comment]
> Let me know if I can help in any way. Should I raise a specific ticket maybe?

No need for separate ticket. I'll use this one :)

**Comment by robertgates55** [comment]
@jaypipes Any update on this? Can we help in any way to reproduce etc?

**Comment by jaypipes** [comment]
@robertgates55 the ACK core team and the RDS team had a meeting about this issue yesterday evening. It's a top priority for us to address ASAP. Having wrapped up some planning docs I've been busy with, I'll be able to start work on this tomorrow and by end of day tomorrow should have a rough timeframe to give you.

We are going to be taking the following approach:

* Change the `Spec.Parameters` field to be a `map[string]string`. This will contain a map, keyed by the parameter name (e.g. "innodb_buffer_pool_size") having values corresponding to the desired ParameterValue.
* `Spec.Parameters` will *only* contain parameters that you wish to change from the default value for that parameter.
* Parameters in `Spec.Parameters` that are dynamic (apply_method="immediate") will be batch-updated against the DBInstances associated with the DBParameterGroup by the ACK controller. Static parameters (apply_method="pending-reboot") will have their parameter values changed in the DBParameterGroup, but any associated DBInstances will need to be rebooted for those changes to take effect. We are still debating an appropriate way of conveying this information to the end user. We could add a `Condition` to the `DBInstance` stating that there are DBParameters that are pending apply. Or we could add a `Condition` to the DBParameterGroup saying there are DBInstances associated to the DBParamterGroup that will require a reboot for certain parameters to be applied. I'd love to hear your feedback on this topic!
* We will add a new field `Status.ParameterStatuses` which will represent the "status" information about all parameters that are in the `Spec.Parameters` field's keys. In other words, we will not be showing ALL the Parameters that could possibly be set for the given DBEngineFamily in `Status.ParameterStatuses`. We thought this would be entirely too much information (consider hundreds of database parameters....) Please let us know your thoughts on this decision!

**Comment by robertgates55** [comment]
Awesome - Thanks - keep us posted on progress.

`---`

>  We could add a Condition to the DBInstance stating that there are DBParameters that are pending apply. Or we could add a Condition to the DBParameterGroup saying there are DBInstances associated to the DBParamterGroup that will require a reboot for certain parameters to be applied. I'd love to hear your feedback on this topic!

My _instinct_ is to reflect it on the parametergroup rather than the instance, but there's obviously a one-to-many paramgroup-to-instance relationship so that might get awkward if the paramgroup is reused extensively. Does AWS use the 'maintenance window' to automatically restart/apply param changes on instances? (am wondering whether this is something that will always require manual intervention or whether it'll eventually become consistent)

`---`

> We will add a new field Status.ParameterStatuses which will represent the "status" information about all parameters that are in the Spec.Parameters field's keys. In other words, we will not be showing ALL the Parameters that could possibly be set for the given DBEngineFamily in Status.ParameterStatuses. We thought this would be entirely too much information (consider hundreds of database parameters....) Please let us know your thoughts on this decision!

100% agree. This should be about the parameters the user is wanting to add/modify/change, not _All_ parameters. It's analogous to pretty standard config file patterns so will definitely make sense. It makes me wonder if there's a better name for the `spec.Parameters` field to reflect the fact that it's actually `additionalParameters` (ie in addition to the family defaults), but that's probably more of an RDS API issue rather than an ACK problem to solve.

**Comment by robertgates55** [comment]
Any update here please?

**Comment by jaypipes** [comment]
> Any update here please?

Still working on it, @robertgates55. Hoping to complete the resource tagging (#1276) and parlay that work into the parameter support (it's a related code path)

**Comment by A-Hilaly** [comment]
>I'm unable to override the default values. It seems to work for the DBParameterGroup though.

I think this is correct. I didn't see the same fix applied to `DBCLusterParameterGroups`

**Comment by A-Hilaly** [comment]
We need to resume working on this ASAP

**Comment by brucegucode** [comment]
Since ACK for RDS is now transferring to rds platform team, I will give it to Andrew James Wilde's team

**Comment by jljaco** [comment]
> I will redirect this issue to Andrew

@brucegucode I am going to be picking up this issue, FYI.

**Comment by jljaco** [comment]
This should now be resolved.  Both `DBParameterGroup` and `DBClusterParameterGroup` now support the fields `Spec.ParameterOverrides` and `Status.ParameterOverrideStatuses` that can be used for managing user-defined overrides of default parameters.  See the relevant sections of `generator.yaml` for more details.

[Implementation for `DBParameterGroup`
](https://github.com/aws-controllers-k8s/rds-controller/pull/107)
[Implementation for `DBClusterParameterGroup`](https://github.com/aws-controllers-k8s/rds-controller/pull/133)
