### ISSUE TITLE
dynamodb controller helm chart release 0.0.3 refers to 0.0.2 controller image.

### ISSUE THREAD

**Issue by beezly** [aws-controllers-k8s/community#870]
**Describe the bug**
When following the instructions at https://aws-controllers-k8s.github.io/community/user-docs/install/ and installing the latest (0.0.3) dynamodb controller using helm, the 0.0.2 DynamoDB ACK controller container image is used.

**Steps to reproduce**
Pull the 0.0.3 dynamodb helm chart from public.ecr.aws/aws-controllers-k8s/chart:dynamodb-v0.0.3 and deploy it. The 0.0.2 container image will be deployed.

alternatively you can just inspect the values.yaml from the chart:
```
$ helm chart pull public.ecr.aws/aws-controllers-k8s/chart:dynamodb-v0.0.3
$ helm chart export public.ecr.aws/aws-controllers-k8s/chart:dynamodb-v0.0.3
$ grep tag: ack-dynamodb-controller/values.yaml
  tag: dynamodb-v0.0.2
```

**Expected outcome**
The 0.0.3 dynamodb ACK controller should be deployed.

**Environment**

* Kubernetes version N/A
* Using EKS (yes/no), if so version? M/A
* AWS service targeted (S3, RDS, etc.) DynamoDB

**Comment by RedbackThomson** [comment]
Thank you for reporting this @beezly .
I've updated the DynamoDB to use the latest ACK runtime (`v0.7.1`) and cut a new release for it (`v0.0.4`) - https://github.com/aws-controllers-k8s/dynamodb-controller/pull/11
https://github.com/aws-controllers-k8s/dynamodb-controller/releases/tag/v0.0.4
