### ISSUE TITLE
Automated test that Helm chart matches tagged version

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#872]
**Is your feature request related to a problem?**
In the past we have accidentally pushed mismatched versions of the Helm charts along with their corresponding tagged controller versions - https://github.com/aws-controllers-k8s/community/issues/870 

**Describe the solution you'd like**
An update to our CD scripts, in the `test-infra/cd` directory, that ensure the image tagged in the Helm chart matches the version tagged in the commit.

**Comment by vijtrip2** [comment]
Closing in favor of https://github.com/aws-controllers-k8s/community/issues/885
