### ISSUE TITLE
Enable Helm testing

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#885]
**Is your feature request related to a problem?**
sagemaker-controller v0.2.0 release was affected by - https://github.com/aws-controllers-k8s/code-generator/pull/141 and we had to re-publish the charts and controller to fix the issue.

Helm charts are created as part of the release process - https://aws-controllers-k8s.github.io/community/dev-docs/release/#release-steps.
PR builds run tests without helm charts. The helm charts should be tested before release.

**Describe the solution you'd like**

Helm Charts testing - 
- add a label to PR which triggers e2e tests on the release candidate (e.g. /test-release-candidate)
- helm charts are generated/updated on every commit and PR build tests run on the helm charts (#863)

Release scripts kept up to date -
- Run mock releases on every release of code-generator/runtime release to ensure release documentation is up to date and does not have any bugs

**Comment by vijtrip2** [comment]
> "add a label to PR which triggers e2e tests on the release candidate (e.g. /test-release-candidate)"

This is not needed. Enabling Helm tests in e2e testing will cover this.

> "PR build tests run on the helm charts"

Agree. As part of this task, I will reenable helm chart test/validation into e2e testing.

> "Run mock releases on every release of code-generator/runtime release to ensure release documentation is up to date and does not have any bugs"

Not as part of this task, but we have backlog item to test all controllers whenever ACK core libraries i.e. code-generator and runtime change. https://github.com/aws-controllers-k8s/community/issues/892

**Comment by vijtrip2** [comment]
https://github.com/aws-controllers-k8s/test-infra/pull/85 should provide testing for helm artifacts during PR. I will now work on adding a validation in post-submit release job to validate that image tag referred in values.yaml file is equal to semver release of the controller.

**Comment by RedbackThomson** [comment]
Looks like it's all done! Thanks @vijtrip2
