### ISSUE TITLE
code-generator v0.9.0 issue incompatibleAssign string / *string

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#888]
**Describe the bug**
when using v0.9.0 code-generator we see an issue in lambda/function/zz_controller.go:

https://github.com/haarchri/provider-aws/blob/code-gen-v0.9.0/pkg/controller/lambda/function/zz_controller.go#L257

```
ERRO Running error: buildir: analysis skipped: errors in package: [/Users/haarchri/Documents/sfn/move_api_version/provider-aws/pkg/controller/lambda/function/zz_controller.go:257:22: cannot use f15elem (variable of type string) as *string value in argument to append /Users/haarchri/Documents/sfn/move_api_version/provider-aws/pkg/controller/lambda/function/zz_controller.go:255:10: f15iter declared but not used -: could not load export data: no export data for "github.com/crossplane/provider-aws/pkg/controller/lambda/function"] 
10:25:42 [FAIL]
```

![image](https://user-images.githubusercontent.com/21083497/128151409-7013c16d-99b1-4668-8fc3-e5c6e8a2adf0.png)

**Steps to reproduce**

make reviewable

**Comment by A-Hilaly** [comment]
It looks like this is caused by a type mismatch between the `Layers` field in the input and output schemas (`[]string` is used for the input and `[]struct{...}` for output). https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

**Comment by haarchri** [comment]
If i am correct the problem needs to be fixed here ?

**Comment by jaypipes** [comment]
@haarchri yes, this is a problem that still needs to be fixed in our code-generator. I'm not sure when we will be able to get to this. For now, it may be necessary to manually edit the code that is output by the code generator...

**Comment by vijtrip2** [comment]
This issue relates to a very old version of code-generator.
Please reopen if this issue still exists in most recent code-generator release
