### ISSUE TITLE
Field names containing an initialism should align with Go styling

### ISSUE THREAD

**Issue by brycahta** [aws-controllers-k8s/community#889]
**Describe the bug**
After generating ec2-controller code fields such as *DpdTimeoutAction* and *IoPerformance* should be DPDTimeoutAction and IOPerformance, respectively.

**Steps to reproduce**
* generate ec2-controller code
* navigate to apis/v1alpha1/types.go

**Expected outcome**
* initialisms should be capitalized fully when exported and lowercases fully when not exported according to Go style guidelines: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Additional Notes**
*  Starting point: https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/names/names.go

**Comment by RedbackThomson** [comment]
We already support this. Try adding the following lines to the `initialisms` array in the `names.go` file:

```golang
{"Dpd", "DPD", "dpd", regexp.MustCompile("Dpd", regexp.None)},
```
and
```golang
{"Io", "IO", "io", regexp.MustCompile("Io", regexp.None)},
```
