### ISSUE TITLE
New Prowjobs to validate changes in ACK core libraries.

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#892]
Currently ACK deals with following two problems:
a) **Late side-effects of code-generation changes:** If a bug was introduced in code-generator, we do not catch it until a service team regenerates their controller and the controller uses the buggy part of code-generator.

b) **Keeping service controllers up to date:** Currently It is very easy for service controllers to go out of date because on every release of code-generator/runtime We have to manually regenerate controller and raise PRs. 

To solve the above problem, There should be 
a) A PreSubmit prowjob to AUTOMATICALLY validate code-generator changes using multiple service controller generation. Unit testing and basic lint of helm/kustomize files would be a decent start for validation. But it can be further extended to e2e testing and validating helm/kustomize artifacts as well. 

b) PostSubmit prowjobs to update, regenerate service-controller whenever a new runtime, code-generator release is made respectively. Raising PRs from this process should also be automated.

**Comment by RedbackThomson** [comment]
Sometimes we want to introduce changes to the code-generator that break the existing configuration (see changes to print columns). In these cases, the presubmit jobs would fail, but the changes are still valid. Is there a mechanism to introduce these changes safely?

**Comment by vijtrip2** [comment]
> Sometimes we want to introduce changes to the code-generator that break the existing configuration (see changes to print columns). In these cases, the presubmit jobs would fail, but the changes are still valid. Is there a mechanism to introduce these changes safely?

* Excellent point. Hopefully such changes are very rare and we can treat them like exception cases/work around them. (Ignore auto-regeneration PRs/UnitTest failures for these exceptional scenarios.)
* Initial implementation can be kept simpler and faster to rollout by ignoring this part during design.
