### ISSUE TITLE
Add a Helm chart values schema file

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#899]
**Is your feature request related to a problem?**
It is possible to deploy our Helm charts with incorrect values, especially for fields that are booleans or enumerations. If values are provided, but are incorrect, the chart will still be applied but may be malformed.

**Describe the solution you'd like**
Deploy a `values.schema.json` file along with all of the Helm charts - https://helm.sh/docs/topics/charts/#schema-files

This schema would include value options for boolean or enumeration string types. If the user attempts to install the chart with incorrect values, it will be blocked with an appropriate error message.

**Comment by philnichol** [comment]
@RedbackThomson @vijtrip2 hope you don't mind, I've raised the above PR which should address this, left a couple of questions in the description, please let me know if you'd like me to address them?
