### ISSUE TITLE
New ObjectMeta method in AWSResource interface

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#905]
### Problem:
Current implementation of `AWSResource.SetObjectMeta(metav1.ObjectMeta)` accepts the concrete type `k8s apimachinery/metav1.ObjectMeta`, while `AWSResource.MetaObject()` returns the `k8s apimachinery/metav1.Object` interface.

When trying to update the AWSResource metadata from `AWSResource.MetaObject()` , it does work because a pointer type is returned from all the AWSResource implementations in ACK but it is not explicit for code readers.

A sample current approach looks like
```
obj := res.MetaObject()
annotations.AddX(obj)
```

While a more readable approach would be 
```
obj := res.ObjectMeta()
updatedObj := annotations.AddX(obj)
res.SetObjectMeta(updatedObj)
```

### Possible solutions
a) add another method `AWSResource.ObjectMeta()` which returns the concrete type `k8s apimachinery/metav1.ObjectMeta`. This concrete return type can be updated and then set into AWSResource with `AWSResource.SetObjectMeta` method.

b) Create a factory method `NewObjectMeta(metav1.Object) metav1.ObjectMeta` inside `k8s apimachinery`. This method will allow the conversion of any `metav1.Object` interface implementation to be used as `metav1.ObjectMeta`

**Comment by RedbackThomson** [comment]
Is there a particular issue that you are trying to solve that requires this solution? I think there is a strong reason to keep the object meta that comes with a given `AWSResource`. If you require changing particular fields, like `finalizers` or `annotations`, I think those should be handled separately.

**Comment by vijtrip2** [comment]
> Is there a particular issue that you are trying to solve that requires this solution? I think there is a strong reason to keep the object meta that comes with a given `AWSResource`. If you require changing particular fields, like `finalizers` or `annotations`, I think those should be handled separately.

I am trying to update the metadata/annotations here. https://github.com/aws-controllers-k8s/runtime/pull/46

Maybe I am overthinking this but it seems weird to me that these methods accept interface type parameter, perform updates and do not return the updated object. (What If implementation of the interface is not a pointer type. Sounds like a bad assumption to me honestly.) Hence I wanted these methods that cause side-effects to be explicit and have a return type.

Anyways, currently in the above mentioned PR, I did follow exactly how we are updating the finalizers and it works. https://github.com/kubernetes-sigs/controller-runtime/blob/v0.9.6/pkg/controller/controllerutil/controllerutil.go#L352 

Please  let me  know if I am overthinking it or it makes sense to add return  types to methods with side-effects without explicit pointer type in the parameters.

**Comment by RedbackThomson** [comment]
Okay, I see what you mean - I just checked out your annotations PR.

Are you suggesting that we should be returning a deep copy of the object meta when returning it? I think it's necessary for some code paths that the method returns the original - because modifications to it are then directly applied (as you show in your first code example). You would prefer to treat it as an immutable object?

**Comment by vijtrip2** [comment]
> "Are you suggesting that we should be returning a deep copy of the object meta when returning it?"

No, we can return the same object after modifying it in the method call.

> "You would prefer to treat it as an immutable object?"

Not necessarily. Even if we mutate the same object, having a return type of same object helps being explicit. (Like we do when we return latest objects from AWSResourceManager.Update() calls )
