### ISSUE TITLE
Question: API Gateway

### ISSUE THREAD

**Issue by eliecer2323** [aws-controllers-k8s/community#906]
Hello everyone,

I'm trying to create a REST API with the apigatewayv2.services.k8s.aws controller but in the documentation I don't find a way to indicate if it should be created as a REST or HTTP API, isn't it? does it only work with HTTP API?, will it work with REST API in the future?. Thanks for your support.

**Comment by vijtrip2** [comment]
Hi @eliecer2323 , the ACK controller is specifically for 'apigatewayv2' service which only supports HTTP APIs and unfortunately it will not work for REST APIs.

In future support for 'apigateway' (REST APIs) can be added but it is not in our current plans.

**Comment by eliecer2323** [comment]
Got it, thank you
