### ISSUE TITLE
flakyness in adoption reconciler because of 2 step patching

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#935]
**Describe the bug**
https://github.com/aws-controllers-k8s/runtime/pull/47 introduced patching status after creating the resource in adoption reconciler. This is useful when the resource's primary identifier field is part of status like ARN, vpcid etc.

When we run tests repeatedly, we are seeing this error in some of the runs 

```
021-09-05T15:52:59.130Z    ERROR   controller-runtime.controller   Reconciler error    {"controller": "adoptedresource", "request": "default/adopt-sdk-endpoint-ua8qko6lpdyuijpmdx1-config", "error": "Operation cannot be fulfilled on endpointconfigs.sagemaker.services.k8s.aws \"sdk-endpoint-ua8qko6lpdyuijpmdx1-config\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
    /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```

after which the adoption reconciler fails with resource already exists error from the next reconcile loop since the resource was already created
```
2021-09-05T15:53:00.198Z    ERROR   controller-runtime.controller   Reconciler error    {"controller": "adoptedresource", "request": "default/adopt-sdk-endpoint-ua8qko6lpdyuijpmdx1-config", "error": "endpointconfigs.sagemaker.services.k8s.aws \"sdk-endpoint-ua8qko6lpdyuijpmdx1-config\" already exists"}
```

I suspect this is happening because once the spec is available, the target resource reconciler kicks in and maybe it is modifying the resource before adoption reconciler patches the status 

and @vijtrip2 suspects

> This maybe the culprit. If we use DeepCopy in second parameter, we lose the resourceVersion updates from etcd.
> ```
> err := r.kc.Patch(
> 		ctx,
> 		res.DeepCopyObject(),
> 		client.MergeFrom(orig),
> 	) 
>```

**Steps to reproduce**
Run test_adopt_endpoint.py repeatedly

**Expected outcome**
Robust Adoption reconciler

**Comment by surajkota** [comment]
if resource `isAdopted`, should the target resource reconciler requeue until both spec and status are non-nil?

**Comment by RedbackThomson** [comment]
Another solution I may propose is to have an annotation that temporarily blocks reconciliation. We create the resource with that annotation, apply the status, then remove the annotation.
