### ISSUE TITLE
apigatewayv2 - DomainNameConfigurations missing in DomainNameObservation

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#951]
for apigatewayv2 in DomainNameObservation struct - DomainNameConfigurations struct is missing

https://github.com/aws/aws-sdk-go/blob/v1.37.10/service/apigatewayv2/api.go#L12137-L12158

at the moment:
```
type DomainNameObservation struct {
	APIMappingSelectionExpression *string `json:"apiMappingSelectionExpression,omitempty"`

	DomainName *string `json:"domainName,omitempty"`
}
```

what we need:
```
type DomainNameObservation struct {
	APIMappingSelectionExpression *string `json:"apiMappingSelectionExpression,omitempty"`

	DomainName *string `json:"domainName,omitempty"`

        DomainNameConfigurations []*DomainNameConfiguration `json:"domainNameConfigurations,omitempty"`
}
```

we have one Issue in Crossplane Provider-AWS for this: https://github.com/crossplane/provider-aws/issues/826

**Comment by vijtrip2** [comment]
Hi Thanks for pointing it out.
APIGatewayv2 controller is currently at aws-sdk-go v1.35.5 https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/apis/v1alpha1/ack-generate-metadata.yaml#L8

We are working on upgrading it but have some problems with how controller-gen handles maps of maps , which were introduced after v1.35.5

**Comment by vijtrip2** [comment]
apigatewayv2 controller now updated to v1.37.10
https://github.com/aws-controllers-k8s/apigatewayv2-controller/blob/main/apis/v1alpha1/ack-generate-metadata.yaml#L8
