### ISSUE TITLE
All links in the Getting Started goes to Page Not Found

### ISSUE THREAD

**Issue by lamw** [aws-controllers-k8s/community#952]
**Describe the bug**
All links in the [Getting Started](https://github.com/aws-controllers-k8s/community#getting-started) section of repo readme is going to page not found. 

It looks like base docs URL may have changed from `/community/*` to `/community/docs/community/*` 

`services controllers` should be https://aws-controllers-k8s.github.io/community/docs/community/services/
`project stages` should be https://aws-controllers-k8s.github.io/community/docs/community/releases/#project-stages
`install` should be https://aws-controllers-k8s.github.io/community/docs/user-docs/install/
`reference documentation` should be https://aws-controllers-k8s.github.io/community/reference/

**Comment by RedbackThomson** [comment]
Thanks William! Updated as part of https://github.com/aws-controllers-k8s/community/commit/eb3ddaffe6ff505a2f4dae6e11885e1275a21d27
