### ISSUE TITLE
ec2 transitgateway code-gen problem zz_conversions.go

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#957]
faced some problem in ec2 transitgateway during code-gen in crossplane project crossplane/provider-aws#831 in func GenerateModifyTransitGatewayInput

https://github.com/haarchri/provider-aws/blob/ec2-transitgateway/pkg/controller/ec2/transitgateway/zz_conversions.go#L209-L272

wrong:
cr.Spec.ForProvider.Options.AddTransitGatewayCIDRBlocks
cr.Spec.ForProvider.Options.AssociationDefaultRouteTableID
cr.Spec.ForProvider.Options.PropagationDefaultRouteTableID
cr.Spec.ForProvider.Options.RemoveTransitGatewayCIDRBlocks

correct:
cr.Spec.ForProvider.Options.TransitGatewayCIDRBlocks
cr.Spec.ForProvider.Options.DefaultRouteTableAssociation
cr.Spec.ForProvider.Options.DefaultRouteTablePropagation
cr.Spec.ForProvider.Options.TransitGatewayCIDRBlocks

https://github.com/crossplane/provider-aws/pull/831
https://github.com/aws-controllers-k8s/community/issues/489

**Comment by A-Hilaly** [comment]
@haarchri Are you still experiencing the same issue? i see that https://github.com/haarchri/provider-aws/blob/ec2-transitgateway/pkg/controller/ec2/transitgateway/zz_conversions.go#L209-L272 got the correct field names

**Comment by haarchri** [comment]
@A-Hilaly we skip the fields in generator-config - in general i think we have a problem with 4 fields:
https://github.com/haarchri/provider-aws/blob/ec2-transitgateway/apis/ec2/v1alpha1/generator-config.yaml#L86-L89

**Comment by vijtrip2** [comment]
Please reopen if this still blocks you
