### ISSUE TITLE
docs: broken links to contributor documentation

### ISSUE THREAD

**Issue by twz123** [aws-controllers-k8s/community#960]
**Describe the bug**
I noticed that the CONTRIBUTING pages in at least s3 and sagemaker controller point to outdated URLs and return 404 pages.

**Steps to reproduce**
They use `https://aws.github.io/aws-controllers-k8s/dev-docs/overview/`, whereas I reckon this changed to `https://aws-controllers-k8s.github.io/community/docs/community/overview/`.

**Expected outcome**
Up to date docs. Not sure if there's some templating in place that manages those files in the controller repos, or if it's required to raise individual PRs for those.

**Comment by vijtrip2** [comment]
Thank you pointing out the inconsistency.
In this [PR](https://github.com/aws-controllers-k8s/code-generator/pull/199), I have updated the `build-controller.sh` to keep the files in all service controllers consistent with the files in `code-generator` repository.

On the next release of `code-generator`, all the service controller will be automatically build and will have the updated/correct files.

**Comment by surajkota** [comment]
In addition to fixing this, can we set up a redirection from old links?

e.g. links in this blog are broken: https://aws.amazon.com/blogs/containers/aws-controllers-for-kubernetes-ack/

**Comment by vijtrip2** [comment]
> In addition to fixing this, can we set up a redirection from old links?
> 
> e.g. links in this blog are broken: https://aws.amazon.com/blogs/containers/aws-controllers-for-kubernetes-ack/

I would rather have us just update the blog post content if it is possible than setting up some redirection.

**Comment by surajkota** [comment]
@vijtrip2 Blog post is just a sample. We dont know how many other blogs, medium posts readmes etc. might be broken. Is it complicated to setup?

**Comment by vijtrip2** [comment]
PR for doc links fix is merged now. For the new release of every controller, the docs link will be correct.
