### ISSUE TITLE
docs explaining various configurations in helm charts

### ISSUE THREAD

**Issue by surajkota** [aws-controllers-k8s/community#964]
https://aws-controllers-k8s.github.io/community/docs/user-docs/install/ to include details about
the values that are required before installing any helm chart like `aws.account_id`. Talk about various configurations and possibly include samples on how to:

- instal the controller in cluster scope and namespace scope
- use private link
- setting log levels etc.

**Comment by RedbackThomson** [comment]
We are fine with the comments we have inline in the Helm chart values files
