### ISSUE TITLE
Documentation regarding helm 3.7 is incorrect

### ISSUE THREAD

**Issue by alphamichael** [aws-controllers-k8s/community#988]
**Describe the bug**
The installation docs prescribe using a version of helm greater than or equal to 3.7 due to a breaking change introduced in helm 3.7.

This appears to be incorrect and should instead say use a version of helm **less than** 3.7?

**Steps to reproduce**
Using helm 3.7

```bash
$ helm version 
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
$ export HELM_EXPERIMENTAL_OCI=1 ; helm pull oci://public.ecr.aws/aws-controllers-k8s/s3-chart --version v0.0.4 -d s3-chart
Error: manifest does not contain minimum number of descriptors (2), descriptors found: 1
$
```

Using 3.6.3:

```bash
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
$ export HELM_EXPERIMENTAL_OCI=1 ; helm pull oci://public.ecr.aws/aws-controllers-k8s/s3-chart --version v0.0.4 -d s3-chart
v0.0.4: Pulling from public.ecr.aws/aws-controllers-k8s/s3-chart
$
```

**Expected outcome**
Documentation regarding helm 3.7 to be accurate.

**Comment by vijtrip2** [comment]
Thank you for bringing it to our attention.
In this case, v0.0.4(released 10 days ago) was generated using helm 3.6

Coming week, we will generate the new release of all ACK controllers, which will be compatible with helm 3.7, and also consistent with our documentation.

**Comment by vijtrip2** [comment]
Please reopen if you still see concerns.
ACK team released new controllers which are compatible with Helm-3.7 and consistent with documentation.

**Comment by samruthr** [comment]
@vijtrip2 I am still encountering this issue with the SageMaker chart v0.1.0:
```
➜ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
➜ helm pull oci://public.ecr.aws/aws-controllers-k8s/sagemaker-chart --version v0.1.0 -d sagemaker-chart
Error: manifest does not contain minimum number of descriptors (2), descriptors found: 1
```

**Comment by vijtrip2** [comment]
Yes because sagemaker controller haven't been built and released with helm3.7 . 
Sorry for the inconsistency among helm version compatibility but sagemaker team handle release of their own controller. I will reach out to them to make a new release. Current release should work well with helm 3.6
