### ISSUE TITLE
Update installation documentation to latest version compatibility

### ISSUE THREAD

**Issue by vijtrip2** [aws-controllers-k8s/community#996]
* Follow ACK installation instruction from https://aws-controllers-k8s.github.io/community/docs/user-docs/install/ and update the instructions if some commands are out of date
* Include s3 Bucket creation and deletion as validation of controller installation

**Comment by RedbackThomson** [comment]
Would you mind updating the title of this issue to be more specific? Perhaps "Update installation documentation to latest version compatibility"?
