### ISSUE TITLE
add apigatewayv2 controller via `Chart.yaml` dependecies

### ISSUE THREAD

**Issue by oxeye-schmil** [aws-controllers-k8s/community#997]
Hi,

I would like to add the apigatewayv2 controller by deploying a helm chart with the following dependencies

apiVersion: v2
name: aws-resources
appVersion: "0.0.1"
version: 0.0.1
description: AWS Resources
dependencies:
  - name: aws-load-balancer-controller
    version: "1.2.7"
    enable: true
    repository: "https://aws.github.io/eks-charts"
  - name: apigatewayv2-chart
    version: "0.0.6"
    enable: true
    repository: "oci://public.ecr.aws/aws-controllers-k8s"

It works for the load balancer controller but not for apigatewayv2 controller
I get the following error

Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://public.ecr.aws/aws-controllers-k8s/" chart repository:
        object required
...Successfully got an update from the "https://aws.github.io/eks-charts" chart repository
Saving 2 charts
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading apigatewayv2-chart from repo oci://public.ecr.aws/aws-controllers-k8s/
Save error occurred:  could not download oci://public.ecr.aws/aws-controllers-k8s//apigatewayv2-chart: public.ecr.aws/aws-controllers-k8s//apigatewayv2-chart:0.0.6: not found
Error: could not download oci://public.ecr.aws/aws-controllers-k8s//apigatewayv2-chart: public.ecr.aws/aws-controllers-k8s//apigatewayv2-chart:0.0.6: not found

Is it even possible to use it that way?

Schmil

**Comment by vijtrip2** [comment]
>" oci://public.ecr.aws/aws-controllers-k8s//apigatewayv2-chart"

Why does it have two '/' between `aws-controllers-k8s` and `apigatewayv2-chart` ? That does not seem right.

Also look at the trailing '/' here for apigatewayv2-chart
```
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading apigatewayv2-chart from repo oci://public.ecr.aws/aws-controllers-k8s/
```

**Comment by oxeye-schmil** [comment]
There was a typo in my Chart.yaml when I ran it
this is the current error
```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://public.ecr.aws/aws-controllers-k8s" chart repository:
        object required
...Successfully got an update from the "https://aws.github.io/eks-charts" chart repository
Saving 2 charts
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading apigatewayv2-chart from repo oci://public.ecr.aws/aws-controllers-k8s
Save error occurred:  could not download oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:0.0.6: not found
Error: could not do
```

**Comment by oxeye-schmil** [comment]
Prorbably the repo url is wrong but couldn't find the right one

**Comment by vijtrip2** [comment]
Found the issue. The version is v0.0.6 and not 0.0.6

It worked for me.
```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://public.ecr.aws/aws-controllers-k8s" chart repository:
        object required
...Successfully got an update from the "https://aws.github.io/eks-charts" chart repository
Saving 2 charts
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading apigatewayv2-chart from repo oci://public.ecr.aws/aws-controllers-k8s
Pulled: public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart:v0.0.6
Digest: sha256:5416d770d6b25d6d72c26362c836c9e1b72f2736b42ada3f54eeb443aa5a49bd
Deleting outdated charts
```

**Comment by oxeye-schmil** [comment]
Thanks
But you are still getting 
```Unable to get an update from the "oci://public.ecr.aws/aws-controllers-k8s" chart repository:
        object required```

**Comment by RedbackThomson** [comment]
You may need to append the chart name to the repository?

For example, `repository: "oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart"`

**Comment by RedbackThomson** [comment]
Have you upgraded your Helm CLI version to 3.7?

**Comment by vijtrip2** [comment]
> Have you upgraded your Helm CLI version to 3.7?

Yes.
```
ubuntu@ip-172-31-3-174:/tmp/chart/s3-chart$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

**Comment by vijtrip2** [comment]
@oxeye-schmil , I asked the question on similar issue in helm repository.
https://github.com/helm/helm/issues/10128#issuecomment-930582803

**Comment by seocam** [comment]
I'm having the same issue using GCP Artefact Registry. I'm able to download the chart but I get the following:

```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://us-docker.pkg.dev/project/repo" chart repository:
	object required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading pgbouncer from repo oci://us-docker.pkg.dev/project/repo
Pulled: us-docker.pkg.dev/project/repo/pgbouncer:0.2.0
Digest: sha256:fa11e5eadac5f07bf20489ea37b4c289f6579c158efab7c35bdf422419511ae6
Downloading redis from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
```
